### ISSUE TITLE
feat(reddit): custom downloading options of videos and pictures

### ISSUE THREAD

**Issue by Goldmaster** [ReVanced/revanced-patches#1003]
### Application

Reddit

### Issue

when downloading content such as images or videos, very often the content is often just a string of letters and thats it. When a user wants to organise the downloaded content into folders, often it can be quite teadierus due to the filenames.

### Patch

The idea of this patch would be an option to allows the user to customise the folder structure of how said content is downloaded. For example, `%subreddit%/%op% - yyyy-mm-dd - %title% (%id%).ext` if applied to say this post https://www.reddit.com/r/memes/comments/gyfedz/a_short_story/ will result in a file saved in the folder path of `/memes/rextraneous - 2020-06-07 - A short story (70zdjiilli351).jpg`

### Motivation

It helps people who download save content from Reddit better organise and find the content if needed. This ensures that original content can be found and seen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
