### ISSUE TITLE
feat(youtube/theme): in app option to change theme colors

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches#1013]
### Application

YouTube

### Issue

Changing the theme via the options.json file doesn't work anymore after the seekbar color preference was added.

### Patch

Like changeable seekbar colors but with the background color, similar to what the patch does with the options file before.

### Motivation

Easier way to change themes

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
