### ISSUE TITLE
feat (Messenger): Hide Notes from top of Messenger

### ISSUE THREAD

**Issue by kazimmt** [ReVanced/revanced-patches#102]
### Feature description

Recently Meta adds a new feature in Messenger.
Whenever any of your friends adds a notes, it's appear on top of Messenger homepage.
![notes](https://github.com/ReVanced/revanced-patches/assets/82371061/989ae70b-8df4-426a-b6e9-a27514956d86)

- A patch which hides these notes would be good for users.

### Motivation

Texting friends or family members is the main reason most people uses Messenger. There is no need to see someone's notes on top of Messenger homepage. That's completely unnecessary & it really hurt eyes.
We want a clean Messaging platform
Not with these notes from other friends.
The place they add notes not is not suitable in any ways.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by tamas646** [comment]
In my opinion the whole "who is currently online" pane could be hidden. It's sometimes disturbing, especially when it loads a little more later when I open the app and I end up in a different conversation than I wanted to select.

@kazimmt did you mean the whole pane or just the notes above the profile pictures?

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by kazimmt** [comment]
Ok, no problem
Still I appreciate your work 🎪❤️🍿
