### ISSUE TITLE
feat(Pinterest): Remove / hide ads

### ISSUE THREAD

**Issue by Cederick** [ReVanced/revanced-patches#1038]
### Application

Pinterest

### Issue

Browsing through Pinterest via the app can be really annoying because the chance of clicking on an ad is really high. That's the case because it's just full of them to a point where it's sometimes more ads than content.

### Patch

I'd like a patch that gets rid of at least some advertisement on Pinterest.

### Motivation

Pinterest has been an important tool to get inspiration or just organiser content to your liking for all kinds of reasons. It's also one of the most popular and we'll known apps in this market or in the Playstore in general. And having to endure even more data harnessing and selling when using the app compared to using the website is a little excessive at this point 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by AlfaPSH** [comment]
try to patch the apk using lspatch and minminguard, if u want i can share the patched apk

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by olivvxr** [comment]
Can we look into this again please at some point, the Pinterest ads are unbearable
