### ISSUE TITLE
feat: Option to hide "Create Post" button while sharing a video

### ISSUE THREAD

**Issue by Aphotic** [ReVanced/revanced-patches#104]
### Feature description

Option to hide "Create Post" button while sharing a video

only content creators use this & most average users will only have fvcked up muscle memory because of this.
thanks

![Screenshot_20231117-072003_YouTube](https://github.com/ReVanced/revanced-patches/assets/30921064/2e66dfa5-61b1-4e51-9669-886a0c904ac4)

### Motivation

create a post button that most people don't use is a new addition in place of the most used "copy link button" and just hiding it will help our muscle memory after years and add to the vast collection of hideable Vanced options! ^^

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made. which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
