### ISSUE TITLE
feat(patch): Community post

### ISSUE THREAD

**Issue by egscodes** [ReVanced/revanced-patches#1053]
### Application

youtube

### Issue

Ok so when blocking community post i feel that it could be better since it blocks the one in the channels

### Patch

Basically if possible add 2 toggles
1. will simply remove the community post from the main screen
2. will hide the one in the youtubers channel

### Motivation

Simply removing them all together feels weird and leaves a blank tab in the youtubers channels.

I do like the fact that it removes the one in the main screen (takes to much space tbh)
But i don't like that it removes the one in there channels

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
