### ISSUE TITLE
feat(X / Twitter): twitter won't show quote tweet of nsfw content.

### ISSUE THREAD

**Issue by TheRealAaronPrince** [ReVanced/revanced-patches#1089]
### Application

twitter

### Issue

quote tweets of nsfw content give "This quoted Tweet is unavailable" when that isn't true. you can load the tweet in the browser, which shows the link and lets you see the tweet from there.

### Patch

if making the quoted tweet load anyway isn't possible, then forcing the app to display the link to the tweet would be appriciated.

### Motivation

not only is it a frustrating issue, twitter is directly lying to users. it seems to be common among nsfw groups to be suggested far less.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
