### ISSUE TITLE
feat(patch): Hide sort by "Members" pill in comments section.

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches#1140]
### Application

Youtube

### Issue

The issue is that Youtube separates comments from members in the comments section with an annoying mid-comments section that shows up while scrolling  even if you sort comments by "Top". The patch should hide the unnecessary members section from showing up mid comments and merge members comments together with the other comments in the comment section, + add an ability to hide "sort by" "members" pill option as it doesn't really matter if the comment is from a member or not.
![Screenshot_20230417_212839_YouTube](https://user-images.githubusercontent.com/30195961/232591007-ad51e072-542b-4bf9-be52-13614566a319.jpg)

### Patch

Introduce an option that merges channel's members comments to show in between along normal comments (top category and Newest category) like it used to be.
Additionally add an ability to hide sort by "members" pill since it doesn't really matter if the comment is from a member or not for an end viewer.

### Motivation

Cleans up comments section from unrelevant tabs displaying in between browsing comments.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
