### ISSUE TITLE
feat(YouTube): Save community images / gifs

### ISSUE THREAD

**Issue by rollingmoai** [ReVanced/revanced-patches#1146]
### Application

YouTube (com.google.android.youtube)

### Issue

Ability to save community images/gifs, which you currently can't do. Useful for meme channel pages.

### Patch

A way to long-press the image and save it to the device.

### Motivation

Usually, the only "way" you can save an image is just to screenshot it, but it won't work on GIFs anyway. Nonetheless, it's cumbersome, and the best solution is directly saving the image.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Bakr-Ali** [comment]
Why was my comment marked as spam? I genuinely want the ability to copy the links of the community posts. It will generally somewhat solve this issue too; if we can copy the link of the post, then we can simply open the post directly in the browser and save the image there. It would also allow us to copy the text of the community post too.

**Comment by oSumAtrIX** [comment]
Because the comment does not add additional information to existing info

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
