### ISSUE TITLE
feat(YouTube): Always show seekbar in bottom of fullscreen player

### ISSUE THREAD

**Issue by fortissimo247** [ReVanced/revanced-patches#1151]
### Application

YouTube (com.google.android.youtube)

### Issue

It is inefficient to tap each time to check the progress of the video in fullscreen.

### Patch

![fullscreen seekbar](https://user-images.githubusercontent.com/125655800/232209301-d5b769d5-507d-4c62-b82e-db24986c067e.png)

I want patch the adding option that always show seekbar in fullscreen like above picture.

### Motivation

I just think it will be useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
