### ISSUE TITLE
feat(patch): Ability to configure YouTube comment translation 

### ISSUE THREAD

**Issue by LiphiTC** [ReVanced/revanced-patches#1153]
### Application

YouTube (com.google.android.youtube)

### Issue

Currently you can't change the language of your comment translator. YouTube says that it is based on "your watch history" and "personal preferences". Changing your location and language(in both yt and google account) doesn't help. The only "solution" I found from [here](https://support.google.com/youtube/thread/125811020/how-to-change-google-translate-language-translation-is-given-to-korean-language-but-i-wanna-change?hl=en) recommends to delete your watch history which is some cases not a perfect one. Also you can't configure which language should be ignored. For example, if you see a comment in your native language, you don't want to see annoying message "Translate into English".

### Patch

1. I guess it's technically possible to spoof the language that is used to translate comments. It's probably uses some google translator api. If youtube actually prevents from spoofing language, we can try to use some 3rd party translator(e.g. LibreTranslate), which will be less accurate, but still better than nothing. 
2. Ignore list of known languages should be also pretty easy, if youtube sends the language of a comment to a client.

### Motivation

Google seems not to care about this issue.
A lot of people like this feature because it allows to reduce language barrier between members of a community. The fact that you can't configure this feature at all is pretty sad.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
