### ISSUE TITLE
feat(YouTube): Show subtitles / captions in PiP mode & tablet mini player

### ISSUE THREAD

**Issue by castdrian** [ReVanced/revanced-patches#1164]
### Application

YouTube

### Issue

YouTube subtitles aren't displayed in PiP mode/tablet miniplayer because they're some screen overlay that just gets disabled

### Patch

Ideally the captions would be visible in PiP mode and tablet miniplayer

### Motivation

It seems reasonable that captions shouldn't disappear, whilst you're watching something

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by ballo** [comment]
> Mpv shows subtitles in a good way in android for reference- ![Screenshot_20230416-095838_One UI Home](https://user-images.githubusercontent.com/81620727/232266684-5c93d584-4846-4fc3-8bfb-1a5639737ec5.png) ![Screenshot_20230416-095758_One UI Home](https://user-images.githubusercontent.com/81620727/232266689-ccb3d7b7-503a-4d37-b286-1699fa99da06.png) ![Screenshot_20230416-095838_One UI Home] I wanted to see this feature in youtube for a long time

Interesting. I wonder if MPV supports YouTube subs and if there is a way to select the video stream (resolution)
