### ISSUE TITLE
feat(YouTube): Setting to force original language audio.

### ISSUE THREAD

**Issue by neversleeping** [ReVanced/revanced-patches#1170]
### Application

YouTube ([com.google.android.youtube](https://play.google.com/store/apps/details?id=com.google.android.youtube))

### Issue

There is a rather new feature in YouTube: different sound languages. When you know multiple languages, it's usually better to watch a video in original one. But every time YouTube finds a translation to your native language, it will set it to default.

### Patch

I want a setting that forces original sound in a video, or, at least, selects a language to prioritise.

### Motivation

The most amount of videos have native English sound, and there is a huge amount of people, who's native language is not an English, but they know it good enough to watch a content in original variant.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
