### ISSUE TITLE
feat(Reddit): Open links Externally

### ISSUE THREAD

**Issue by WanderBoi** [ReVanced/revanced-patches#1180]
### Application

Reddit

### Issue

Links always open in the Chrome custom tabs and the feature has been removed some time ago for some reason 

### Patch

Bringing the option back, a toggle which will make any links open in the default browser, bypassing the Chrome custom tabs

### Motivation

I dont believe I'm the only one unhappy with the implementation reddit chose but I also heard enough "go use 3rd party" so to the developer's discretion, if it turns into too much of a hassle I'm not expecting it to come.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
