### ISSUE TITLE
feat(Instagram): Allow / Force opening links on external browser

### ISSUE THREAD

**Issue by stdedos** [ReVanced/revanced-patches#1190]
### Application

com.instagram.android

### Issue

I would like to Allow/Force opening links on external browser, instead of the Instagram browser.

### Patch

I would like to Allow/Force opening links on external browser, instead of the Instagram browser.

### Motivation

"Who knows" why Instagram decided that, despite all other applications doing it differently (i.e., allowing you use your own browser), to force you to only be able to navigate the web via their browser.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
  > https://github.com/revanced/revanced-patches/issues?q=is%3Aissue+instagram+browser
  > ![image](https://user-images.githubusercontent.com/133706/229884672-998e50c0-1957-43c3-a6a7-4e12c9f96d95.png)
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
