### ISSUE TITLE
feat(Spotify): Hide episodes & podcasts

### ISSUE THREAD

**Issue by seaque** [ReVanced/revanced-patches#1210]
### Application

Spotify (`com.spotify.music`)

### Issue

Getting rid of Spotify forcing users on using podcasts.

### Patch

Removing **Episodes for You** and **Your Shows** from the home feed.

### Motivation

Spotify should stick to being a music player only. Trying to force people to use podcasts and episodes while they don't have Hi-Fi even after 2 years after announcement shows they don't care about users. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
