### ISSUE TITLE
feat(YouTube): Add silent skip to skip silent part of YT video.

### ISSUE THREAD

**Issue by heartlog** [ReVanced/revanced-patches#1214]
### Application

YouTube

### Issue

It is available in [Newpipe](https://github.com/TeamNewPipe/NewPipe/).. And works smoothly... And also now in LibreTube.. 
This will skip the silent part of video where we waste a lot time wasting a lot of time..

### Patch

Add option to skip the silent part of video. This will reduce wastage of time..
You can use exoplayer skip silence. 

### Motivation

Skip silence is life saver, when you want to complete a lecture of hours and have less time. And comes handy when watching music. Already many people are using this in the Newpipe and LibreTube.

Newpipe is seems to rely on ExoPlayer for this feature... I am leaving [This ExoPlayer GitHub code](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/SilenceSkippingAudioProcessor.java) For reference...

[Newpipe skip silent discussion](https://github.com/TeamNewPipe/NewPipe/issues/9251)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
