### ISSUE TITLE
feat(X / Twitter): Unlock several client-side premium features

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches#123]
### Feature description

With the recent changes to Twitter's premium plans, there have been new client-side features for premium subscribers that might be unlocked with a patch. Below are the list of built-in client side premium features I'm talking about:
- Custom app icons
- Customize navigation
- Themes
- Undo post
- Video downloader
- Thread reader
- Background video playback

### Motivation

- Why should this feature be implemented?
  - These features are very useful
- What is the explicit use case?
  - For accessibility and customizability
- What makes this feature important?
  - It makes the app more usable
- What makes this feature important?
  - The features it gives to the users are valuable

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by TheShadowRunner** [comment]
Was about to make a new feature request for this.. +1, "Video Background Playback" is sorely missed.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
