### ISSUE TITLE
feat(Google Dialer): Call Recording Silence Call announcement

### ISSUE THREAD

**Issue by DraconicNEO** [ReVanced/revanced-patches#1233]
### Application

Phone By Google [package `com.google.android.dialer`](https://play.google.com/store/apps/details?id=com.google.android.dialer)

### Issue

When recording calls a loud call recording announcement is present and cannot be disabled, it occurs even in regions where it is legal to record your own calls and conversations without announcement. You used to be able to disable it though means other than patching but Google prevented that in an update.

### Patch

I'd like to see a patch which completely silences the call recording announcement and optionally enables call recording by default as the previous methods of enabling it aren't very stable.

### Motivation

People in first party call recording regions are legally allowed to and therefore should be able to record their calls without a loud automatic call recording announcement. It's especially important in cases where people might not want the other party to know a call is being recorded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
