### ISSUE TITLE
feat(patch): Niconico Patches like YouTube

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches#1245]
### Application

Niconico (jp.nicovideo.android)

### Issue

Important features like the ones from the YouTube patches are locked behind a paywall.

### Patch

Unlock/add features such as:
- Watch videos at high resolutions when it is crowded
- Hide video and banner ads
- Custom playback speeds
- Change duration of double tap seeking on videos
- Picture in Picure
- Audio playback in the background when the app is minimized
- Videos load faster than regular members
- Hide notice of premium subscription for normal users
- Resume playback from where you left off

### Motivation

I wanted an experience like the ones with the YouTube patches.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
