### ISSUE TITLE
feat(patch): hide ui controls in TikTok

### ISSUE THREAD

**Issue by mohammadhaseb45** [ReVanced/revanced-patches#1250]
### Application

Tiktok

### Issue

The bottom buttons in tiktok (home, share and profile) are causing burn in in Amoled displays and the tiktok app would look much cooler if there was only the video when clear mode is enabled

### Patch

If it possible to make the Clear mode on tiktok always enabled and also to make the bottom buttons be hidden also and to be left with only the videos to scroll through.

### Motivation

 the tiktok app would look much cooler if there was only the video when clear mode is enabled

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by mohammadhaseb45** [comment]
@oSumAtrIX thnx man that's exactly what I meant 😁

**Comment by mohammadhaseb45** [comment]
Why no open even looked at it 😕

**Comment by kelvinkad** [comment]
That's a very good idea. I thought the same thing and was about to open a new isue when I found this is already opened by mohammadhaseb45.
My description to contribute with this open issue:

A patch to enable "clear mode" permanently to all videos without it being automatically disabled in every next videos.
In addition, the clear mode could real clear the screen, removing all the status and navigation bar and icons keeping only the video in the screen. It would be good to amoled screens preventing burn in pixels because when we spend a lot of time in TikTok, these navigation buttons are always on, causing the burn in.

**Comment by oSumAtrIX** [comment]
#2742
