### ISSUE TITLE
feat(Twitter / X): Hide Twitter menu elements

### ISSUE THREAD

**Issue by sebm253** [ReVanced/revanced-patches#1265]
### Application

Twitter

### Issue

The patch should let users hide elements in the menu which can be accessed by tapping your avatar or by swiping to right. In theory, the patch could be extended to cover the "Professional Tools" section too, but I think that's out of scope and not so distracting since it's collapsed by default.

<details>
<summary>Click to see image</summary>

![image](https://user-images.githubusercontent.com/42180891/224571162-d0755d6d-8945-4f5b-a748-3040a21dcc77.png)
</details>

### Patch

Hiding each element should be optional. For example, if the user only wants to hide the "Twitter Blue" element, they don't have to also hide "Profile" or "Topics". There should be an option in the `options.toml` file - probably a comma-separated string so there don't have to be 5+ options.

### Motivation

I despise Twitter Blue and unnecessary menu elements that take space.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
