### ISSUE TITLE
feat(patch): video patch loading sliding your finger to advance

### ISSUE THREAD

**Issue by LAMBORGUINI** [ReVanced/revanced-patches#1269]
### Application

YouTube ReVanced

### Issue

bug fix when advancing the video by sliding your finger

### Patch

When I slide my finger to advance the video by 2-3 seconds, the video does not advance, it only advances 1 minute per minute, it does not advance seconds. in version 17 it worked perfectly to advance two seconds by sliding your finger

### Motivation

because there is an error

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
