### ISSUE TITLE
feat(patch): Integrate PocketTube for YouTube channel groups

### ISSUE THREAD

**Issue by SameenAhnaf** [ReVanced/revanced-patches#1297]
### Application

YouTube

### Issue

PocketTube is a browser extension for organizing subscription feed by channel groups. Signing up with google account will let you backup info for all channel groups.

### Patch

Integrate [PocketTube](https://pockettube.io/) with YouTube Revanced app for including this feature.

### Motivation

Having channel groups is a nice way to organize the entire feed. It removes the hassle of browsing a cluttered UI. Browsing videos become easier based on my choice and needs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
