### ISSUE TITLE
Pro version or just hide ads for MX Player

### ISSUE THREAD

**Issue by xDARKxDEVILx** [ReVanced/revanced-patches#1308]
### Application

MX Player

### Issue

I love using MX Player and I have been using it for years and it is one of the most famous players ever, but lately the ads have became super disruptive and annoying, and I wish that this app gets patched for removing ads as I don't want to switch to any other app

### Patch

Just the pro version or the removel of ads , even if you can't remove all of them any thing would be appreciated 

### Motivation

MX Player is one of the most famous players with over a billion downloads so surly a lot of people would benefit from such patch 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
