### ISSUE TITLE
feat(YouTube Music): "Don't Play Music Videos" option

### ISSUE THREAD

**Issue by NarrikSynthfox** [ReVanced/revanced-patches#1353]
### Application

Youtube Music

### Issue

For premium users, theres an option that makes it so that it doesn't play the music video version of songs when only playing audio. If it's possible to allow that to be used tor non-premium users, that would be great. Some songs, the music videos have long intros or sfx over the music that isn't in the streaming upload of the song.

### Patch

Show the option for "Don't play music videos" (I think thats what it's labeled as) for all users.

### Motivation

I have seen a lot of people requesting SponsorBlock for Youtube Music, and most of the reasons why would be solved with this patch. Hopefully its possible to accomplish.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
