### ISSUE TITLE
feat(patch): Allow captions to be moved by dragging

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [ReVanced/revanced-patches#1383]
### Application

Youtube

### Issue

Sometimes the captions cover some important part of the video. On PC it is possible to drag the captions to anywhere on the video. It would be nice to do that on the android.

### Patch

Make it possible to move caption location by dragging. Alternatively provide some setting to change caption location to a few preset positions like top, bottom, center etc.

### Motivation

It allows one to watch the video without captions covering important details of video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
