### ISSUE TITLE
feat(youtube): ability to set video playback speed for shorts

### ISSUE THREAD

**Issue by D3SOX** [ReVanced/revanced-patches#1387]
### Application

YouTube

### Issue

There is no way to set the playback speed on the shorts tab

### Patch

Some ideas how I'd like to see it being implemented:
- An entry in the tripple dot menu on the top right to change the playback speed, just like in the normal player
- It should persist between videos for that session (or configurable)

Nice to have:
- A prefered shorts playback speed option
- A button to quickly switch between 1x and the prefered speed

### Motivation

I watch nearly everything in 2x and want that feature for shorts too. I think there are other people with that habit too who would consider this a useful addition.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
