### ISSUE TITLE
feat: (Tumblr) Remove 1-click follow links from dashboard

### ISSUE THREAD

**Issue by Sudrien** [ReVanced/revanced-patches#139]
### Feature description

Posts (and replies) from unfollwed users have a "Follow" link. It's position is variable based on username lengths & reblog status, so it's very easy to tap accidentally.

![Screenshot from 2023-11-05 13-37-30](https://github.com/ReVanced/revanced-patches/assets/24167/aa4a84b9-bfef-4181-be85-d8595ccc95a5)

Patch would either remove this link, or change behavior to "Follow User? Ok/Cancel" confirmation.

### Motivation

I keep find myself following people I had no intent to follow. This is bad for accessibility - link for a POST request equivalent.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
