### ISSUE TITLE
feat(YouTube): Disable Shorts double tap to like

### ISSUE THREAD

**Issue by MuhammetEminCakir** [ReVanced/revanced-patches#1409]
### Application

YouTube

### Issue

Sometimes you may accidentally like the video when trying to stop the video

### Patch

Disable or block double click like when watching short videos

### Motivation

When you watch a short video, double-clicking it can cause a like. Double-clicking like feature is not very necessary as there is already a like button.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by CompuGenius** [comment]
Are there any updates on this?

**Comment by CompuGenius** [comment]
> Accidental double taps don't seem realistic to me. If you do non the less, you can click the like button to unlike again.

It ABSOLUTELY happens sometimes, especially when trying to pause a video. I have my like and dislike buttons hidden because I don't like or dislike videos, so clicking the like button isn't an option. I need to go to Library, scroll to My Liked Videos, open it, click the three dots by the video, and click Remove. Would love to have a feature that allows us to disable double-clicking.

**Comment by oSumAtrIX** [comment]
> sometimes

Sometimes is not enough, especially if its barely sometimes. YouTube won't fall apart if you accidentally like a video therefore undoing rare accidental likes, especially in shorts is useless as the algorithm factors that very likely in.

**Comment by CompuGenius** [comment]
> > sometimes
> 
> Sometimes is not enough, especially if its barely sometimes. YouTube won't fall apart if you accidentally like a video therefore undoing rare accidental likes, especially in shorts is useless as the algorithm factors that very likely in.

I don't remember saying "barely". Also, who said anything about YouTube falling apart? 😂
Someone requested this feature, three people upvoted and I would also like it. Clearly there's want. I understand that you're not under any obligation to do it, but saying because you don't understand it is the reason you're not going to do it is a bit strange.

**Comment by oSumAtrIX** [comment]
> I don't remember saying "barely"

What you say doesn't change that it is barely. If you have a personal problem, you can look into finding a solution yourself.

> Also, who said anything about YouTube falling apart? 

I did to clarify why this is a non-issue.

You had your chance to provide proper motivation and burned it.
