### ISSUE TITLE
feat(patch): Add 'Save to watch later' in notification new videos

### ISSUE THREAD

**Issue by l2eused** [ReVanced/revanced-patches#1414]
### Application

YT Revanced

### Issue

Allow users to save watch later (or playlists) without clicking to view videos

### Patch

Add Option button in 3-bar menu to save videos in their watch later/playlists.
![IMG_20230123_021042](https://user-images.githubusercontent.com/94383254/213935471-f7b6667d-d821-432e-84f5-75e66b71c278.jpg)

### Motivation

You can save video to watch later/playlists by one-click and no need to viewing that videos

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
