### ISSUE TITLE
feat: Add option to subscribe without google account.

### ISSUE THREAD

**Issue by W1zardK1ng** [ReVanced/revanced-patches#1419]
### Type

Functionality

### Issue

For now to subscribe to any channel we need to use a google account. This is an issue and forces to have a google account to get this feature.

### Feature

Im a long term new-pipe user and i do not have a google account, recently moved to revanced project and its awesome.
the major problem is, i do not have a google account and i do not want to create one. It will be nice to have an integration to subscribe channels without the google account, using the RSS method just like the newpipe, libretube and other apps uses.

### Motivation

Providing subscription without google account will completely eliminate the use of a google id unless someone want to comment and react on videos but still able to track the subscriptions and watch contents easily.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
