### ISSUE TITLE
feat(patch): Black Theme for Cast Pop-up Panel in YouTube Music

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-patches#1423]
### Application

YouTube Music

### Issue

As the title suggests, the cast option in YouTube Music is grey in colour while the entire other UI element is amoled black. A patch to make this theming uniform would be nice.

### Patch

An option or just making it black by default or a theme option in YouTube music.

### Motivation

The same way as everything is black, this would further improve upon that purpose if implemented.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is what it looks like:

![Screenshot_2023-01-03-10-35-02-84_801c3494cc30bc6d615367769f98046d](https://user-images.githubusercontent.com/13122796/210331694-b62f82f8-cf1e-44f9-85a0-d3a5f745fd1f.jpg)

**Comment by ILoveOpenSourceAppications** [comment]
![210235465-47cc678e-70f6-4d20-8593-a1cb6e201a91](https://user-images.githubusercontent.com/117499019/210375135-87b3a4e7-d832-495a-8118-2c87ef49269a.png)
This is how it looks like now. Sorry if the way I typed seemed different to you. Since most UI elements in YouTube music is black, it would be nice to have this also in black

**Comment by ILoveOpenSourceAppications** [comment]
Is this something that is doable or is it not possible @oSumAtrIX (
