### ISSUE TITLE
feat(YouTube): Always show video preload buffer bar

### ISSUE THREAD

**Issue by severtheskyline** [ReVanced/revanced-patches#1452]
### Application

YouTube

### Issue

The buffer segment on the video player is now hidden behind a tap on the video player to show "advanced" information, and the bar is hidden now, when before was always shown. 
![Screenshots_2023-01-12-22-01-00](https://user-images.githubusercontent.com/79670265/212235160-5691b67c-2006-4d66-8d1b-3c284567dde6.png)
![Screenshots_2023-01-12-22-09-07](https://user-images.githubusercontent.com/79670265/212235253-01493a80-9265-4957-bd08-94f9bf5f84aa.png)

### Patch

The patch would simply show the buffer bar alongside the progress bar, as it was before the update. 

### Motivation

It's nice to know how much of the video is loaded, and frankly, no one had a problem with that feature, just youtube simplyfing already simple things. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#1151 can be clubbed together with this issue right?

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
