### ISSUE TITLE
feat(patch): Reddit patch to remove subscribe subreddit updates.

### ISSUE THREAD

**Issue by aDifferentBook** [ReVanced/revanced-patches#1460]
### Application

Reddit (com.reddit.frontpage)

### Issue

Reddit shows this pop-up if you visit a subreddit offenly and there is no way to disable it. It shows `Get the best of r/subreddit` to get updates from that perticular subreddit.

![IMG_20230109_223807_521.jpg](https://user-images.githubusercontent.com/80353171/211366941-325c939a-b422-44ee-9e0d-24e1eecfe148.jpg)

### Patch

Disable the pop-up permanently.

### Motivation

It's too annoying for all the app user to see it whenever you open a subreddit and needs to click on `Not now` option everytime, also there is no option in settings to disable it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
