### ISSUE TITLE
feat(youtube): different playback rate for youtube music videos

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#1464]
### Application

Youtube

### Issue

People don't often play music videos or listen to music with the same playback speed as other videos

### Patch

Use a different entry for youtube videos with type music. This in theory can be detected as sponsorblock has a special music type.

### Motivation

It's very annoying to change the playback rate for music videos, which takes a couple seconds and I have to go back to the start and re-watch it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
> This would only address some videos because there are a lot of "music" videos like dance videos that aren't categorized as music. It's probably better to implement this as #977 instead.

It might not be appropriate to mark the whole channel, as there are also a number of channels with mixed contents. For example, [vtuber channels](https://youtube.com/@HoshimachiSuisei) often contain not only music type, but also gaming, live stream (replays), etc. There are also [anime related channels](https://youtube.com/@anime_oshinoko) that post non-music contents but still has [a couple of music (type) videos](https://youtube.com/playlist?list=PLf1diALdg09hQkOdw1LR314ar0V4ZkbQk)

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
