### ISSUE TITLE
feat(patch): patch tournesol app

### ISSUE THREAD

**Issue by moolight-seashell** [ReVanced/revanced-patches#1465]
### Application

youtube

### Issue

everyone knows that the suggestion algorithm of YouTube is very bad, from the oppacity of these algorithms to the propagation of false information through the recommendation of poor quality videos
Feature

looking for this problem the mathematician Lé of the science4all channel has proposed a transparent answer to this problem

### Patch

this is why yhere is the platform tournesol app
https://addons.mozilla.org/fr/firefox/addon/tournesol-extension
https://github.com/tournesol-app/tournesol
https://tournesol.app/recommendations?date=Month&language=en

the objective is to allow the Internet users to vote to determine and to emphasize the video judged of public utility

I think that this platform would deserve much more visibility and I think that an integration in revanced would be ideal for that, even if, given its nature, its integration will probably be a difficult task.
If it were possible to simply start a discussion between the two teams it would be a big step forward to me

https://www.youtube.com/watch?v=HTzEkz8sFEE
https://www.youtube.com/watch?v=fe9u6YQTsWY

### Motivation

propose a solution to the worrying problem of the opacity of recommendation algorithms and limit the propagation of fake news

hmm i have never posted something like that here ? strange

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
