### ISSUE TITLE
feat(patch): Add File Manager + support

### ISSUE THREAD

**Issue by m-obeid** [ReVanced/revanced-patches#1475]
### Application

File Manager + (com.alphainventor.filemanager)

### Issue

It is not available yet.

### Patch

Enable dark mode without premium. Also maintain the Cloud storage functionality which is currently tripped in other mod versions.

### Motivation

Mods do exist already, but they seem pretty sketchy, and i just cant stand using the light mode. And again, it wont let me use google drive anymore then!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
