### ISSUE TITLE
feat(patch): Prevent Twitter auto refresh newsfeed

### ISSUE THREAD

**Issue by Accelerator-OW** [ReVanced/revanced-patches#1495]
### Application

Twitter

### Issue

Stop Twitter auto refresh the newsfeed after a short period of time.

### Patch

If using Twitter for a while, or keep switching between recent apps, it will auto refresh the news feed. Which is very hard to track posts.

### Motivation

This problem existed for long time ago and seems like Twitter dev won't do anything about it. A lot of people also getting annoyed with it, too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
