### ISSUE TITLE
feat(patch): Twitter verification badge differential b/w actually/blue verified account 

### ISSUE THREAD

**Issue by meetpateltech** [ReVanced/revanced-patches#1497]
### Application

Twitter

### Issue

differentiation between actually verified and twitter blue subscribed verified accounts!

### Patch

it can be confusing to distinguish between a regular verified account and a blue verified account. We think it would be helpful to add a feature patch that allows for differentiation between the two, such as using different symbols or colors. This would make it easier for users to identify which accounts are actual verified and which are not. Please consider adding this patch in a future update!

### Motivation

This feature are already available in twitter web with the chrome extension but till now not a single third party apps for twitter provide this feature! And many users want to this patch in twitter app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
