### ISSUE TITLE
Bypass Premium check for already downloaded music

### ISSUE THREAD

**Issue by flleeppyy** [ReVanced/revanced-patches#1503]
### Application

YouTube Music

### Issue

Being unable to play downloaded music without Premium, or if you have premium, being unable to play some downloaded music because its "Unavailable" 

### Patch

The patch should trip a premium check when browsing through local downloads, as well as bypassing logic to check if a video/song is still available, so you can still play downloaded music regardless of if the song is available or not. 

### Motivation

It would be useful for those who have downloaded music that they can't play any more but are still downloaded, and it would allow you to play music you've downloaded before if you had premium then, but don't have it now. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
