### ISSUE TITLE
feat(TikTok): Allow any keyword in content filter

### ISSUE THREAD

**Issue by tacohitbox** [ReVanced/revanced-patches#1535]
### Application

It's for both versions of TikTok on the Google Play store.

### Issue

It'd remove the blacklist of hashtags and words used to filter out things in your feed, for example, sponsored TikToks. 

### Patch

Essentially, it'd just prevent [this](https://files.gay/f/LqPLF/raw) from happening.

If it's done on the frontend, you could simply remove the blacklist.
If it's done on the backend, you could probably make your own filter or add it in addition to the ad/livestream filter.

### Motivation

I feel like it'd enhance people's experience browsing the app, acting as a way to get rid of sponsored TikTok's in the feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
