### ISSUE TITLE
feat(YouTube): Display full title of videos

### ISSUE THREAD

**Issue by indrastorms** [ReVanced/revanced-patches#1537]
### Application

YouTube

### Issue

When the video title is long enough it ends with "..."
![Screenshot_20221223-211132_YouTube_ReVanced](https://user-images.githubusercontent.com/48489074/209362363-c939cdd0-6c6d-4f60-b578-e12b17723153.png)

### Patch

To show full video title

### Motivation

Personal preference maybe !

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by Bubser** [comment]
I would absolutely love this feature as well. On PC you can hover the title with your mouse to see the full title, but on phone you have to open the video. I actually have a firefox addon on my PC which shows full titles and it's amazing QoL.
