### ISSUE TITLE
feat(YouTube): Move the search bar and notification button region to the bottom of the screen

### ISSUE THREAD

**Issue by 32423d** [ReVanced/revanced-patches#1545]
### Application

Youtube Revanced

### Issue

Currently the search bar and notification button region are hard to reach for users using Youtube Revanced in a portrait screen orientation on devices that have a larger aspect ratio than 16:9.

### Patch

An option in the app settings to move the region that contains the search bar and the notification button to the bottom of the screen. If the option was to be enabled it would move the region that contains the search bar and the notifications button to the bottom of the screen above the "Home", "Subscriptions", and "Library" button. 

Photo demonstrating how feature would work if it was enabled (if the option was to be enabled it would move the region circled in blue to the bottom of the screen where it is circled in red):
![image](https://user-images.githubusercontent.com/95009201/209027251-0982c79e-14a0-4cc1-abb6-472f86bdce83.png)

### Motivation

Quality of life changes. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
