### ISSUE TITLE
feat(Guilded): Enable sharable media links for uploaded media

### ISSUE THREAD

**Issue by CloudRealm** [ReVanced/revanced-patches#1553]
### Application

[Guilded](https://play.google.com/store/apps/details?id=com.gg.guilded)

### Issue

Every time I want to share an image/video on guilded it does not let me copy the url link to it, it only lets me copy the message link.

### Patch

Enable link copying for uploaded media, instead of copying the guilded message link. Like discord how lets you use the share menu to share media.

### Motivation

It would make the app far more usable and allow for easier sharing of uploaded media to other people,platforms and apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
