### ISSUE TITLE
feat(YouTube Music): Zen Mode (Discontinued YouTube Music Vanced feature)

### ISSUE THREAD

**Issue by KarmaBeast** [ReVanced/revanced-patches#1577]
### Issue

Protect eyes with Zen Mode (Grey background when playing videos or videomode in YouTube Music)

### Patch

"Zen Mode" was a feature developed by the discontinued Vanced team for YouTube Music Vanced. I don't know the exact English translation of this feature since I had installed the German language of YouTube Music Vanced.

When you play a video or videoversion of a song it makes the background grey to protect eyes (instead of black)

See attached screenshots & videoclip:

![Screenshot_20221217-221050817 (1)](https://user-images.githubusercontent.com/73917917/208269212-6a746a24-79d7-4b3b-ba43-0c3ed3dc67eb.png)

![Screenshot_20221218-000708217](https://user-images.githubusercontent.com/73917917/208269213-cd805654-6806-4baf-8739-2eb0b39673dd.png)

Screen recording: https://streamable.com/qbqgl4

### Motivation

It's useful and protects the eyes against eyestrain. Makes using YTM more comfortable.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
