### ISSUE TITLE
feat(Google Messages): Amoled black for dark theme

### ISSUE THREAD

**Issue by Toiletmason** [ReVanced/revanced-patches#1582]
# **Application**

Google Messages 

# **Issue**

Google messages dark theme is pretty ugly and could use a amoled face-lift. 

# **Patch**

Make the dark theme of the app Amoled #000000 black, and possibly tweak some of the blues for better aestetics.

# **Motivation**

Google Messages is the only way alot of us are going to be able to get rcs unfortunately. The app is pretty awful to look at in dark mode and this could alleviate that.

# **Acknowledgements**

 I have searched the existing issues and this is a new and no duplicate or related to another open issue.

I have written a short but informative title.

 I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
