### ISSUE TITLE
feat(Google News): Disable in-app browser

### ISSUE THREAD

**Issue by gotham8x** [ReVanced/revanced-patches#1585]
### Application

Google News

### Issue

There is no way to disable in-app browser on Google News. It defaults to open news in embed browser which is not best experience. Users have to take couple steps on each news to open in users' default browser.

### Patch

Disable default in-app browser.

### Motivation

Bringing best user experience for users.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
