### ISSUE TITLE
feat(Netflix): Trakt.tv scrobbling

### ISSUE THREAD

**Issue by antifarben** [ReVanced/revanced-patches#1592]
### Application

Netflix

### Issue

It would be perfect if it'd be possible to scrobble watched Netflix content to trakt.tv

### Patch

It would need a possibility to authenticate with a trakt account.
Then the states (finished/in progress) should be [synced to the trakt API](https://trakt.docs.apiary.io/#reference/scrobble).

**PS:** It seems that [trakt currently has some issues](https://status.trakt.tv/) though.

### Motivation

The native Netflix app doesn't support this. Only apps like KODI or inofficial browser extensions do.

ReVanced could improve this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
