### ISSUE TITLE
feat(TikTok): Disable in app browser / Open links in external browser

### ISSUE THREAD

**Issue by 2latemc** [ReVanced/revanced-patches#1594]
### Application

TikTok

### Issue

TikTok opens every link in a stupid in App browser, there is no way to disable this or copy the link or something

### Patch

Disable this Feature completely and just open links in the standard browser

### Motivation

I think (might be wrong) this isn't reay complicated. I would have tried coding it myself, however I failed. This would be such a useful thing tonhave

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
