### ISSUE TITLE
feat(Google Feed): Hide ads

### ISSUE THREAD

**Issue by AshwinKO** [ReVanced/revanced-patches#1598]
### Application

Google Android APP

### Issue

is there any way we can revance the google app available on android it shows too many ads and lots of data collection an adblocking  feature which blocks ads in google feed plus search results would be really nice

### Patch

adblocking and data collection blocking, trackers blocking support in google app for android

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
