### ISSUE TITLE
feat(Tumblr): Save videos to device

### ISSUE THREAD

**Issue by SubZero5** [ReVanced/revanced-patches#162]
### Feature description

While browsing Tumblr posts, one may long press on an image and select save image. But there is no save option for video content. Please implement a save video option to the menu. This option might also be added to the three dots menu. 

### Motivation

I mean the images can easily be saved but the videos are not. It would be great if one could save the video with no hassles. 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by SubZero5** [comment]
May I Re-request this feature?
