### ISSUE TITLE
feat(YouTube): Full height save to playlist dialog

### ISSUE THREAD

**Issue by KraXen72** [ReVanced/revanced-patches#1640]
### Application

YouTube

### Issue

currently, the save to playlist dialog only occupies half the screen at best, which is not efficient. 

### Patch

the dialog should expand itself towards the top when you start scrolling, so you can see more of your playlists at the same time (same behaviour as Vanced)

### Motivation

see Issue.
it makes it a lot easier to select a playlist to save video to, when you have the whole screen showing a list of your playlists, rather than just 1/2 of the screen

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
