### ISSUE TITLE
feat(YouTube): Remove badges from subscriptions button on the navigation bar and from notification bell icon

### ISSUE THREAD

**Issue by d3EyedRaven** [ReVanced/revanced-patches#1647]
### Application

 YouTube

### Issue

The badges of subscription button and notification bell are ALWAYS there in today's world where everyone who uses youtube regulary has at least ten channels subscribed to. So these serve no purpose, and should be removed.

### Patch

The patch should be in Settings > ReVanced > layout > Hide badges

and it should remove the badges of subscription  (red dot) on the navigation bar and from the notification bell icon on the upper side (number)

### Motivation

Removing the badges would result clean minimalist view to home tab.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
