### ISSUE TITLE
feat(Twitter / X): Remove Spaces button/functionality

### ISSUE THREAD

**Issue by pixiekat** [ReVanced/revanced-patches#1652]
### Application

Twitter

### Issue

I'm not sure if this is possible but it would be nice to remove the Spaces button (or function) to make room in the bottom toolbar. 

### Patch

Ideally I'd like to see the middle Spaces button removed in the bottom toolbar and maybe move the "+"  floating menu into it's place. The spaces circle inside the "+" floating menu to create a new space would be removed too. 

### Motivation

Spaces, I feel, are very similar to Youtube Shorts, which take away from what the app is supposed to be and end up just taking up space. It would be nice to have the option to not see it at all if someone never uses the feature. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
