### ISSUE TITLE
feat(patch): Universal Patch: change package name

### ISSUE THREAD

**Issue by sjiawjbssj** [revanced/revanced-patches#1662]
### Application

Universal Patch

### Issue

I'd like to install some Apps multiple times.

### Patch

Change the package name of any App so that it can be installed multiple times.

### Motivation

It would be an easy way to install duplicate apps on any rom.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Linus789** [comment]
I think this issue still holds some value. If you want to do this via "cloning", you have to uninstall the original app first, patch the original apk and install it, clone it, uninstall the patched app (not the clone) and at last re-install the original app and set it up again (because all the data is lost after the uninstall of the original app).

Just changing the package name while patching seems a lot easier than that, because you don’t have to uninstall the original app.
