### ISSUE TITLE
feat(SnapTube): Hide ads

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-patches#1702]
### Application

Snaptube

### Issue

Removing Snaptube ads.

https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.snaptubeapp.com/&ved=2ahUKEwi886eur8z7AhUOqIsKHWVmA5IQFnoECAgQAQ&usg=AOvVaw1sQFpcFwVJh6GVtlGhI-0C

### Patch

Get rid of Snaptube ads.

### Motivation

Snaptube is used to download videos and photos from Instagram, YouTube, etc.The app contains a lot of ads.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
