### ISSUE TITLE
feat(YouTube): Add save to library, playlist, download buttons to the Shorts player

### ISSUE THREAD

**Issue by A-74** [ReVanced/revanced-patches#1718]
### Application

Youtube 

### Issue

When using youtube shorts you can't save to library or a Playlist or download that video(even in normal youtube)

### Patch

Adding save to library, add to Playlist and download (via powertube or newpile) buttons to youtube shorts screen (left side upper is good with rest of the buttons)

### Motivation

To download and save videos in youtube shorts to library quickly!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
