### ISSUE TITLE
feat(Streamio): Downloads patch

### ISSUE THREAD

**Issue by Kissasdx** [ReVanced/revanced-patches#1729]
### Application

com.Streamio.one

### Issue

The app does not support downloading movies and series from the menu , you have to go to each movie or series episode one by one and open with browser to download.

### Patch

It would be usefull to be able to download right from the menu(for each episode/movie/song or season/playlist ) ,the problem seems to be because streamio is torrent based you have many feeds you can use to download , so it would also be usefull to have settings for preferred quality and torrent privider. It could use either newpipe or advanced download manager as download provider. 

### Motivation

Because i believe it would be a key feature for those who use streamio and it's features.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
