### ISSUE TITLE
Limit Distraction

### ISSUE THREAD

**Issue by Maha-Rajan** [ReVanced/revanced-patches#1734]
### Application

YouTube 

### Issue

Right now when you are viewing a video on YouTube there is an option to hide comments which reduces the distraction. It would be nice to also remove video suggestions below the player to limit distractions.

### Patch

Right now when you are viewing a video on YouTube there is an option to hide comments which reduces the distraction. It would be nice to also remove video suggestions below the player to limit distractions.

### Motivation

Helps in reducing unwanted interaction and reduces destruction from the video you are currently watching 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DidierLoiseau** [comment]
Hey @Maha-Rajan, did you find a solution using a custom filter? I tried checking with logcat but I don’t find anything that does not also hide the thumbnails/videos from the subscription page.

@oSumAtrIX, in #981 someone suggested `search_video,related_video` and you said not to do that because it strains the API. Even that does not seem to work any more (and I don’t see those in logcat), but with the infinite scroll, is it even feasible to implement a solution using filters that wouldn’t also strain the API?

If not, could this issue be reopened?

**Comment by oSumAtrIX** [comment]
No and create a new updated issue
