### ISSUE TITLE
feat(Twitch): Playback speed changer

### ISSUE THREAD

**Issue by zieAnarbeast** [ReVanced/revanced-patches#1741]
### Application

Twitch

### Issue

Cant change playback speed

### Patch

Add an option to change playback speed on vods on twitch

### Motivation

Its a feature that exists on the site and is veey usefull to safe alot of time.
I mainly watch vods because of time zones and sleeping during the times my favorite streamers are live so i catch up on vods when i can and im sure many people have the same issue and would benefit from the ability to change the playback speed like on every other video platform even on mobile because you are not always at your pc when you watch content 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
