### ISSUE TITLE
feat(YouTube): Change video aspect ratio

### ISSUE THREAD

**Issue by Dark000Soldier** [ReVanced/revanced-patches#1760]
### Application

Revanced Youtube

### Issue

Many uploaded videos have wrong aspect ratio!

### Patch

 A small icon in the player to change the aspect ratio of a video like between 4:3 / 16:10 / 16:9 etc….
There is a chrome extension for that but no YouTube patch for that yet.

### Motivation

On YouTube there are many videos with wrong aspect ratio, such as the old videos 4:3 been uploaded as 16:9 which makes the video so bad and everything on the screen looks so overstretched!
Similar function exist in 99% of video players but YouTub doesn’t have it for whatever reason!

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
