### ISSUE TITLE
feat(TikTok): Local favorite videos & following list

### ISSUE THREAD

**Issue by powerfulsaber** [ReVanced/revanced-patches#1764]
### Application

TikTok.

### Issue

Without an account, a user is not able to follow creators or favorite videos.

### Patch

Allow the user to follow creators and favorite videos without an account (similarly to [NewPipe](https://github.com/TeamNewPipe/NewPipe)). This data would be stored locally rather than on an account.

I'd suggest implementing an export/import feature of this, so it wouldn't be lost when transferring over devices.

### Motivation

TikTok makes it difficult to create an account when taking privacy precautions, such as using a VPN. There's already a patch made to disable the force login prompt, so this is a simply a step further in making it closer to the normal TikTok viewing experience.

This is also beneficial privacy-wise, as your data won't be tied to an account. 

Partially inspired by NewPipe.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
