### ISSUE TITLE
feat(Twitter / X): change Twitter blue users icon 

### ISSUE THREAD

**Issue by castdrian** [ReVanced/revanced-patches#1769]
### Application

Twitter

### Issue

Essentially replicate what this repo does for chromium https://github.com/wesbos/who-blue

### Patch

Pretty much a replica of the extension or something in that area

### Motivation

Elon Musk is a twat and we all love to spite him

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
