### ISSUE TITLE
feat(Spotify): Premium like features

### ISSUE THREAD

**Issue by GioPan04** [ReVanced/revanced-patches#1774]
### Application

Spotify (`com.spotify.music`)

### Issue

See patch section

### Patch

- Play any songs, currently you can search songs but only play playlists and you can't choose a song in them.
- Songs in playlist can only be played in shuffle
- Remove audio ads
- Unlimited songs skips

### Motivation

Spotify is a big app, used by many. Currently there aren't any good alternatives for android. There are some patched version online but they are all closed source as much as I know, having an open source ones could be a great thing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
