### ISSUE TITLE
feat(TikTok): Hide "TikTok Now" post prompt

### ISSUE THREAD

**Issue by MarkPinto** [ReVanced/revanced-patches#1776]
### Application

Tiktok

### Issue

This issue would patch out the prompt urging users to post to tiktok live, please refer to screenshot of prompt in feed

![Screenshot_20221109-114700](https://user-images.githubusercontent.com/17538608/200890835-7eefed8b-a218-437e-8cb4-2d62d568885d.png)

### Patch

The patch I'd like to see would remove it from the feed so that content consumption isn't interrupted by a silly prompt

### Motivation

It's the equivalent to an ad, its unnecessary and not content that user's want to see. If users want to make content for TikTok Now then they can do it without being nagged.

I would understand if TikTok only nagged user's once but it's not a one time thing

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
