### ISSUE TITLE
feat(YouTube): Modify channel name, photo, banner

### ISSUE THREAD

**Issue by The-Grace-God** [ReVanced/revanced-patches#1788]
### Application

Youtube

### Issue

None (so far) just a patch for fun

### Patch

Allows you to locally modify a channels name, picture and banner

### Motivation

Because it a plugin that allows people to customize channels and YouTube to their liking could be used for memeing stylization or reverting the channel back to a old look

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
