### ISSUE TITLE
feat(YouTube Kids): Hide ads

### ISSUE THREAD

**Issue by Koognod** [ReVanced/revanced-patches#1789]
### Application

yt kids

### Issue

ads between video playback in app.

### Patch

ads skipped or not displayed in yt kids

### Motivation

young children shouldn't be forced to watch ads for things they don't even understand or know exist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by Julmik647** [comment]
You try can using some adblocking extension in web browser and going to [https://www.youtubekids.com/](https://www.youtubekids.com/). I would recommend [Ublock Origin](https://ublockorigin.com/). On mobile you can use browser with support for extensions like [Firefox](https://www.mozilla.org/pl/firefox/browsers/mobile/), [Edge](https://www.microsoft.com/pl-pl/edge/download?form=MA13FJ) or [Kiwi browser](https://github.com/kiwibrowser/src) on Android or browsers with built-in Adblocker like [Opera](https://www.opera.com/pl/download) or [Brave](https://brave.com/pl/download/) on both Android and ios.

**Comment by oSumAtrIX** [comment]
A VPN can be used.
