### ISSUE TITLE
feat(YouTube): Toggle timestamp button in transcript 

### ISSUE THREAD

**Issue by KyleBroflowski** [ReVanced/revanced-patches#1799]
### Application

To disable timestamp displayed in transcripts 

### Issue

Resolves viewing the content without a timestamp to be able to copy them

### Patch

Add a toggle button named timestamp near the top of the transcript. This when off should show the timestamps and when off should hide the timestamps fully. 

### Motivation

Feature in desktop youtube  

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
