### ISSUE TITLE
feat: Prevent youtube auto-refreshing notification list

### ISSUE THREAD

**Issue by asgraf** [ReVanced/revanced-patches#183]
### Feature description

Notification list (accessible after clicking notification bell button in main menu) can be manually refreshed if user performs top over-scroll gesture
Around few years ago auto-refresh feature was introduced to the notification list.
Auto-refresh is triggered every time application looses focus (phone screen is turned off, someone calls or switched to another app)
I find this auto-refresh feature is very annoying

Please create patch that kills all auto-refresh triggers
Only manual refresh performed by top over-scroll gesture should be left

### Motivation

Whenever I have free time I go to the notification list then scroll down a few days back until I find the notification I finished on last time, then slowly scroll up visiting videos that look interesting. This strategy allows me not to miss any new video from the channels I subscribe to.

The problem is that every time youtube app looses focus (someone calls me or I let the phone screen go blank) the notification list refreshes taking me back to the top of the list which forces me to scroll down again until I find the notification I was on before the refresh occurred

Before the auto-refresh feature was introduced, as long as the app wasn't killed by Android's memory manager, returning to the notification list always landed me exactly where I left off

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
