### ISSUE TITLE
feat(YouTube): Higher volume

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#1836]
### Application

Youtube

### Issue

Some videos have very low volume, even if you turn the phone's speaker all the way up you cannot hear well

### Patch

A button next to the subtitle button, which have the following logic:

```
toggle-on() {
  // make the video have similar volume but with half
  // of the system volume, so the volume upper limit
  // can be doubled
  system-volume = floor(system-volume / 2)  // force integer
  amplify-video-volume-by-2x(true) // lower volume first 
}
toggle-off() {
  // reverse what toggle-on does, but check for volume > 15
  amplify-video-volume-by-2x(false)
  tmp = system-volume * 2
  if (tmp > 15) { tmp = 15 }
  system-volume = tmp
}
```
Or a setting item that you could change without restarting the app, no system-volume changing steps needed as this dont need to be toggled too often.

### Motivation

make videos with low volume easier to hear

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kairusds** [comment]
While a **stable volume** toggle was added as an option for the video player on the original version, it doesn't seem to work so this patch would be pretty helpful.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
