### ISSUE TITLE
feat(YouTube): Force landscape in fullscreen mode

### ISSUE THREAD

**Issue by castdrian** [ReVanced/revanced-patches#1840]
### Application

YouTube 

### Issue

On regular sized devices pressing the fullscreen button rotates the player to landscape to achieve full screen viewing. On big devices it just enter full screen mode in a desktop like way.

### Patch

It should simply force landscape mode when clicking the full screen button and keep the orientation locked

### Motivation

Landscape for fullscreen makes more sense than portrait unless it is a vertical video

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by assist726** [comment]
@oSumAtrIX Would happily pay a reasonable amount to get this feature implemented, wondering if you do accept paid requests?
