### ISSUE TITLE
feat(YouTube): Allow pinch to zoom in flex mode

### ISSUE THREAD

**Issue by castdrian** [ReVanced/revanced-patches#1843]
### Application

YouTube 

### Issue

YouTube currently does not allow pinch to zoom whilst in flex mode

### Patch

The patch should simply allow pinch to zoom whilst the app is in flex mode

### Motivation

It makes no sense not to be able to pinch to zoom whilst in flex mode

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
