### ISSUE TITLE
feat(Spotify): improved shuffle feature (non biased shuffle)

### ISSUE THREAD

**Issue by rbits0** [ReVanced/revanced-patches#1850]
### Application

Spotify

### Issue

Spotify's shuffle option currently uses an algorithm that favours some songs over others. There is no way to do a true shuffle in the Android Spotify app.

### Patch

Implement a true random/unbiased shuffle in Spotify. This has already been implemented in Spicetify for PC. Here are some links:
https://spicetify.app/docs/advanced-usage/extensions#shuffle
https://github.com/spicetify/spicetify-cli/blob/master/Extensions/shuffle%2B.js
It uses the Fisher-Yates algorithm to shuffle the songs.

### Motivation

There aren't many patches for Spotify right now. There doesn't seem to be anything else that has patches for Spotify, except xManager, which seems to be more focused on features for non-premium users, like removing ads and forced shuffle. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
