### ISSUE TITLE
feat(PleX): Remove 1 minute limit and allow downloads

### ISSUE THREAD

**Issue by zhilinli1** [ReVanced/revanced-patches#1851]
### Application

PleX

### Issue

To remove the 1 min limit. 
To add download without PleX pass. 

### Patch

I wish there is a way to download videos from a shared or self owned Plex server. It should also remove the Plex 1min limit on playing back medias on mobile. 

### Motivation

PleX is a extremely popular service to self host media and share with friends. Although free options like Jellyfin exist, the world predominantly uses PleX for this, due to its low hardware req. However, these artificial requirements made Plex's free tier hard to use. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
