### ISSUE TITLE
feat(YouTube): Remember "Videos only" setting in subscriptions feed

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-patches#1852]
### Application

YouTube

### Issue

Allows persisting hiding community posts from the subscriptions feed. Currently, the only solution is to use the hide community posts patch, which makes them inaccessible from anywhere, even manually going to a channel's community tab.

### Patch

Currently, there is an option in the subscriptions feed when you swipe to the end of the bar under the channels that has categories like "All", "Today", etc. that allows you to change between videos and posts, and videos only, however this setting is not saved and resets to videos and posts when the fragment is reloaded. This patch would involve saving the setting so that community posts can be permanently hidden from the subscription feed but not be completely inaccessible in the app.

### Motivation

This would provide a better option for people who just want to hide community posts from their subs feed but still would like to be able to access them from elsewhere, as currently you need to go into settings, toggle hide community posts, and restart the app every time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
