### ISSUE TITLE
feat(YouTube): Disable Video Title Auto-Translation

### ISSUE THREAD

**Issue by edcarlo157** [ReVanced/revanced-patches#1882]
### Application

Youtube ReVanced

### Issue

The translation usually is not good and can even make people ignore some videos they might enjoy thanks to the often bad and/or misleading translation, one of the current "solutions" is change the language and/or region of the device.

### Patch

A patch similar to the "Hide-Shorts", that would hopefully disable this non-optional "feature"

### Motivation

The translation that's apparently added by the uploader only translates the title/description, that might make it easier to possible new foreign viewers to find the content, won't matter that much since the video itself won't be translated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by SapuSeven** [comment]
Did someone look into this?
Is it actually possible to get the original title?

**Comment by D3SOX** [comment]
Sorry for the necro bump but the translation has gotten so aggressive now. It made browsing for videos so frustrating. Is there any possibility for this to be considered an open request again?

**Comment by Bubser** [comment]
I would love this as well if anyone finds the time/motivation to do it ❤️

**Comment by CraftingDragon007** [comment]
This is just annoying, I literally can't watch any videos that are in my native language when my phone's language is set to English. Maybe I'll implement it myself later, because it's just so annoying.
