### ISSUE TITLE
feat(YouTube): Different forward and backward seek time

### ISSUE THREAD

**Issue by amit-katyal** [ReVanced/revanced-patches#1890]
### Application

I would like to request this patch where user can set different values of time to forward and different for backward backward.

![Picsart_22-10-26_10-33-02-679](https://user-images.githubusercontent.com/89385446/197939620-75a5a58e-cfaa-4132-bb26-f20b8198fb75.jpg)

### Issue

Not trying to solve any major issue but this would be a good feature for a user like me, who sometimes skips through lecture videos. Like you can forward like 10 seconds and it you think you have skipped more than you wanted to, just skip back 5 seconds.

### Patch

This patch is about mapping double tap to seek backward and forward to different values. Like setting double tap to seek forward to 10 seconds and setting double tap to go backward to 5 seconds. Also these values to seek can be set by user as it suits.

### Motivation

Video payers on some websites have similar feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
