### ISSUE TITLE
feat(YouTube): Use default system share sheet over youtube default

### ISSUE THREAD

**Issue by skff-err** [ReVanced/revanced-patches#1896]
### Application

youtube revanced

### Issue

The youtube app uses it's own share sheet which is jarring to use when other Google apps like Photos and Maps have a way to access the default system share sheet, usually via the "more" button

moreover, the youtube's share sheet just absolutely sucks because it has no useful suggestions (like group chats or contacts) and just shows all shareable-to apps which makes it a hassle to find the app you want to share to when you have a million of them

### Patch

I'd like to see a patch involving the removal of the youtube share sheet and replace with a system default share sheet

I guess it could be like the branding patch where you had to apply it before patching but a toggle withing revanced's settings would be nice too

### Motivation

youtube share sheet killed my mother

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Aryan-Chauhan** [comment]
https://github.com/anddea/revanced-patches/issues/50

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
