### ISSUE TITLE
feat(Spotify): Quick access to enable / disable car mode

### ISSUE THREAD

**Issue by walti0** [ReVanced/revanced-patches#1904]
### Application

Spotify

### Issue

Using car mode when I want

### Patch

Add a button that turn on and off a car mode in spotify

### Motivation

I just want use car mode when  I'm doing something but I'm not in the car at that moment.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
