### ISSUE TITLE
feat(Metanav): Fix scaling

### ISSUE THREAD

**Issue by halotroop2288** [ReVanced/revanced-patches#1911]
### Application

[metaNav](https://play.google.com/store/apps/details?id=com.metanav)

### Issue

The app was made for an older version of Android, so it shows a warning on first startup that it might not work (but it does).
It doesn't have support for wider screens, so the content is off-center and doesn't fill the screen.
Text doesn't fit itself within bounds correctly but this might not be due to updates, simply bad design.

![metaNav screenshot](https://user-images.githubusercontent.com/30361266/197308965-a0dd56a7-4b2d-4a3b-879f-765cb30828d8.png)

### Patch

I'd like to see the app either stretch the background or center it to fit neatly into a wide phone for a start. The rest of the content should just be centered.

If possible, I'd like the warning message to go away as well.

### Motivation

I just think it would be neat, and would make a good starting point for other patches to the app.
@juztim suggested opening this issue rather than attempting it myself.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
