### ISSUE TITLE
feat(YouTube): Remove "continue playing?" dialog after the screen has turned off

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#1913]
### Application

Youtube

### Issue

When you use YT to play a playlist, it will stop itself.

1. Create a playlist with about 15 songs each with length not less than 3:40 
2. Play the playlist from start
3. Press the power button to turn off screen
4. Wait until no sound is playing. It should have played about 7 or so songs
5. Unlock and you can see the dialog at the bottom, asking you to interact before playing

As I did not use English version of YT, the exact wording might be different, I translated it back to English

BTW the dialog has a white background even when you used dark theme

### Patch

Remove the aforementioned dialog such that you dont need to click it to continue playing

### Motivation

This allows user to shut the screen off when listening to music. Which:

1. Saves battery
2. prevents screen burn-in on OLED device
3. lets you focus more when listening background music

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
