### ISSUE TITLE
feat(YouTube): Remove "You may see ads here" screen

### ISSUE THREAD

**Issue by Othmane-ElAlami** [ReVanced/revanced-patches#1927]
### Application

YouTube

### Issue

I activated YouTube Premium (for my Samsung TV) using a VPN because we don't have it here, but now I have this annoying message every time I open YouTube.

<img src="https://user-images.githubusercontent.com/111425505/196054873-c67dc02f-f79e-4257-b910-5404c8e71806.png" width="480">

### Patch

Disable / Remove this screen.

### Motivation

This will help anyone like me who don't have Premium in their country and have YouTube Premium.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
