### ISSUE TITLE
feat(YouTube): Hide buttons in the 'You' / Library tab

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-patches#1929]
### Application

YouTube ReVanced

### Issue

The existence of the following buttons on the "Library" tab can be inconvenient:
"Your videos"
"Downloaded"
"Your movies"
"Your clips"

I translate this text and the name of the buttons with the translator, there may be errors.
"Your clips" button appears for those who have created at least one clip and never disappears again, even if you delete clips.

### Patch

Add the ability to hide these buttons as an interface customization

### Motivation

These buttons are not needed by many users and just take up useful space on the screen where playlists could be displayed.
Actually, I'm making this report for my own sake - I encountered the appearance of the button "Your clips", which can not be removed (report to Google did not yield results). Therefore, all hope for modifications. Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
