### ISSUE TITLE
feat(YouTube): Ability to select a CDN server for downloading static content

### ISSUE THREAD

**Issue by LenaTDDS** [ReVanced/revanced-patches#1947]
### Application

YouTube

### Issue

This patch should solve the problem with loading static content (avatars, pictures in the "Community" tab)

### Patch

Add a setting that will allow you to choose a server from where to download static content (for example, an alternative CDN server from Google, or your own proxy server)

### Motivation

In Russia, because of the blocking by Roskomnadzor, https://yt3.ggpht.com was blocked. As a result, avatars from channels and images in the "Community" tab stopped loading for users living in Russia. This patch can help solve this problem, and it may also help enthusiasts

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
