### ISSUE TITLE
feat(Nvidia Shield / Google TV): Hide ads

### ISSUE THREAD

**Issue by IrealiTY** [ReVanced/revanced-patches#1967]
### Application

I think those are the related packages:

Google TV Home: com.google.android.apps.tv.launcherx
Google app for Android TV: com.google.android.katniss

### Issue

The Google TV Launcher was updated recently to display promoted / ad content in the top part of the home screen.
Here are 2 samples of before and after the update:

Before:
![image](https://user-images.githubusercontent.com/1223686/194751574-f1ea983d-3bea-4699-9dcb-725ba550f316.png)

After:
![image](https://user-images.githubusercontent.com/1223686/194751529-3f013930-ad32-49ec-b041-f08544f7396c.png)

### Patch

Remove ads from homescreen

### Motivation

It would help all the Nvidia Shield Users and Google TV (Like Sony) owners to remove Ads from the home screen after google force updated the launcher and only way around it is to use an alternative launcher that doesn't't support the "Play Next" options that integrate nicely with other apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by JimZiii** [comment]
@oSumAtrIX i totally get why it got rejected, but I'd just like your opinion on this.
The current fix to keep the old layout is to uninstall updates on android tv home (com.google.android.tvlauncher) and deactivate all automatic updates in the playstore since it's not possible to disable them individually on android tv

So I'm just wondering if it's even possible to somehow patch a system app so it's no longer possible the play store to update it, making it possible to activate auto-updates again??
Or is that impossible without root?

**Comment by JimZiii** [comment]
@LisoUseInAIKyrios he quoted the guidelines saying it can be accepted or rejected at their discretion, thats why i used the word rejected, and i just meant to say i understand why he closed it.
The point was to ask my semi-related question, not  to imply that its forbidden or anything like that

**Comment by oSumAtrIX** [comment]
@JimZiii to answer your question, yes
