### ISSUE TITLE
feat(Waze): General poi removal

### ISSUE THREAD

**Issue by Cliffmode2000** [ReVanced/revanced-patches#1993]
### Application

Waze. 

### Issue

Ads in navigation. Poi popups etc. 

### Patch

Just general ad interruptions.

### Motivation

Idk how many people use waze just thought I'd ask. I personally only use waze for voice packs, excellent direction and crowdsourced traffic. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
