### ISSUE TITLE
feat: (patch) Add Discord Integration [Youtube Music]

### ISSUE THREAD

**Issue by Vikachubro21** [ReVanced/revanced-patches#2]
### Application
Youtube Music

### Issue
Youtube Music has no current integration with discord.

### Patch
Add integration by creating a rich presence similar to the following image: (This was made for desktop, see https://github.com/XFG16/YouTubeDiscordPresence)
![image](https://github.com/ReVanced/revanced-patches/assets/57052932/86b428c2-736b-442f-87f1-b4acce50ecd3)
Listen along will be replaced with "Play on Youtube Music" (which will open a link to the given song)

### Motivation

Spotify has long had discord integration, but doesn't have the same song selection as Youtube Music (specifically in terms of remixes). A discord integration similar to Spotify's would allow Youtube Music users to have the same functionality.

The benefits: Users of Revanced Youtube Music can more easily show their music off similar to spotify.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
