### ISSUE TITLE
bug: Subtitles placed incorrectly on the top of the video

### ISSUE THREAD

**Issue by Domiiniik** [revanced/revanced-patches#2003]
### Type

Cosmetic

### Bug description

Subtitles in reVanced are placed on top of the video instead of at the bottom as they should.
Link to the video: https://youtu.be/HTnQRV_L32c
ReVanced
![Screenshot_20230428_063027_YouTube](https://user-images.githubusercontent.com/30195961/235055624-2bfcb52b-5996-4779-b62e-083d7fa0f358.jpg)
Stock Youtube:
![Screenshot_20230428_063013_YouTube](https://user-images.githubusercontent.com/30195961/235055691-38a70d38-96ae-4ff8-baaa-fb2d079a5885.jpg)

### Steps to reproduce

~

### Relevant log output

```shell
~
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SodaWithoutSparkles** [comment]
I patched just now using 2.171.0. This issue is still there, but it seems that this issue only affects the first video. Once you watched another video, the subtitle position returns to the bottom. Watch the first video again and the subtitles are normal again.

Steps to reporduce: 

1. Force-stop revanced and clear its cache
2. Launch revanced and watch a video that you for-certain knows it has subtitle. Example: one from LTT
3. Expect to see subtitles are at the top
4. Watch another video that you also knows that there are subtitles
5. Expect to see subtitles are in the bottom
6. Go back and watch the same video from step 2
7. Expect to see the subtitles goes back to the bottom again

**Comment by SodaWithoutSparkles** [comment]
While I am here, do you want some kind of debug log? I have adb access to that device. I don't know what I should grep for tho.

**Comment by SodaWithoutSparkles** [comment]
Or use both the first and the second call to determine if the fix was needed? Wouldn't option 1 cause the first subtitle line to be dropped/hidden/cause undocumented behaviours?

**Comment by SodaWithoutSparkles** [comment]
@LisoUseInAIKyrios Do you also contribute in the RV manager project? It would be nice to be able to use the dev channel on manager.

**Comment by oSumAtrIX** [comment]
Moving to #1752
