### ISSUE TITLE
feat: Patch for blocking ads in Telegram

### ISSUE THREAD

**Issue by topminipie** [ReVanced/revanced-patches#202]
### Feature description

Target application: "org.telegram.messenger"
[Google Play](https://play.google.com/store/apps/details?id=org.telegram.messenger)
[telegram.org](https://telegram.org)
[GitHub](https://github.com/DrKLO/Telegram)

Patch to disable advertising in:
chats,
channels,
on the start page ("Buy Telegram Premium").

Screenshots:

<img alt="2" src="https://github.com/ReVanced/revanced-patches/assets/145812405/fb1dc541-e845-40da-9fba-b7bf08af3330" width="50%">

<img alt="3" src="https://github.com/ReVanced/revanced-patches/assets/145812405/f66e7434-2955-4eb0-9475-1eb64e46c782" width="50%">

Maybe this will help:
[Killergram](https://github.com/shatyuka/Killergram/blob/master/app/src/main/java/com/shatyuka/killergram/MainHook.java)
[Killergram](https://github.com/JeelsBoobz/Killergram/blob/main/app/src/main/java/com/jeelsboobz/killergram/MainHook.java)
[TMoe](https://github.com/cinit/TMoe)

It would also be nice to have this patch for third-party custom Telegram clients. (Based on official client)
Example: 
ForkGram   Package name: "org.forkclient.messenger.beta"     [GitHub](https://github.com/forkgram/TelegramAndroid) 
Telegram-FOSS   Package name: "org.telegram.messenger"     [GitHub](https://github.com/Telegram-FOSS-Team/Telegram-FOSS) 

### Motivation

I think it’s only a matter of time before advertising appears right between messages in channels/chat rooms.

More recently, advertisers have started using bright (red) sticker inserts.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
