### ISSUE TITLE
feat: (Disney Plus) allow adjusting Playback Speed

### ISSUE THREAD

**Issue by frogjet** [ReVanced/revanced-patches#203]
### Feature description

The Disney Plus app currently does not allow you to adjust playback speed at all. Adding options similar to YouTube or Netflix where you can select custom speeds would make the app nicer to use.

### Motivation

Some content on Disney Plus would be much better if you could speed it up faster than 1x speed.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by speedstyle** [comment]
Modifying the Disney+ APK would prevent Widevine checks from passing and disable playback entirely.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
