### ISSUE TITLE
feat(Spotify): Hide Podcasts

### ISSUE THREAD

**Issue by UraniumDonut** [ReVanced/revanced-patches#2041]
### Application

Spotify com.spotify.music

### Issue

Podcasts are visible.

### Patch

Podcasts are not recommended on the home screen.

### Motivation

People are annoyed by podcasts in a music app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
