### ISSUE TITLE
feat(YouTube Music): Audio normalization (Stable volume)

### ISSUE THREAD

**Issue by JamesTablefield** [ReVanced/revanced-patches#2042]
### Issue

The difference between audio levels of songs

### Patch

Since YouTube Music has its stats for nerds option you can see the content loudness level as well. Would like to see an option which acts like ReplayGain to flatten the audio level difference between songs. I don't use general YT music but for my library but I wonder if it's possible.

### Motivation

I think it would help at least to ease the annoyances of turning the volume up and down all the time and since music's loudness very tend to differ, it'd would save a lot of hassle, in my eyes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by TheW0LVERIN3** [comment]
+1 Now that youtube revanced has it, only youtube music revanced still needs it.

**Comment by TheW0LVERIN3** [comment]
> YT now has a 'stable volume' feature built in. No patch needed.

@LisoUseInAIKyrios Yeah, but youtube **music** (a completely separate app with different patches) doesn't have this. 
Please reopen the feature request.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
