### ISSUE TITLE
feat(YouTube): Change subtitle text size

### ISSUE THREAD

**Issue by bablabl** [ReVanced/revanced-patches#2046]
### Application

YouTube 

### Issue

normal subtitles are too big and small are too small

### Patch

just new option between normal and small subtitles sizes, nothing fancy

### Motivation

its not valuable for many people, but for ones that are still in process of learning vocabulary, these ,,normal" subtitles take too much screen and with small ones you cant see shit + they are not centered

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
