### ISSUE TITLE
feat:(youtube)the ability to change MORE of the app apart from changing the colors.

### ISSUE THREAD

**Issue by Techfromthepast123** [ReVanced/revanced-patches#205]
### Feature description

So I had an idea,would it be possible if you could make a patch to add another level of customization apart from just changing colors ?

Changing the YouTube logo with a custom image,changing the background and topbar texture,changing the position of the bottom navigation bar to the top,changing video pages stuff (compact related videos like in 2020,video player icon images) aswell has changing the border radius on thumbnails and other stuff,changing the font,etc... 

Bring back old youtube layout stuff (If the spoof version patch stops working completely)

### Motivation

This feature would be cool to be implemented because we could change the youtube logo at the topbar to anything image we want (example: the old youtube logo)
And aswell has changing topbar texture and it's icons like search,cast,etc...

We could even make themes to make youtube look like older versions with this or make any theme we want with full customization apart from the colors!!!

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
