### ISSUE TITLE
feat(TikTok): System volume UI

### ISSUE THREAD

**Issue by Rosentti** [ReVanced/revanced-patches#2054]
### Application

Tiktok 

### Issue

Tiktok's volume bar sucks and doesn't let you adjust per-app volumes as it disables the system volume UI for no reason. It also has way bigger steps than the system volume UI.

### Patch

Disable TikTok listening to media keys on video pages. Tiktok's camera can use volume keys.

### Motivation

This patch would be extremely useful for anyone wanting to:
- Listen to TikTok more silently (at night)
- Use features available only through the system's audio UI

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
