### ISSUE TITLE
feat(TikTok): Remove banner ads

### ISSUE THREAD

**Issue by K4Z3R0** [ReVanced/revanced-patches#2070]
### Application

TikTok (com.zhiliaoapp.musically)

### Issue

Banner ads like the one in the picture circled in red
![Screenshot_20220924-205414_1](https://user-images.githubusercontent.com/90075041/192100563-af1dfd8b-bc94-4bac-9d44-13106703bbfa.png)

### Patch

Remove banner ads

### Motivation

Ads are annoying

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
