### ISSUE TITLE
feat(YouTube Music): Force tablet UI landscape mode for non tablets

### ISSUE THREAD

**Issue by Silent000Lain** [ReVanced/revanced-patches#2086]
### Application

YouTube Music

### Issue

As per default YouTube Music behavior, you can only use the app in portrait mode on a smartphone. However YouTube Vanced had a feature to force enable landscape mode for smartphones, which actually uses the tablet UI while in landscape. The media player will then be on the left half of the display while the playlist is simultanously shown on right half of the screen.

### Patch

Force enable landscape mode with tablet UI for smartphones.

### Motivation

While driving a car, I actually have my phone mounted in landscape above the dashboard. The tablet UI makes it handy to see the media player as well as the playlist to very quickly select / see what's next, instead of needing to tap "up next" to bring up the playlist and then return back to the player, which takes too long and is unsafe for driving. Additionally, using an app in portrait mode while the phone itself is mounted horizontally, is literally a neck twister.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
