### ISSUE TITLE
feat(X / Twitter): Video Quality Selector

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches#209]
### Feature description

Add a quality selector for videos like in [OldTwitter](https://github.com/dimdenGD/OldTwitter/blob/32ad48a1d0d4598f23a179a5bd1e3baf1c9f3481/scripts/tweetviewer.js#L1191).
![IMG_20231016_032454](https://github.com/ReVanced/revanced-patches/assets/32636532/9217f4e9-f708-4f10-b8cf-0d0262cd8ca7)

### Motivation

The Twitter android app always uses a low quality for videos.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
