### ISSUE TITLE
feat(YouTube): Integrate NewPipe in app downloading (without opening a separate external app)

### ISSUE THREAD

**Issue by 0-BlackSpectrum-0** [ReVanced/revanced-patches#2122]
### Application

Youtube 

### Issue

Current solution is nice but we need to switch to different apps to see downloaded videos and watch download % as well!

### Patch

New patch let's you download yt video from newpipe but it'd be really nice if you could fully integrate newpipe download feature in revanced so if I select download it'll directly ask me quality and format mp3 or mp4 to download also in library tab, all downloads would be visible under download page like we can map it to fetch video from a particular location on Internal/external storage where these videos are downloaded and saved!
And we can download in max quality too even though phone doesn't support it! 
Please add this if possible!

### Motivation

I just thought of it when I saw the new download feature it's good but less convenient!

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
