### ISSUE TITLE
feat(YouTube): Dimmed UI

### ISSUE THREAD

**Issue by arichornlover** [ReVanced/revanced-patches#2124]
### Application

YouTube + YouTube Music

### Issue

Some of the unneeded Contrast UI Elements of the YouTube App. Which contains texts, icons, settings, profile and other to revert them to the easy-on-the-eyes UI

### Patch

It’s a new patch for YouTube Revanced. I’m just trying to give everyone like me a new setting/option on ReVanced YouTube App their way of having to be able to reduce High Contrast in Dark Mode/Light Mode. Ever since August 2020, YouTube changed the way the UI should’ve looked and never added a option to let users turn off the high contrast color and since YouTube is not letting us change it will effect a lot of people with eye strain age with this new contrast UI and I do get it they are helping colorblind people but people in different conditions can get headaches/eye strains from it which is why there should be a setting. and I do know that not all of the UI will be modified since some elements of the app uses server side stuff but either way it still improves the UI and really deserves a patch.

### Motivation

Prevent Eye Strainage or any other eye problems, headaches and some others that I can’t confirm and definitely makes ReVanced like it is today! ⭐️

Image of what the patch looked like on the texts:
![8EE7C073-AAF8-4A72-B783-B44791E5B2C5](https://user-images.githubusercontent.com/78001398/190922531-0e552061-64a1-4bd2-905e-a1a140c54e8d.jpeg)

colors that should help the ReVanced team. ⬇️
[TextPrimary] & [TextSecondary] YT Dark/OLED Mode Hex Code: #909090
[TextPrimary] & [TextSecondary] YT Light Mode Hex Code: #606060

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
