### ISSUE TITLE
feat(patch): Youtube Hide recommended videos

### ISSUE THREAD

**Issue by mangoepic** [ReVanced/revanced-patches#2139]
### Application

Youtube

### Issue

Like the Unhooked Chrome extension it should give the option to disable the home feed or maybe even recommended videos etc per option.

### Patch

Options to
 - Disable startpage (remove from bottom toolbar)
 - Disable recommended videos
 - Shorts? not sure if already has a patch
 - Other things maybe inspired by Unhooked

### Motivation

Reasoning for this is to help make YouTube less addictive and a more deliberate tool of choice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DrSapling** [comment]
Disabling shorts and home page is already a thing (but the home page still apears whennlaunching the app which I think is a "bug") however disabling recomendations would be nice. And disabling shorts shouldn't make them disapear from subs feed, just make them launch with regular viewer.

**Comment by sharpsteelsoftware1** [comment]
IMO this is a hugely critical final piece of this app. It has done everything I dream of with the YouTube app. But when I open YouTube Revanced, it dumps me on the Home page, with YouTube's awful and ugly recommendations. They ruin my day -- I need this so I can get off other YouTube clients. I love this project, INCREDIBLE work.

**Comment by Bassani-Paulo** [comment]
Now that the feed can be removed, to put it more clear than the above, we just need:
- hide the recomended videos from below the comment section
- hide recomended videos that are shown together with search results

the last one I don't know if can be done, but the first would be much appreciated by the adicted community

**Comment by KobeW50** [comment]
> Now that the feed can be removed, to put it more clear than the above, we just need:
> - hide the recomended videos from below the comment section
> - hide recomended videos that are shown together with search results
> 
> the last one I don't know if can be done, but the first would be much appreciated by the adicted community

You can hide those with custom filters.

Settings > Revanced > Layout > Custom filter.

Enter: `search_video,related_video`

**Comment by oSumAtrIX** [comment]
This is highly dangerous as it strains the API.

**Comment by oSumAtrIX** [comment]
The home feed can be bypassed by hiding the home button and replacing the YouTube icon with a YouTube shortcut on your Launcher.

**Comment by biscober** [comment]
That works, though it's not an ideal solution for those of us who launch YouTube exclusively from the app drawer and prefer not to clutter our home screen with additional icons.

**Comment by oSumAtrIX** [comment]
The solution should be sufficient

**Comment by DidierLoiseau** [comment]
> This is highly dangerous as it strains the API.

@oSumAtrIX  What exactly is highly dangerous? I’m looking for a solution to hide the recommended videos below the player, the custom filter seems to work well.

**Comment by oSumAtrIX** [comment]
The app tries to automatically fetch new videos, the components are replaced with an empty component, thus, the client fetches new videos. This continues in an infinite cycle straining the API.

**Comment by Bassani-Paulo** [comment]
@DidierLoiseau , as an youtube adicted myself, the soft solution I made to this was to bring the ads back on.

This way the first thing that appears bellow the video is the ad and I do not see the video recommendations. It is still not ideal because you see ads and you could scroll down and see the recomendations. But in a similalr way you could click on the youtube logo at the to left corner and go to the home page or alternatively during a video make a slide up gesture and see a recomendation carousell. But I personally do not find myself doing any of this as it is much easir to resist not seeing a recomendation thatn it it to resist not clicking on an interesting one that you are seeing. To the point that I forget about those gestures exist.

For me now the biggest issue is the youtube messing up with search results.

**Comment by biscober** [comment]
This issue really seems to be for two separate issues.  Regarding the issue of lacking the functionality to automatically load to the subscriptions tab, maybe there can be some reconsideration.  For people who have watch history disabled, Youtube is turning the home tab into a giant button for turning watch history back on instead of listing any videos.

Having to clutter my clean home screen with a special shortcut for Youtube is not a sufficient solution for me, so for now I have to keep opening the app and pressing subscriptions at the bottom.  A sufficient solution would be having the ability to open Youtube from the app drawer and have it open directly to the subscriptions tab, skipping the soon-to-be-useless home tab.  This feature would not result in any unreasonable API calls, unlike the other issues being discussed above.

I understand the desire to avoid feature bloat as it increases the number of patches that have to be maintained for each update.  However, I think the ability to have the app open directly to Subscriptions tab is a very useful feature that is worth more consideration.

**Comment by oSumAtrIX** [comment]
> However, I think the ability to have the app open directly to Subscriptions tab is a very useful feature that is worth more consideration.

You can do this on YouTube natively by holding on the icon, then dragging out the subscription list item to your home screen.

**Comment by biscober** [comment]
> > However, I think the ability to have the app open directly to Subscriptions tab is a very useful feature that is worth more consideration.
> 
> You can do this on YouTube natively by holding on the icon, then dragging out the subscription list item to your home screen.

I guess the sticking point for me is that I strongly prefer maintain a clean home screen with no shortcuts. I open every app from the launcher, and my home screen is strictly for weather widgets and things like that. Dragging a shortcut to the home screen would degrade the aesthetic of my device, but more importantly since I've used my devices this way for a decade I probably wouldn't remember to use the shortcut. When I want to open an app, I instinctually open the app drawer.

I realize this probably sounds really petty and stupid to people who do have shortcuts on their home screen and use them. If there were a way to add this shortcut to my app drawer I'd be happy with that, but I don't think pixel launcher can do that. That's the reason I respectfully ask for reconsideration of this feature. And I'll leave it at that - if the answer is still no, I respect that. No one is entitled to free work from the developers, after all.

**Comment by DidierLoiseau** [comment]
> The app tries to automatically fetch new videos, the components are replaced with an empty component, thus, the client fetches new videos. This continues in an infinite cycle straining the API.

I see indeed. There seems to be 3 or 4 spinners and then it stops, but I also noticed some performance issues which might be related.

So there isn’t a good solution, I guess. Should there be a separate feature request for this then?
