### ISSUE TITLE
feat(YouTube Music): Remove or bypass 'Viewer discretion is advised' warning 

### ISSUE THREAD

**Issue by Heyoxe** [ReVanced/revanced-patches#2141]
### Application

YouTube Music 

### Issue

Some music have a "Viewer discretion is advised" warning  that you have to dismiss manually every time. Failure to dismiss the warning (either if you are playing the music in the background or by clicking on "cancel") will skip the song.

### Patch

A toggle inside the settings to completely disable this pop-up (and act as if it was accepted).

### Motivation

Any music having this pop-up cannot be played in the auto-play mode which defeats the purpose of this app.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
