### ISSUE TITLE
feat(YouTube): Disable cropping of 4:3 videos in the feed

### ISSUE THREAD

**Issue by kocane** [ReVanced/revanced-patches#2158]
### Application

YouTube

### Issue

Videos of the 4:3 format are cropped to 16:9 when you scroll down thru comments or recommendations.

### Patch

Give an option to disable this behaviour.

### Motivation

It would be nice to have the optional feature to disable this behaviour so that you can watch the "whole" of the video when reading comments without having to constantly "maximize" it.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
