### ISSUE TITLE
feat: Youtube: A-B Repeat

### ISSUE THREAD

**Issue by TheShadowRunner** [ReVanced/revanced-patches#218]
### Feature description

I'd like to request an A-B Repeat feature.

An additional Button on the main video screen, just like the copy link / copy link + time buttons.

First press sets A, the second press sets B.
Further press cancels AB repeat and restores continuous playback.

Ideally gapless to be able to create perfect music loops.

### Motivation

Very useful when: 
- Learning languages
- Learning bass line
- Obsessing over certain music sequences
Thank you for considering. 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
