### ISSUE TITLE
feat: ReVanced Reddit Patch - Bypass out.reddit.com tracking

### ISSUE THREAD

**Issue by nightznero** [ReVanced/revanced-patches#2194]
### Type

Other

### Issue

Reddit tracks the links you open with a redirect to out.reddit.com. This patch bypasses the redirect without visiting the site.

Search for ```.class public final Lcom/reddit/domain/model/OutboundLink;```

Replace the getUrl method in the same file with this:

```smali
# get the "url" query in the out.reddit.com link and return that instead.
.method public final getUrl()Ljava/lang/String;
    .locals 5

    iget-object v4, p0, Lcom/reddit/domain/model/OutboundLink;->url:Ljava/lang/String;

    const-string v1, "https://out.reddit.com"
    if-eqz v4, :return

    .line 1
    invoke-virtual {v4, v1}, Ljava/lang/String;->startsWith(Ljava/lang/String;)Z

    move-result v1

    const/4 v2, 0x0

    if-eqz v1, :return

    .line 2
    invoke-static {v4}, Landroid/net/Uri;->parse(Ljava/lang/String;)Landroid/net/Uri;

    move-result-object v0

    const-string v3, "url"

    invoke-virtual {v0, v3}, Landroid/net/Uri;->getQueryParameter(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    if-eqz v0, :return

    const-string v3, "UTF-8"

    .line 3
    invoke-static {v0, v3}, Ljava/net/URLDecoder;->decode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    move-result-object v0
    return-object v0

    :return
    return-object v4
.end method
```

### Feature

☯️

### Motivation

☯️

### Additional context

☯️

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
