### ISSUE TITLE
bug(YouTube - Always repeat): Patch should be reworked

### ISSUE THREAD

**Issue by TheJeterLP** [ReVanced/revanced-patches#2223]
### Type

Functionality

### Issue

Currently the auto-repeat patch completely ignores youtubes auto-repeat setting in the player controls and uses its own setting.

### Feature

Patch should be changed to behavior like the video-quality patch. So remember the setting when the user changes it in the player controls.

### Motivation

Some users don't seem to understand that the patch uses its own setting and report false bugreports. 

### Additional context

Remembering the value should be toggleable from revanced settings. Maybe some users don't want it to always be remembered.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
