### ISSUE TITLE
facebook lite, disable in app browser and allow inbuilt messenger to open all messages

### ISSUE THREAD

**Issue by SalvatoreNoschese** [ReVanced/revanced-patches#228]
### Feature description

Hi, ATM removed Facebook and messenger, I really prefer Facebook lite but this use in app browser and inbuilt messenger can open only message from users (if I try with messages from page, ask me to use messenger).

A patch for this will be very appreciated.

### Motivation

Because Facebook still require messenger and Facebook lite looks like a best alternative.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request is free to PR it. Thanks for the feature request!
