### ISSUE TITLE
feat: Unlock TickTick Widgets

### ISSUE THREAD

**Issue by rahaaatul** [revanced/revanced-patches#2283]
### Application

TickTick:To-do list & Tasks

### Issue

Unlock the locked widgets.

### Patch

Unlock the premium widgets

https://github.com/revanced/revanced-patches/assets/86149861/9d59f0a5-0069-4468-b7ba-abf9bb61d177

### Motivation

It can show you your tasks on the home screen in details, saves time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rahaaatul** [comment]
@oSumAtrIX May I ask why this issue was closed?

**Comment by oSumAtrIX** [comment]
No good motivation provided.

**Comment by Stale-1** [comment]
> No good motivation provided.

I hope you reconsider the request. 

Instead of just unlocking the premium widgets, Unlocking all the premium features would be better. 

Motivation
* Convenience - With Ticktick Premium Widgets people don't need to open the app and scroll to find the Task/Note instead they can just take a glance in their homescreen.
* Alternative to Google Calendar - People who use Huawei and also those who want to separate to Google Apps can use this app instead of Google Calendar.
* Group Task and Logging - You can create a Group Task and Logging feature that list the changes commited by other members. Good for overall management of time and activities.

**Comment by oSumAtrIX** [comment]
There's many similar apps, doesn't mean this one needs to be unlocked.

**Comment by rahaaatul** [comment]
> There's many similar apps, doesn't mean this one needs to be unlocked.

But this is the best one out of all of them.
