### ISSUE TITLE
feat(YouTube): Custom domains for pfps and YouTube community pics

### ISSUE THREAD

**Issue by ktheticdev** [ReVanced/revanced-patches#2288]
### Type

Functionality

### Issue

The yt3.ggpht.com domain is currently banned in Russia, that is why it is impossible to view profile pictures. yt4.ggpht.com is, however, available. 

### Feature

A patch that would let users either to switch to yt4.ggpht.com or to switch to a custom domain that can be specified in ReVanced settings would solve the problem and pfps will load. 

### Motivation

Many Russian YouTube users right now can't view profile pictures and community posts, which is annoying and would be a nice fix for everyone who uses YouTube in that region.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
