### ISSUE TITLE
feat(JADX): Plugin to autogenerate fingerpints and patches

### ISSUE THREAD

**Issue by Sculas** [ReVanced/revanced-patches#2291]
### Type

Functionality

### Issue

Currently, fingerprints and patches have to be written by hand. While this is not an issue for some, this can be a challenge for newcomers.

### Feature

Develop a [JADX](https://github.com/skylot/jadx) plugin (either using the current Java API or the new KTS API) to autogenerate fingerprints and patches.
This system will include checking if said fingerprint actually resolves to the correct method, and if needed autogenerate parent fingerprints. It should prefer string patterns over opcode patterns. It would also be nice if it can minimize the opcode pattern as much as possible.

Creating patches would be made easier too, just click "Create Patch", make your changes and click "Done"!
The developer would need to know how smali works, but smali is quite an easy language to learn.

### Motivation

This would allow newcomers to create fingerprints and patches very easily and speeds up patch development in general.

### Additional context

Optionally port this plugin over to [Recaf](https://github.com/Col-E/Recaf) when Android support has been added. It's a good alternative to JADX (when Android support has been added) and supporting more decompilers is always good.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by Sculas** [comment]
Makes total sense, and nowadays the documentation suffices for one to learn it themselves anyway 👍
