### ISSUE TITLE
feat: Pinch to zoom and/or increase font sizing for Reddit

### ISSUE THREAD

**Issue by sliceanddice9** [ReVanced/revanced-patches#230]
### Feature description

Using the default official Reddit app or the official ReVanced Reddit app there is no way to zoom in or scale the font to make it larger.

### Motivation

Enabling a zoom gesture and/or control to make the font size bigger will make navigating Reddit easier on the eyes.  

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request is free to PR it. Thanks for the feature request!
