### ISSUE TITLE
feat: Remove iFunny ADs

### ISSUE THREAD

**Issue by xdevilkillx** [revanced/revanced-patches#2342]
### Application

iFunny

### Issue

Even with domains blocked some ADs (possibly built in) still show up or appear as blank boxes .

### Patch

Remove banner ADs, comment ADs, and ADs seen while swiping through posts.

### Motivation

As mentioned before it would be appreciated by the Android iFunny community.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by xdevilkillx** [comment]
Really made me open a whole other issue instead of just stating that in the original.

**Comment by xdevilkillx** [comment]
What motivation would you have wanted then? Donations? Lack of a premium option so lucky patcher is out of the question? "You can do it! I believe in you!" Or some other crap like that?

**Comment by xdevilkillx** [comment]
Because it' scummy for a company to have embedded ads in their app with no option for premium? What do you want from me, a twelve page business offer?

**Comment by Julius8900** [comment]
Keep in mind that developers work on their free time and opening an issue won't guarantee that the patch or the issue will be solved.

**Comment by oSumAtrIX** [comment]
@xdevilkillx You opened a request we can deny or accept. We will deny it if you don't give us a good reason to accept the request.

**Comment by Fireeyeeian** [comment]
@xdevilkillx and anyone else that wants to block ads for the time being untill someone takes up this request or if I ever get some free time to actually get into android app dev eventually, I'll give it a try.
Downgrade to at least version 8.1.3 (find a "_trusted_" site to get the apk from (I know))  and use a dns adblocker or if you have root you could also use AdAway (either way works). Doing this will bring back the bug that sometimes makes you have to view a users profile in order to fullscreen view a reaction image in the comments and have that banner/nag that says it needs an update or it wont work (it will, even version 5.X still works fine ) but the compromise allows you to block ads.

Steps:

1. uninstall Ifunny 
2. install older version (from my testing 8.1.3 is the version right before they baked in comment ads, swipe ads, and banner ads)
3. make sure auto update is off in Playstore if it's detected there.
4. profit?
