### ISSUE TITLE
feat: Reddit is Fun patch

### ISSUE THREAD

**Issue by mtswilnd3865** [revanced/revanced-patches#2424]
### Application

Reddit is Fun

### Issue

The current Revanced patcher does not include Reddit is Fun in the list of supported apps. 

### Patch

Is it possible to implement Reddit is Fun support in the same way that Revanced did for Sync for Reddit?

### Motivation

The looming API changes for third-party Reddit apps has basically killed off third-party apps and Reddit is Fun, along with Apollo, has announced its intention to shut down by the end of the month. By providing a revanced Sync for Reddit, it should be possible for other third-party Reddit apps to be included in Revanced in order to ensure they can still be used beyond the API deadline. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Any specific reason why it should be added when Sync is already present?

**Comment by snvoid** [comment]
Not OP, but Its down to preference. Some of us prefer RIF because its what we have used since it first came out and it works exceptionally well.

**Comment by profucius** [comment]
> Any specific reason why it should be added when Sync is already present?

Sync is decently customizable, but pales in comparison to Boost for Reddit, which is what I prefer.

Revanced team will hopefully make patches for each 3rd party app, not only for the sake of the users who prefer their own, but also for diversity against Reddit busting one app and then everyone breaks.

Diversity, diversity, diversity.

**Comment by Aunali321** [comment]
> Revanced team will hopefully make patches for each 3rd party Reddit app, or at least prioritize the big 4 (Sync, Boost, RIF, Infinity).


Why waste time making the same thing for each app? Reverse engineering and making a patch takes time. The efforts will increase significantly to support other apps. You can't just copy paste patch. Unless there is a reason to besides user's preference. It better to ask the app developers to support changing api key.

**Comment by profucius** [comment]
I'll admit that I'm not aware of it being a time-consuming process to patch/replace an API key within an app. It seems that it would be more of a minor thing to change. If it is time consuming, I can understand not patching every single Reddit app without the demand for it.

However, what I can guarantee is that Boost certainly has more customization options than Sync does. It's difficult to prove that to you unless you download it yourself to look. Sync has a few theme/color choices and a couple font size choices, but by-and-large you're stuck with one of the main formats (e.g. Card, List, Compact, etc) and you can minorly tweak those aspects. 

Boost on the other hand is almost like editing CSS, it lets you change nearly every aspect, down to the font color and size of each and every type of text the app presents. It has more control options of other types of features as well, like moving the Navigation Pane to the right side, a more concise display of links (esp. when there is no preview, Sync just shows a big grey box), and other QoL things of this nature.

---
I did try contacting the Boost dev, and they seem to be going dark after the whole fiasco on reddit. I've also made multiple public comments on the app's subreddit, and have received many upvotes in agreement that others want the ability to continue using Boost in particular, with their own API key.

I can understand having a lot on your plates, and perhaps not having the time at the moment to release patches for all the reddit apps. But I'm asking that you consider the idea of making a single release of other 3rd party reddit apps than just Sync. It would also seem to me that there is little need to "support" these patches beyond their initial release, since practically all of the 3rd party reddit app developers are throwing in the towel, these apps likely will never receive any further updates, meaning the patch methods will probably never change either. If the API key changes, the end-user replaces it in the txt file and reruns the existing patch. Perhaps there is more to this than I'm aware, but it seems less complex than supporting an app that changes constantly.

**Comment by jordan1776** [comment]
> I need some explicit reason or feature on why Sync does not suffice. So far Boost and co. haven't compared against Sync and its customizability and rich amount of features

Probably the most simple reason is popularity, there isn't really a "big 4" as really "rif, a few smaller ones, and a bunch of less popular apps". RIF has more installs (5m) than Boost (1m), Baconreader (1.1m), Sync (1.1m), and Relay (1.1m) combined. If there is any app that should have personal api input, rif is it.

**Comment by Winterhasarrived93** [comment]
Think it's been said above, but boost for Reddit has been my go to for the last few years, best for efficiency and navigation and overall look for me. 

Overall though, I'm honestly happy that the Devs have done one app let alone considering doing more. Thank you so much for yours efforts and if nothing else I appreciate it greatly

**Comment by Aunali321** [comment]
I am almost done with Boost patch. It works on CLI, needs some work on manager because of some issue. RIF is alot more complicated because of obfuscated/minified code and obfuscated api calls.

**Comment by Winterhasarrived93** [comment]
> 

Amazing news, great stuff and thanks for the efforts

**Comment by oSumAtrIX** [comment]
@profucius 

> However, what I can guarantee is that Boost certainly has more customization options than Sync does. It's difficult to prove that to you unless you download it yourself to look. Sync has a few theme/color choices and a couple font size choices, but by-and-large you're stuck with one of the main formats (e.g. Card, List, Compact, etc) and you can minorly tweak those aspects.

I have checked Boost and Sync had a magnitude of more options. While yes, boost may allow to change certain small aspects of the client, that Sync does not, theres also a lot that Sync does, that Boost can't. Considering that Sync now has more options, I am not sure how you come to your conclusion above.

**Comment by lilbro93** [comment]
> I am almost done with Boost patch. It works on CLI, needs some work on manager because of some issue. RIF is alot more complicated because of obfuscated/minified code and obfuscated api calls.

Thanks for your 
work. It is greatly appreciated. 
Just another proud revanced user would like to nominate Rif for being considered to receive a patch. 

Goid luck with your work.

**Comment by meilluer** [comment]
> Any specific reason why it should be added when Sync is already present?

One probably would be that boost allows users to set quality for videos and images and have much much better data saving features

**Comment by oSumAtrIX** [comment]
In sync you can chose between video qualities too & it also has data saving feature

**Comment by meilluer** [comment]
> In sync you can chose between video qualities too & it also has data saving feature

Agreed but it's not as good as boost like I can custom set video quality for each video 220p 360p or 720p no such option seems to be available in sync

**Comment by oSumAtrIX** [comment]
What Sync offers is enough for it's purpose of saving data

**Comment by profucius** [comment]
I don't think it's productive to argue here about the philosophy of choice between 3rd party reddit clients. @Aunali321 has stated there is progress on the patch for the Boost client. I'm very much looking forward to it.

**Comment by meilluer** [comment]
> What Sync offers is enough for it's purpose of saving data

Did some testing and on an average boost uses 2x to 1.3x less data which means a lot for people like me who are on data caps which I assume a lot people are on their mobile devices

**Comment by oSumAtrIX** [comment]
Please include reproductive steps to test it.

**Comment by meilluer** [comment]
> Please include reproductive steps to test it.

Have fresh install of both sync and boost
Set data saving setting on both
Install any data monitoring tool
Scroll to and perform. Same actions and same post on both app
You could see that boost on data saving setting saves a lot more data

**Comment by gui-lherme** [comment]
>Probably the most simple reason is popularity, there isn't really a "big 4" as really "rif, a few smaller ones, and a bunch of less popular apps". RIF has more installs (5m) than Boost (1m), Baconreader (1.1m), Sync (1.1m), and Relay (1.1m) combined. If there is any app that should have personal api input, rif is it.

This. RIF is the most popular Android 3rd party app for Reddit. It more than deserves and API patch like Sync received

**Comment by oSumAtrIX** [comment]
While it may have many downloads that does not equate to it being the most popular. Regardless of that, the alternative clients already can what RiF can

**Comment by FazeThree71** [comment]
I'd be interested in a RiF patch too.

**Comment by r-ook** [comment]
I too use RIF and would love it if it can be patched.  I understand the reality looks grim just want to show some support.

**Comment by toconquer** [comment]
RIF has the largest install base and in many cases the users of the app have been supporting it for more than a decade, having purchased the golden platinum version. The client ID work around would be great given that switching apps after a decade can be difficult for some.

**Comment by oSumAtrIX** [comment]
Added with https://github.com/revanced/revanced-patches/commit/14809cd4510ad9514b4a4820187a81681669374c.

**Comment by irrweg** [comment]
> Sync is decently customizable, but pales in comparison to Boost for Reddit, which is what I prefer. Other 3rd party apps offer their own features, and people use and prefer them because of those features which sometimes Sync doesn't have, or does less well.
> 
> Revanced team will hopefully make patches for each 3rd party Reddit app, or at least prioritize the big 4 (Sync, Boost, RIF, Infinity).

I love Boost, so many options for customization, easy download of pictures, supports external storage, and many more.
To bad reddit decided to kill 3rd party apps.
