### ISSUE TITLE
feat(X / Twitter): Replace the default X (Formerly Twitter) Blue with any color

### ISSUE THREAD

**Issue by szbinks** [ReVanced/revanced-patches#2435]
### Feature description

Currently we can replace the Blue with the user's material you palette, but on samsung phones (and probably other) the implementation of the palette is buggy and not usable in some apps, this include X.

It would be easier to juste paste a HEX code to replace the Blue, for example if I want to reproduce the purple available on the web version I could paste the code #7B59FF and get an equivalent.

### Motivation

This feature can make another existing feature more complete.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
