### ISSUE TITLE
feat(YouTube): Ability to hide Fullscreen Button

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2437]
EDIT: Already implemented in anddea's & YT-Advanced's RVX YT, but not in inotia00's.

### Feature description

Kindly add the ability to hide the Fullscreen Button on videos. Screenshot attached.
![Screenshot_2023-12-15-08-53-34-55_f22faf49515899f9781ec174a4d85388](https://github.com/ReVanced/revanced-patches/assets/91815107/96d90a3c-5200-4724-9aee-579c211cd6b6)

### Motivation

To make the video fullscreen, we can already swipe up on the video, it does the job.

That's why this feature should be implemented.

Thank you.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
