### ISSUE TITLE
bug: (Google Recorder) INSTALL_FAILED_VERIFICATION_FAILURE while trying to install patched apk

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#2464]
### Type

Error while patching

### Bug description

After patching Google Recorder, the patched apk can't be installed.

### Steps to reproduce

1. Patch the APK
2. Try to install. It will show "the app was not installed" error. Use SAI if you wanna get the error below.

### Relevant log output

```shell
INSTALL_FAILED_VERIFICATION_FAILURE
```

### Additional context

I also tried different APKs from multiple sources but they all get the same error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ignamiranda** [comment]
I'm not able to test right now but changing the package name might work. Google has special protections for their apps. The package name patch is currently broken so this needs to be done on the desktop.

**Comment by n1cKz1** [comment]
App does install after changing the package name but it fails to launch. No error, no black screen, nothing. Just doesn't launch.

**Comment by DesolateIntention** [comment]
It might be because the patch fails to apply.

`"Failed to apply remove-device-restrictions: Failed to resolve"`

**Comment by AnonymousWP** [comment]
For me it did successfully apply the patch, but upon installing it says "app not installed" indeed.

**Comment by oSumAtrIX** [comment]
The app has further protections that need to be bypassed.

**Comment by DesolateIntention** [comment]
> The app has further protections that need to be bypassed.

Could this eventually be fixed?

**Comment by IsMaix** [comment]
The patch by Xmader is very outdated and won't work with any newer versions unless a new patch is used or it's updated to work with newer versions.

Firstly, the apk installation:

The reason why many people can't actually install the apk is because of the integrity verification introduced by Google in Android 11 and up. I don't know of many workarounds for this except for changing the package name (to something other than com.google.android.apps.recorder) but that can potentially introduce some issues with patching or sync functionality. So I'm on Android 11 and I've used an xposed patch with lsposed to disable the integrity verification. Of which there are two options, one older that seems deprecated, and one newer that requires zygisk and lsposed shamiko (I used the older one since I'm on magisk 24 without zygisk and it worked just fine).

![SmartSelect_20230627-175348_LSPosed](https://github.com/revanced/revanced-patches/assets/43832909/5343aea7-afc4-4d0b-9e00-17dfef1e0e8a)

Secondly, the patch:

I've found that version [2.0.335556769](https://www.apkmirror.com/apk/google-inc/google-recorder/google-recorder-2-0-335556769-release/) installs just fine and works for me without any patches or modifications or lsposed modules. 

While version [2.2.362762080](https://www.apkmirror.com/apk/google-inc/google-recorder/google-recorder-2-2-362762080-release/) installs with the lsposed module and a patch from luckypatcher.

![SmartSelect_20230627-175258](https://github.com/revanced/revanced-patches/assets/43832909/6961d4f2-9d43-4d7d-8eea-a934d9b39d5b)
![SmartSelect_20230627-175326](https://github.com/revanced/revanced-patches/assets/43832909/5c94c088-6cd0-4895-a347-3e2de6cf933c)


This luckypatcher patch unfortunately doesn't work with any newer versions because the app structure or location  of what needs to be patched changed I guess.

Also, I get this log when I try to patch any version of 
the recorder with revanced
![SmartSelect_20230627-173844](https://github.com/revanced/revanced-patches/assets/43832909/9db24655-8cd0-4949-9d12-cb508baffee3)

**Comment by MaixGit** [comment]
Update:

I've contacted the creator of the patch and yeah these methods are very outdated

"The patch is based on this instruction https://4pda.to/forum/index.php?act=findpost&pid=89934682&anchor=Spoil-89934682-1 But now the apk is protected from modification, and it is not so easy to edit it."

He proposed an alternative method to get newer versions working. By either installing Pixelify or an LSposed module which both aim to enable or get around the com.google.android.feature.PIXEL_(YEAR)_EXPERIENCE flags where the YEAR seems to vary but it just enables all years.

Magisk: https://github.com/Kingsman44/Pixelify
Lsposed: https://github.com/Xposed-Modules-Repo/balti.xposed.pixelifygooglephotos/releases/

However unfortunately the GPhotos LSposed module doesn't seem to work on my phone and while the Pixelify module works for unlocking the pixel feature flags, but there are issues with downloading the language recognition packs and when I restart my phone the app uninstalls/reverts to 2.2.36 which is weird. 

However I am on Android 11 with an s20 fe 5g, and I've been planning to update for a while now and it seems like One UI 5.1 (Android 13) will be the last official update for my phone so I'll update to that over the next week or so and try again with updated magisk zygisk and everything.

**Comment by udiNur** [comment]
Any updates on that?
Failed to install on op11 (verification failed) before and after patch
