### ISSUE TITLE
feat(patch): Various Instagram patches

### ISSUE THREAD

**Issue by bennett-sh** [ReVanced/revanced-patches#2475]
### Application

com.instagram.android

### Issue

Currently Instander has more changes so I prefer it but I hate it that I can't manually patch the app when I want or for betas.

### Patch

- [ ] Material You theme
- [ ] Downloading images/videos
- [ ] Ghost Mode
  - [ ] Don't mark stories as seen
  - [ ] Disable typing indicator
  - [ ] Don't mark as read
- [ ] Disable In-App browser
- [ ] 60s Stories
- [ ] "Follows you" on profiles 
- [ ] Hide ads (stories, discovery, ...)
- [ ] IG Developer Mode

### Motivation

As previously mentioned, I hate that Instander is closed-source/distributed without you knowing what's in it. Having these patches here would therefore be more private & more extendable as you could locally write & patch your own patches on top.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
