### ISSUE TITLE
Requesting Patch for UniFi Protect (com.ubnt.unifi.protect) - Adding Local Devices

### ISSUE THREAD

**Issue by dylangerdaly** [ReVanced/revanced-patches#250]
### Feature description

Requesting a patch for UniFi Protect (https://play.google.com/store/apps/details?id=com.ubnt.unifi.protect) that'll allow hardcoding (or possibly via some UI) a host for UniFi Consoles locally

Someone has already created a patch for an earlier version -> https://github.com/rick51231/unifi-protect-android-direct/blob/master/patches/1.10.1/direct_connection.patch

There are also [patches](https://github.com/rick51231/unifi-protect-android-direct/blob/master/patches/1.10.1/wifi.patch) to disable WiFi Checks

I'll pay a bounty

### Motivation

This allows for the use of viewing IP Cameras without the Cloud Key/Console being accessible via their cloud setup, and instead over a VPN for example.

You get to use UniFi's gear without using their weird cloud thing.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, if anyone comes across this feature request, they are free to PR it. Thanks for the feature request!
