### ISSUE TITLE
feat(youtube):Return YouTube Comment Username

### ISSUE THREAD

**Issue by atuy1219** [revanced/revanced-patches#2537]
### Application

YouTube

### Issue

YouTube recently replaced usernames in the comments section with forced handles.

### Patch

return YouTube comment username like this addon.
https://chrome.google.com/webstore/detail/return-youtube-comment-us/kamibelompadnaekbellinmgbphoidmj
https://github.com/yakisova41/return-youtube-comment-username

### Motivation

Usernames are easy to understand.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Handles are also easy to understand

**Comment by atuy1219** [comment]
However, it would not be a bad idea to have an option to display usernames.
Or is there a problem?

**Comment by oSumAtrIX** [comment]
I can imagine that the instances for comments include a reference to users which should have a username field. Though, this issue lacks good motivation to implement it

**Comment by tesmite** [comment]
> I can imagine that the instances for comments include a reference to users which should have a username field. Though, this issue lacks good motivation to implement it

Although YouTube handles are useful in terms of preventing identity theft, the most common way to distinguish accounts on YouTube is by user name, except in the comments section, and the current notation is inconsistent.
In addition, there are many users whose default YouTube handle is @user-, which is difficult to understand when there are multiple users like this.
I believe that the addition of user names will improve the convenience of the application, as user names used to be used in the past.

**Comment by Albond87** [comment]
Bumping this, +1 for the readability of usernames over handles. I'm sure it can't be that much work to implement? As you say the comment instances probably already have all the user info including handle and username. Plus the linked github repo in the original post above could be useful

**Comment by PeterNjeim** [comment]
I'm not sure why @oSumAtrIX claimed that there wasn't good motivation. YouTube's unilateral and industry-defying change is discriminatory against those that don't use the Latin alphabet, and even those who use the extended Latin alphabet (accents, etc.). I wrote about this extensively in a private feedback message to YouTube, but I'll summarize it here:

- All non-Latin usernames are changed to `user-<alphanumeric>`. Not only does this make determining who's who difficult, it also removes the cosmopolitan nature of YouTube comments, where all cultures and languages are included, now it's just a sea of Latin and poorly romanized names.

- Even worse, a huge portion of YouTube comment culture, whereby a commenter's username was part of their persona (e.g. `FBI`), has been totally demolished. Not to mention the removal of emojis and other Unicode characters.

Not denying that this change is hard to implement, but the closure reason ("handles are fine") is against the mission of Vanced, which is to say that things aren't supposed to be fine, they're supposed to be great. I welcome the reopening of this issue, but do not demand anything from you, thanks in advance

**Comment by oSumAtrIX** [comment]
Handles have a clear purpose to be distinct. The actual name does not matter, what matters is that it is clearly visible who you are talking to. Restricting this to numbers and latin letters is a positive thing as you can not use sketchy characters to impersonate a handle.

**Comment by PeterNjeim** [comment]
> Handles have a clear purpose to be distinct.

Usernames have a clear purpose to be unique. Username collisions have never been a reported problem.

> The actual name does not matter, what matters is that it is clearly visible who you are talking to.

Names are integral to self-identity. Usernames clearly define who you're talking to. In fact, the reduction in character set, and especially the removal of spaces, makes it harder to parse who you're talking to. In addition, the default template for non-Latin names (`user-<alphanumeric>`) also reduces parsability.

> Restricting this to numbers and Latin characters is a positive thing as you can not use sketchy characters to impersonate a handle. 

Illogical claim. Chinese characters can't be used to imitate Latin characters, so the restriction is an overreach (and unnecessary anyways, as impersonation need not be done with sketchy characters, but can be done with Latin characters when username collisions are allowed, rendering the point moot). Impersonation is only done by bots, and continues to be done. YouTube continues to verify prominent YouTubers.

Not to mention, other platforms that use handles, such as X, show the username prominently, and the handle less prominently. Handles are technical in nature, the reason they are restricted to Latin is to make them easy to type for a worldwide userbase, not for any other reason. This is why I stated that YouTube's change was industry-defying, because using the technical handle as the main username is not what major platforms have done thus far (with the notable exception of pseudonymous-by-default platforms, such as GitHub and Reddit, although pseudonymity is still very popular on YouTube and X). It's also notable that channel names don't use handles when viewed under a video, signifying that YouTube treats the username as more important than the handle when it comes to self-indentity.

I look forward to seeing you agree with my points, or if not, a sound rebuttal. If you don't want to participate further, please consider reopening this issue so others can continue the discussion in good faith, thanks in advance

**Comment by oSumAtrIX** [comment]
> Username collisions have never been a reported problem.

Yes they have been and they have been actively abused by using characters that look like others.

> makes it harder to parse who you're talking to

Opposite. I can not type Chinese characters and I won't tell them apart from each other. Latin characters on the other hand have enough characters that you can use to create a unique, clearly identifyable name. 

Regarding your wall of text, shorten it, I won't other reading it

**Comment by PeterNjeim** [comment]
You're acting in bad faith. I didn't say "illogical" as an insult, I used it literally.

Both of your paragraphs are pre-rebutted by my earlier comment.

Not to sound rude here, but I've seen you reply partially to comments in other issues, and also make claims that have already been addressed. The result is always the same, an argument that never ends and is always rehashed.

You mentioned the text being long, I will not work to summarize it as it is sufficiently dense with substance, however you're welcome to use an LLM to summarize it on my behalf. Cheers

**Comment by oSumAtrIX** [comment]
You are free to comment on what I have replied partially. I will repeat claims if your comment ignores them and I see them fit as a response to your comment. I will not go out of my way and use an LLM to summarize your comment, after all it is you who requests something from me, not the other way round.

**Comment by PeterNjeim** [comment]
> You are free to comment on what I have replied partially. I will repeat claims if your comment ignores them and I see them fit as a response to your comment. I will not go out of my way and use an LLM to summarize your comment, after all it is you who requests something from me, not the other way round.

I already replied to what you said though, that's why I said I pre-rebutted them, the reply is in my long comment above. I won't rehash arguments, sorry.

My comment doesn't ignore your claims, so stop repeating them.

The phrase "after all" is short for "after all things have been taken into account". After all things have been taken into account, you're the one requesting a summary from me, not the other way around... I'm seriously unsure how you came to the conclusion you did.

This is the second bad faith comment in a row. Again, if you don't plan on participating in this discussion (bad faith comments usually indicate this), then it's ok, reopen the issue so others can participate with me. I have no beef with you, but I will not sit idly while being responded to in bad faith, hope you understand

**Comment by oSumAtrIX** [comment]
I will require proper comments and eventually motivation to reopen this issue. Unfortunately, none of your last comments have been either and instead throw unrelated comments derailing with clear intention of derailing this issue into a disproprtionated discussion, that being said, leave the discussion, if you are unwilling to cooperate.

**Comment by PeterNjeim** [comment]
> I will require proper comments and eventually motivation to reopen this issue. Unfortunately, none of your last comments have been either and instead, with clear intention derail this issue into a disproprtionated discussion, that being said, leave the discussion, if you are unwilling to cooperate.

My long comment was made with the intention to provide motivation to open the issue, was it not?

My comments were respectful and proper, if not, please specify what was improper, and I will work to address them. I have notified you of what I believe was improper conduct on your part, but you haven't cooperated with me on those thus far.

I'm not sure how I have a "clear intention to derail" this discussion, derailment means off topic, yes? Was my comment not on the topic of handles? Did you not respond to my initial comment explicitly because it was on topic? In this case the past cannot be changed, if my comment was indeed off topic, you wouldn't have responded with a partial rebuttal, am I correct?

What shall I cooperate with you on? That I needlessly summarize my comment? That I aid you in comprehending my pre-rebuttals?

Obviously, most of what I said is rhetorical, it's obvious you are attempting to derail this discussion with what I like to call "pseudo-seriousness", where you pretend to be infallible while simultaneously refusing to engage in discussion, making any excuse possible not to respond. I gotta say, forcing someone else to summarize a comment is a new tactic to me, I like your innovativeness.

Anyways, that's 3 bad faith comments in a row, and you know what they say, 3 strikes and you're out. On Wikipedia this offense would probably result in disciplinary action, but here there is no such thing, so instead I will link you to the [article on good faith](https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith) so that you avoid negative interactions in the future, as you seem to always instigate a negative atmosphere in the issues you've participated in (from what I've seen, at least). Hope you self-reflect and improve, oh, and maybe you'll muster the courage to say "I agree", as it's clear there's an ego issue preventing you from changing your mind, and that's been chronic on the issues I've seen you participate in.

As always, no beef between us, but I'll take your advice and leave this discussion, cheers

**Comment by oSumAtrIX** [comment]
Way too long, once again ignoring my previous request of keeping it short. I'll take your word with your last sentence.
