### ISSUE TITLE
feat(YouTube): Hide Shorts shortcut from app icon long press menu

### ISSUE THREAD

**Issue by Turhvjbufv** [ReVanced/revanced-patches#254]
### Feature description

When long pressing on the icon, the shorts popup jumps, I would like that there will be a patch to disable it
![Screenshot_20231006_113741_One UI Home_1](https://github.com/ReVanced/revanced-patches/assets/91851160/103b33a0-1c03-45ee-91b5-abc154610c65)

### Motivation

My mom doesn't like that my siblings can view shorts and they found this workaround so yeah 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Thanks for the feature request!
