### ISSUE TITLE
feat: (Youtube) : Add an option "Watch this video in Incognito Mode" in the context menu of a video/shorts

### ISSUE THREAD

**Issue by ruffianlabs** [ReVanced/revanced-patches#2565]
### Feature description

For a brief time, YouTube App had an option to Open/Watch videos in Incognito Mode. You just have to click the three dot icon (context menu) next to the Video Title & select "Open/Watch in Incognito Mode". But, it was removed after a while. 

 I would like that option (be back) in YouTube Revanced.  
 
 Something like this : 
 
![featreq1](https://github.com/ReVanced/revanced-patches/assets/112596796/cc7265b9-27b6-434f-ba1a-15bd9fd87d09)

### Motivation

Some videos in our YouTube Timeline can be different from our usual content. As of now, I have been copying the link by share & then, Turn on Incognito & then pasting the video link in YouTube search & then watch the video. 

I believe others would also like that option to open the video in incognito mode without the hoops.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by egscodes** [comment]
Plus if the feature also worked on notifications it would be great
_currently a notification has:_

1. App name, notification time
2. Youtuber name
3. Title of video
4. Channel image
5. Thumbnail
6. Play
7. Turn Off
8. Watch Later
9. (Incognito could go here)

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
