### ISSUE TITLE
feat: add separate hide/unhide patch for category tabs in notification section 

### ISSUE THREAD

**Issue by Wizjul88o** [ReVanced/revanced-patches#257]
### Feature description

It is possible to hide/unhide category bar in notification section separately?

![Screenshot_2023-10-05-22-51-47-967-edit_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/145720270/29f7303d-ebba-4c11-a408-6a7213a2a87b)

Target application: YouTube 

### Motivation

Because i found "comments" in category bar quite useful as it separates tagged comments from all notification 

I know i can  unhide it by disabling "hide category bar in feed" in general settings but it brings back category bar in home feed which i don't won't. i'll really  appreciate if you could separate both of them.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Thanks for the feature request!
