### ISSUE TITLE
feat: can't hide notification button

### ISSUE THREAD

**Issue by Antobm81** [ReVanced/revanced-patches#2590]
### Feature description

In layout > navigation buttons, there is no option to hide the notification panel.

I have found a exploit that allows it to be hidden, but it gets reset after an app restart, I hope this information helps to make a "hide notification button" option

(with hide create already enabled) when I click to swap create with notification, I click cancel instead of restart and, for some reason, that works temporarily

### Motivation

Due to it already being almost possible and everything in notification being visible in the subscription tab, I think it would be a great addition to declutter the YouTube app of redundancy.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You can switch the create with the notifications button and hide the create button

**Comment by Antobm81** [comment]
> You can switch the create with the notifications button and hide the create button

That does not work, there is no way to hide the notification with the available settings except the temporary exploit I mentioned.

**Comment by oSumAtrIX** [comment]
The tab that was occupied by notifications is being hidden.

**Comment by Antobm81** [comment]
> The tab that was occupied by notifications is being hidden.

No matter what I do, the notification tab is never hidden properly and I have changed all settings related to this to verify

**Comment by oSumAtrIX** [comment]
In this case check out our support channels on our social media on revanced.app

**Comment by Antobm81** [comment]
I have sent a message about it on discord and was told to make an github
issue about it.

**Comment by oSumAtrIX** [comment]
Please resolve this on Discord then.

**Comment by Savasdotexe** [comment]
I actually thought this was and still is requesting a feature relating to the badge/button at the top, because I also can't find how to hide the notification **badge/button**. (similar to https://github.com/ReVanced/revanced-patches/issues/251), however it's also been closed...

Even though this is more of a feature request because it supposedly doesn't exist, the actual _solution_, where by toggling off switch create with notifications then hiding the create button removes the **tab** at the very bottom, it doesn't get rid of the top button. I think there's some confusion here with the wording which could be fixed to avoid this.

**Comment by oSumAtrIX** [comment]
There is no patch to hide the bottom at the top, onpy navigation buttons and switching those with the button at the top
