### ISSUE TITLE
bug: tiktok has adds on opening.

### ISSUE THREAD

**Issue by Newbie1980** [ReVanced/revanced-patches#2632]
### Bug description

When you open tiktok revanced there are adds. If app is left for a while and you go back same thing.

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Newbie1980** [comment]
For the brain dead old folks like me. What does closed as not planned mean. I cant attach a error log/report as the app doesn't crash??

**Comment by oSumAtrIX** [comment]
It's a duplicate of another issue

**Comment by drewbitt** [comment]
@oSumAtrIX you stated to open another issue https://github.com/ReVanced/revanced-patches/issues/2534#issuecomment-1884324516 for seeing ads still (after mistakenly closing that one), then closed this one mistakenly as a duplicate of the one you closed? What is the open one?

**Comment by Newbie1980** [comment]
Yes please. What he said

**Comment by oSumAtrIX** [comment]
Indeed, it was closed mistakenly. Please fill everything properly and include reproduction steps in a new issue.

**Comment by drewbitt** [comment]
There really shouldn't have to be three duplicate individual issues for one problem because maintainers want to close prematurely. This happens across this repository. Seems like the format of issues and policy on re-opening takes precedence over actually taking user feedback & bug reporting. I am sure users would appreciate a single sentence on why issues are closed and not the repeated closings without comment I see in this repo. And I am sure you understand the frustration in having to open three or more issues just to report that a single patch is broken. Cheers.

**Comment by oSumAtrIX** [comment]
Issues being closed mistakenly happen and will continue to happen, we aren't robots. Please open a new issue

**Comment by Newbie1980** [comment]
As mentioned i cant attach a crash report etc as it doesn't crash. It simply still has adds when you first open it or open it after a while.

**Comment by oSumAtrIX** [comment]
Reproduction steps, images, versions, combination of patches are useful information that were not included in this issue even though they are requested in the template and required by the acknowledgment. Open a new issue please
