### ISSUE TITLE
YouTube: notification count tweaks 

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#2705]
### Feature description

Add an ability to change how many notifications can YouTube app show (for example instead of writing 9+ it can display 10 for example) or just disable it 
![Screenshot_20240208-135619](https://github.com/ReVanced/revanced-patches/assets/104251188/3f8aeb77-b6d8-4afb-8141-82a570320b94)

### Motivation

It can makes using the app more comfortable by seeing the exact notifications count or without it

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by 111ebobo** [comment]
> The notification badge on the app icon can be turned off in your phone settings.  Don't need a patch for that.

This one in the screenshot doesn't

**Comment by oSumAtrIX** [comment]
The motivation is hardly sufficient. It is not necessary to know how many notifications you have, it could be 1 or 100.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
