### ISSUE TITLE
feat(YouTube): Allow ambient mode when battery saver is on

### ISSUE THREAD

**Issue by Kevinr99089** [ReVanced/revanced-patches#2712]
### Feature description

This patch would allow to bypass Ambiant Mode restriction when Battery Saver is On for YouTube.

### Motivation

For those who like the ambient mode, but can't enjoy it because of the battery saver (e.g., when the battery can't hold a charge, or simply for those who leave the battery saver on (like me))

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
