### ISSUE TITLE
bug: Google Assistant does not open Google ReVanced apps

### ISSUE THREAD

**Issue by CrazyWolf13** [ReVanced/revanced-patches#272]
### Application

Youtube Music
Youtube 
Maybe more

### Issue

Sadly when telling Google assistant to play a song it does not play on revanced yt/yt music.

Links open in browser not in revanced apps

### Patch

Make the Revanced youtube/youtube music get recognized by google assistant and allow opening links directly in them or t least the possibility to allow sharing a link to the youtube app.

### Motivation

Opening youtube links and clicking urls from the browser is normal all day browsing and those are clearly highly negative points to revanced apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by captainjs** [comment]
It's irrelevant to issue 4339. 
The issue I raised is about "Google Assistant within Android Auto", not Google Assistant with "patched YT/YTMusic".

In fact: YT app is not appearing in AA, that is normal.
YT Music is appearing in AA only after dev mode and "Unknown sources" enabled, that is also normal.

The issue raised here is unrelated:
_Google assistant to play a song it does not play on revanced yt/yt music.
Links open in browser not in revanced apps_
Google Assistant on AA Auto (especially with "hey google play example") did play a music in patched YT Music, within the car, so in the car display, in AA. And there is no link opening in a browser in that context.

Also, just for wasting time, I reiterate that this is absolutely incorrect: "_The only way to fix is to root install those patched apps._"
Because in AA context, Google Assistant was able to open songs in YT Music patched. So there is another way.
