### ISSUE TITLE
feat: Rumble: Block Rumble Ads

### ISSUE THREAD

**Issue by Joscpe** [ReVanced/revanced-patches#2721]
### Feature description

Block or remove video Rumble advertisements for live shows and uploaded content.

### Motivation

Rumble has become annoying with its increased volume of ads, sometimes playing three consecutive advertisements. Especially annoying if you're trying to watch a live stream and you're missing out on content you want to see for something you really do not...

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Are the ads streamed on the server?

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by neo-neo1** [comment]
Would love to be able to patch the adds out of Rumble. They're getting bad
