### ISSUE TITLE
feat: Universal patch that forces using the default system font

### ISSUE THREAD

**Issue by 0-BlackSpectrum-0** [ReVanced/revanced-patches#2726]
### Feature description

A patch for all apps to use system font instead of it own custom font. Mainly for twitter!

### Motivation

Consistency

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
#1895 can be closed in favor of this one.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
