### ISSUE TITLE
feat(YouTube): Hide video view counts

### ISSUE THREAD

**Issue by gjgok** [ReVanced/revanced-patches#2764]
### Feature description

I would like to hide the viewcounts and the high and low ratingcounts in the Youtube home and channel menu and subscribe menu and search results and video playback screen. It would be appreciated if each could be turned off independently, if possible.
(If that is possible with a custom filter, I would like to know how to do that.)

### Motivation

I think this feature would allow people to genuinely enjoy the videos without worrying about the numbers by turning off the number of ratings.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by iLikeCake10** [comment]
You can use video_subtitle in custom filter to hide the views, hashtags, and time of upload in the player, but they can still be seen in the home / search feed.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
