### ISSUE TITLE
feat: LinkedIn ReVanced (without sponsored or suggested posts)

### ISSUE THREAD

**Issue by MidnightRetro** [ReVanced/revanced-patches#277]
### Application

LinkedIn

### Issue

At this point, LinkedIn is almost unusable because of the amount of unrequested crap.
I wish there were a way to remove suggested and sponsored posts from my feed.

### Patch

Patch 1: remove sponsored posts from feed.
Patch 2: remove suggested posts from feed.
Patch 3: feed in reverse chronological order by default (new posts at the top).

### Motivation

I guess there are a lot of people who would appreciate a cleaner, tidier LinkedIn experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Thanks for the feature request!
