### ISSUE TITLE
feat: twitter video downloader

### ISSUE THREAD

**Issue by Jheremy13th** [revanced/revanced-patches#280]
### Type

Functionality

### Issue

I cannot download Twitter video's in the app.

### Feature

Add a patch that allows me to download Twitter video's in the app.

### Motivation

It would be very nice to be able to download Twitter video's in the app.

### Additional context

This is low priority.

**Comment by Lucky-069** [comment]
https://github.com/Dr-TSNG/TwiFucker/pull/45
Don't know much about this. But here's twifucker which I use since I'm on rooted device but it has recently got a download functionality! Perhaps the devs can look at the commits and come up with something! @oSumAtrIX I'm unaware if you can mention other repos to take inspiration from or suggestions! Hope that's okay. If not please remove the comment and tag me!

**Comment by oSumAtrIX** [comment]
Please open a discussion in the revanced-suggestions repository @Lucky-069. Thanks.
