### ISSUE TITLE
bug(YouTube - Spoof app version): `17.33.42` spoof target has the same layout as `17.41.37`

### ISSUE THREAD

**Issue by HattieJosh** [ReVanced/revanced-patches#2808]
### Bug description

Installing the patch to fix the watch history has caused the spoofing of app versions to show the new layout instead of what should be the spoofed layout. The spoof only appears to fix the thumbnails of videos on the home screen and nothing else
![Screenshot_20240302_152247_YouTube](https://github.com/ReVanced/revanced-patches/assets/131213954/1fca3206-f6f3-4d00-9a04-7c70a9f92b91)
![Screenshot_20240302_152236_YouTube](https://github.com/ReVanced/revanced-patches/assets/131213954/cea4e3c8-634d-483c-bad7-ca805f8200c1)
![Screenshot_20240302_151742_YouTube](https://github.com/ReVanced/revanced-patches/assets/131213954/b2b1f31b-3bec-4fcf-a122-f87514daa50b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [x] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Sam101011** [comment]
Like @LisoUseInAIKyrios already mentioned, the old non-rounded UI is gone for good. I liked it a lot and used it 'till its last day, but it's gone.

The difference between the bottom player layouts of 17.33.42 and 17.41.37 are not as big as between the previous and the rounded UI(you can see the difference as shown here:https://github.com/ReVanced/revanced-patches/pull/2776#issuecomment-1971902737)

In order to get the 17.33.42 bottom player layout, first you need to spoof to said version and after the restart, force stop ReVanced and clear app cache(that worked for me at least). 

>Since it's so stubborn to apply the older layout (And the steps above are not explained anywhere else), the spoof version patch could automatically clear the app data when the spoof target is changed.

Imo, only clearing the cache should do the trick, instead of all data(this has done the trick for me like 90% of the time). Or, clearing cache and clearing data could be added as separate options when spoofing app version.

**Comment by Sam101011** [comment]
@LisoUseInAIKyrios for me the opposite thing happened. I spoofed to 17.41.37 and the layout changed, but it got stuck on this layout even when I changed back to 17.33.42(even with force stopping and clearing cache multiple times).

So yes, if you find a way to clear data when applying this patch and auto keep revanced settings, it'd be a good solution.

**Comment by oSumAtrIX** [comment]
The layout structures are sent by the server. Once the servers shut down, the next releases of the clients will remove the deprecated code which essentially would require writing the app from scratch to revert these changes. Unviable.

**Comment by oSumAtrIX** [comment]
Seems the initial issue is invalid.
