### ISSUE TITLE
feat(YouTube): Hide community post in the recommended videos section

### ISSUE THREAD

**Issue by RoonMoonlight** [ReVanced/revanced-patches#2829]
### Feature description

Enabling community post has downside, which also includes community post being displayed on recommended video section.

Would be great if there is option to disable community post in recommended videos section.

### Motivation

Same goes to recommended videos. Sometimes recommended stuffs displaying below includes some controversial stuff (e.g. Some specific person and agency's dispute, etc.) and you feel like it is very uncomfortable and sometimes you think you want to remove it. Also displaying community post displays unrelated topics and it is very annoying all the time and disturbs the experience.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by xgoku1** [comment]
Workaround using Custom Filters. Add the following:

`post_base`
`post_base_wrapper`
`post_attachment_container`
`post_comment_button`
`post_like_dislike`
`post_like_count`
`post_header`
`post_metadata`
`post_author`
`post_time_text`

This blocks Community posts everywhere.

Tested on YT v19.16.39, ReVanced 4.11.0

**Comment by oSumAtrIX** [comment]
Community posts should be blocked everywhere if you use the respective patch already, if not, please open a bug report
