### ISSUE TITLE
feat: Show default Home Screen for users who have Watch History turned off

### ISSUE THREAD

**Issue by flash1230** [ReVanced/revanced-patches#2830]
### Application

YouTube

### Issue

As per current changes by YouTube. The home screen will remain empty if the user has watch history turned off. 
![9s5u19e84iib1](https://github.com/ReVanced/revanced-patches/assets/49901286/dde7e22e-218a-4cc8-a493-0bee159e0702)

### Patch

A patch which could bring back the home screen or give the user YouTube's default home screen (The one which a user sees when he doesn't have an account). 
Or a patch that can be used to hide the home screen (default turned off) would also be helpful. 

### Motivation

The current change by YouTube is annoying to users who have turned off watch history due to privacy concerns or to improve their experience of YouTube's recommendation

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
This might be impossible, due to YT sending the UI components through the server.

**Comment by oSumAtrIX** [comment]
Very likely restricted by the server, although alternative clients such as NewPipe work regardless of the history setting, but they do not have accounts.

**Comment by kazimmt** [comment]
https://www.theverge.com/2023/8/8/23824672/youtube-blank-homepage-watch-history

Enable watch history to fix this issue.

**Comment by kazimmt** [comment]
https://github.com/ReVanced/revanced-patches/issues/2787#issuecomment-1685944545

This may help

**Comment by Psych0somatic** [comment]
“[Temporary Solution](https://github.com/ReVanced/revanced-patches/issues/2830#issuecomment-1686930925)” proposed requires too much user-end tinkering in Google Account, and produces poor results. While pop-up enabling Watch History is purposefully made frictionless, disabling requires a browser login to full Google Account and navigating thru a series of obfuscated menus to locate option to turn off Watch History.

“Turn on watching history?” disclaimer is also concerning:
>When YouTube watch history is on, this data may be saved from any of your signed-in devices.

Building off OP’s 2nd proposed solution, empty homepage should be replaced with default home feed. **View home page in Incognito Mode to see entire home feed return sans recommendations.**

## Solutions to replace blank page with YouTube’s default Home feed

### Quick Fixes
1. Automatically enable “Incognito Mode” on home page OR replace “Your watch history is off” warning with shortcut for user to enable/disable Incognito Mode (on home page only)
    - Note: Incognito Mode on mobile app displays default Home Feed with _all_ its features
2. Incorporate New Pipe’s home feed front-end and adjust layout to ReVanced’s/YouTube’s UI 
    - Limitations: No Shorts, limited results, no categories

### Potential Long-Term Solutions
1. Compartmentalize ReVanced Home tab to always display Incognito (or logged out) feed by emulating that account login status by either automating enabling/disabling of Incognito Mode or using dummy account/spoofing user-agent (if needed) to emulate Incognito/logged out user state.
    - Automate enabling Incognito Mode on Home button touch, disable on search/other tab touch
    - Suppress toast “you’re incognito” and “signed in as [account name]” that flash when switching modes
    - Optional/Advanced: Disable compartmentalized acct state and/or disable Incognito Mode upon user interaction with video, enabling: add to watch list, like, comment, etc without user being prompted to disable Incognito Mode or login.
2. ReVanced pull its own data from YouTube’s default home feed (via API requests, RSS or XML feed, scraping website data, etc) to overcome NewPipe’s limitations and potentially support any of the following: 
    - Explore tab categories: i.e. All, News, Music, Live, Recently Uploaded, Podcasts, etc. (_All_ of which are available on home page while Incognito OR logged out)
    - Shorts
    - Logged-in user interactions
    - More video results

In both solution types, **Option 1** is the easiest to incorporate since it still uses YouTube’s existing architecture and UI without any modifications. Only requires automating account state transition between logged-in and Incognito Mode, while in Home tab.

**Comment by reisxd** [comment]
To be honest, if you're just going to watch incognito videos and not save them, why have an account? Unless you either want to watch videos from people you subscribed or you want to like/comment on a video. I think implementing this would be too much hassle.

**Comment by Psych0somatic** [comment]
> To be honest, if you're just going to watch incognito videos and not save them, why have an account? Unless you either want to watch videos from people you subscribed or you want to like/comment on a video. I think implementing this would be too much hassle.

**Correction:** They’re _not_ “incognito videos,” this is YouTube’s non-personalized default home feed. I already accounted for ways to interact with videos on this feed while logged-in. **Read Long-Term Solution Option 1 in its entirety**. See: “Optional/Advanced” bullet point. Relatively easy fix to enable _full user interactions_ (i.e. add to watch list, like, comment, share).

### The entire point is: 

**the homepage feature, which is the front page of YouTube, is available for _everyone_ except for logged-in users who don’t save their watch history**. **It’s being intentionally hidden to pressure logged-in users to enabling watch history.** It’s unethical to selectively discriminate by allowing home feed for non-logged in & incognito mode users, and viewers with no account whatsoever — but to actively **block it from being used unless you hand over your data** now that YouTube’s been caught red-handed using our watch history to make recommendations this entire time.

Never once has my YouTube account active since 2010, had watch history enabled. It being “too much of a hassle” in your opinion, to implement some automation features in order to restore what’s been taken to punish those who don’t want their watch history sold to 3rd party data brokers and used to send them unbridled “personalized” ads — does not make it so. If it was too much of a hassle to continue this project, blocking ads and sponsors, blocking upselling and accessibility features — then we wouldn’t be here discussing this. The solutions I presented, are practical, and this functionality is important. No one should be punished for partaking in a privacy setting YouTube has offered users since its inception. The explore page, and the various tab categories I listed, is a major feature on this platform, that’s just as useful without personalized recommendations.

Like I said above, this is the front page of YouTube and it shall not be denied to all except for the logged out, the Incognito, and those selling their watch history for free.

This should be a constructive discussion about the tech — not about opinions over whether or not it personally matters to one person or another. Try using the homepage in Incognito Mode before claiming its not worth keeping.

**If we can patch Spotify to have a prettier UI, certainly we can automate Incognito Mode as I outlined, at a minimum, to restore full use of the home feed to all — including retaining user interactions with videos in said feed.**

**Comment by reisxd** [comment]
> They’re not “incognito videos,” this is YouTube’s non-personalized default home feed

Basically the same thing. If you either don't have an account or use incognito, you'll have the same recommendations.

> YouTube’s been caught red-handed using our watch history to make recommendations this entire time.

...what? That's... basically how it works? You watch something related about tech and you get videos about tech. Is that something very wrong? That's what all the platforms basically do. You check something, it recommends it more. 

Also about privacy, you're already using a Google product. Your data is already being stolen. Why should you care about it if Google will steal your data in a way or another? If you care about your privacy, use a privacy-focused client, and not a client thats made by Google themselves.

It's an hassle to implement due to how obfuscated the YouTube client is. To do this, you'd have to modify the request that the client sends to the Innertube client for recommendations. Now, where to find it? It can be anywhere. You would also have to find where it adds the authentication token/user ID and remove it for people who have history disabled. If you want to implement it, you can. This is an open source project and anyone can either request for a feature and implement a feature. Requesting does not mean it'll get added or it'll get added in a short period of time.

**Comment by flash1230** [comment]
> You watch something related about tech and you get videos about tech. Is that something very wrong?

I remember when I had watch history on, I received shitty recommendations after watching things sent by friends on which I was absolutely not interested in. 

> Also about privacy, you're already using a Google product. Your data is already being stolen. Why should you care about it if Google will steal your data in a way or another?

There are ways which me and many others area actively adopting to restrict what Google learns about us and believe it. Since stopping web activity and YT watch history, I haven't seen ads tailored to me in a very long time, in whatever rare occasion I see an ad.

I understand the hassle is not worth it for about 5% of users who will be facing this. That's why I recommended an option to remove the Home tab.

**Comment by reisxd** [comment]
> I remember when I had watch history on, I received shitty recommendations after watching things sent by friends on which I was absolutely not interested in.

Well, that's you watched, and YouTube recommended more of the similar things you have watched. This isn't YouTube's fault, you watched it, the algorithm simply recommended similar videos.

> There are ways which me and many others area actively adopting to restrict what Google learns about us and believe it. Since stopping web activity and YT watch history, I haven't seen ads tailored to me in a very long time, in whatever rare occasion I see an ad.

Your searches and other things you do in other Google products are still collected. Sure, no more targetted ads but your data is still being collected by using Google products.

> I understand the hassle is not worth it for about 5% of users who will be facing this. That's why I recommended an option to remove the Home tab.

I think there's already an open issue for that. But as a workaroud, you can make a shortcut of your subscriptions and disable the home button in ReVanced settings.

**Comment by oSumAtrIX** [comment]
Tracking in https://github.com/ReVanced/revanced-patches/issues/2888
