### ISSUE TITLE
feat(YouTube): Remove video chapters from seekbar

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#2850]
### Feature description

This patch would completely disable video chapters from showing up on the seekbar.

### Motivation

1. Seekbar feels cluttered with too many chapters
2. Chapters have a "feature" where if you try to seek forward or backwards in a chapter it randomly auto-drags you back to the beginning of your current chapter or forward to the beginning of the next one. This is very annoying especially since YouTube has recently been auto-generating chapters for many videos on their platform, so it often feels like you can't even seek properly anymore. _I've created another request for a patch to disable this behavior alone in the past but I closed it in favor of this._

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Aryan-Chauhan** [comment]
Please edit your title to this:

Disable video chapters from showing up on the seekbar.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
