### ISSUE TITLE
feat(YouTube): Show captions using data from NekoCap.com

### ISSUE THREAD

**Issue by lolbinarycat** [ReVanced/revanced-patches#2880]
### Feature description

if the current video doesn't have subtitles in the current language, and the audio has a different language¹ than the current locale, check the NekoCap database and show those instead

for the sake of patching in as little code as possible, perhaps this could be implemented using a proxy server that intercepts subtitle requests

1: if youtube doesn't make this metadata easy to access it should be possible to pull it from the language of the autogenerated captions

### Motivation

youtube removed community captuons a while ago, and this feature would go a decent way towards reimplententing them

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by everypizza1** [comment]
If I'm understanding this right, would this work as a replacement for auto captions on some videos instead of just translation?

**Comment by lolbinarycat** [comment]
i suppose it would, if the database contains such captions.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
