### ISSUE TITLE
feat: (YT Music) Music Sped Up Patch

### ISSUE THREAD

**Issue by aka-0x4C3DD** [ReVanced/revanced-patches#2884]
### Feature description

sped-up versions of music have a different fanbase, which is why you will find a lot of them in a single search in YTM. Now, I use a YTM package in Desktop, that allows the speeding up of YTM music being played (up to 2x) while retaining the original voice. I use that for a lot of songs, and I would like that to be added here too if possible 

![image](https://github.com/ReVanced/revanced-patches/assets/93938476/e360e12b-788b-4318-8e02-4a3f1a0a03eb)

### Motivation

For every song, I don't get sped-up versions. Moreover, in a lot of songs, the voice is changed for the sped-up version, since copyright ig ... so this speed will be a nice addition IMO.
It was there for a brief period when normal videos were being considered as podcasts a few days back.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
