### ISSUE TITLE
feat(X / Twitter): Option to hide UI elements

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches#2898]
### Feature description

Add an option to hide/remove UI elements. Examples:

![IMG_20240319_175729](https://github.com/ReVanced/revanced-patches/assets/32636532/2424f6e5-0410-4145-8255-d3af05a6b570)
![IMG_20240319_175801](https://github.com/ReVanced/revanced-patches/assets/32636532/a487a432-e592-497e-8ab8-b5ffa3d405ea)
![IMG_20240319_175811](https://github.com/ReVanced/revanced-patches/assets/32636532/af830e9e-bcd1-422b-b941-db26171765fe)

### Motivation

This would be helpful for removing the clutter of the app's user interface, with unnecessary elements all over the place. For example, there's a bookmark button to the left of the share button, while the share menu also has a bookmark button in it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
