### ISSUE TITLE
feat (YT) : Provide the user an "already fully opened" description when they open the description to prevent clicking on "...more"

### ISSUE THREAD

**Issue by Aryan-Chauhan** [ReVanced/revanced-patches#2901]
### Feature description

You must've noticed that when we open the description of any video by clicking on the video title, the description opens BUT only partially. We have to press "...more" to fully open the description. So, this requested patch will have the following behaviour:

**Whenever the user taps on the video title, the description will open as usual BUT the only difference is, it will already be "fully open" & not "partially open" like before.**

So, please accept this feature request.

![1711169055519](https://github.com/ReVanced/revanced-patches/assets/91815107/5e9f12f1-04ab-43f8-ac64-b00994c9f26e)

### Motivation

Please tell me, why do people open the description? To read/check out the description, right? That "...more" thing is too small & most of the times, the touch only registers when you tap 2 or 2+ times.

For clicking that small "...more" thing, I've accidentally clicked on links in the description so many times.

So, please implement something that provides the user an "already fully opened" description when they open it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
