### ISSUE TITLE
feat(YouTube): Search in playlist

### ISSUE THREAD

**Issue by RobinRMC** [ReVanced/revanced-patches#2914]
### Feature description

When in a playlist, make the search bar search for videos within the playlist.

### Motivation

This would be very useful for searching in huge playlists.

I always struggle with finding videos in big playlists. I know the video or song I'm looking for is in there somewhere, but it sometimes takes up to 3 minutes to scroll through a playlist.

And to make things worse: the new recommended videos and recommended playlists at the bottom of playlists prevents me from loading the playlist properly. I've given up on searching for videos that are at the bottom of a big playlist, because it's just not doable.

I would really appreciate it if someone were to make a patch for this, and I think I wouldn't be the only one.

_(This feature was already suggested here: https://github.com/ReVanced/revanced-discussions/discussions/139)_

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
