### ISSUE TITLE
feat(YouTube): Playlist autoplay on/off function

### ISSUE THREAD

**Issue by GitOuttaEre** [ReVanced/revanced-patches#2918]
### Feature description

Bring back Autoplay on/off button for playlists.

I haven't seen this mentioned here but many are annoyed YT turned this super useful feature off including me! It was available until about a year or so ago then disappeared 🤬

### Motivation

It would bring back a feature that YT removed for some reason.

I have playlists with meditation tracks and I only want to play one (before bed) and don't need it playing the 100+ following tracks when asleep!....

Instead, I have to find the one I want, search for the individual link then make sure Autoplay is off. Super super irritating and illogical.

Would appreciate if there was a patch or option for this in RV prefs. Thanks!

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
