### ISSUE TITLE
feat: Disable the AV1 codec

### ISSUE THREAD

**Issue by DanGLES3** [ReVanced/revanced-patches#2986]
### Feature description

Seems with the march Play System update Google might have accidentally enabled the AV1 codec on all/some devices (regardless of hardware support) which Youtube will always choose to use thus causing significant battery drain on devices without hardware AV1 decoding, i had to workaround with root by stripping out the AV1 codec from the update 

If possible could a feature be implemented to force disable the AV1 codec to workaround this issue? The affected app is Youtube and likely Youtube Music as well (haven't tested the latter)

### Motivation

The use of the AV1 codec on unsupported devices causes huge strain on the CPU and thus significant battery drain, without an workaround/fix affected users will notice their devices heating up and running slower due to the overhead of decoding AV1 video 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by eldepor** [comment]
My youtube experience is has been literally destroyed. I bought a new phone and since few days ago can't play a single shirt properly. All of them are played 720 when they always been 1080, and now 1080 are dropping 90% of the frames, that means video is playing @ 10 fps or less. I don't know what is happening but everything worked perfectly one week ago. Av1 sucks (at least, some of them), I want all my videos vp9 like before and play smoothly, please fix it or tell us what can we do. Those posts don't solve anything. Thanks!

**Comment by eldepor** [comment]
@LisoUseInAIKyrios thanks for the info

**Comment by eldepor** [comment]
@LisoUseInAIKyrios Hello again.
I found something strange with shorts and this recent (stupid) av1 codec push from google, and the thing is that sometimes (most of the times) when I open a short (not happening with normal videos) with AV1 format @ 1080 60fps, there is a huge frame drop, making the short unplayable (this does not happen in any case with vp9), HOWEVER, if I close and reopen the same short, sometimes there is no frame drop and it plays perfectly, being the same codec and video format. Any idea of why is this happening? Examples and phone info:

![image](https://github.com/ReVanced/revanced-patches/assets/19383172/da105ae3-bbe1-406d-b880-70ba74b1ebf3)
![image](https://github.com/ReVanced/revanced-patches/assets/19383172/e20f6e88-90ec-4b0b-bcba-18ca76adc0e8)
![image](https://github.com/ReVanced/revanced-patches/assets/19383172/ce7fb759-acac-4c09-99a8-06e20bd4adc2)

**Comment by oSumAtrIX** [comment]
The issue occurs on the unpatched app as well. Currently an A/B feature Google pushed.

**Comment by MishaalRahmanGH** [comment]
That's odd: the libdav1d AV1 decoder (which is what [Google rolled out to some users with the March 2024 GPSU](https://www.androidauthority.com/android-update-av1-videos-3420418/)) shouldn't be _that_ bad on the CPU/battery. Or perhaps libdav1d isn't being used at all, but rather the slower/less efficient libgav1 decoder?

**Comment by oSumAtrIX** [comment]
Is this the unpatched app? If not, check if the issue is reproducible on the unpatched app

**Comment by eldepor** [comment]
> Is this the unpatched app? If not, check if the issue is reproducible on the unpatched app

Yep. Exactly the same issue with both patched (19.09.37) and un patched (19.15.35). And by the way, AV1 1080p60fps regular videos are playing just fine, seems the issue is related with shorts only. I also have spoof device dimensions patch (which I asked to implement few months ago) enabled, otherwise I wouldn't be able to unlock shorts higher than 720p on my redmi 10 and higher than 480p on my Lenovo M10 tablet. Also, for your knowledge, some other shorts are still playing vp9, some updates from 720p format to 1080p after the first seconds, some others stay stuck at 720p, etc.

![Screenshot_2024-04-18-12-11-49-987_app revanced android youtube~01](https://github.com/ReVanced/revanced-patches/assets/19383172/e21896b3-41be-4650-8cf4-8920800f1ec7)

**Comment by oSumAtrIX** [comment]
Are you using Google Services or MicroG GmsCore when using the unpatched app?

**Comment by eldepor** [comment]
> > I also have spoof device dimensions patch (which I asked to implement few months ago) enabled, otherwise I wouldn't be able to unlock shorts higher than 720p on my redmi 10 and higher than 480p on my Lenovo M10 tablet.
> 
> Spoof device dimensions can have problems. If it unlocks 1080p but playback is dropping frames, then that is a side effect and the patch should be turned off.

What is dropping frames is this new stupid update Google pushed. I have been playing shorts 1080p60fps perfectly (thats why I asked for the patch) until now. Now I have to condemn myself to play 720p shorts with a phone I just bought 3 months ago (that it's perfectly able to play those "unplayable" shorts) just because #€@#&+= Google implement these stupid features? This is beyond a joke.

**Comment by eldepor** [comment]
> Are you using Google Services or MicroG GmsCore when using the unpatched app?

I just see one yt app registered on GmsCore, which corresponds to the patched one, so I assume the unpatched one is using Google Play Services.

BTW, Ive been using microg v0.2.24.220220 until the last revanced patches that forced me to install GmsCore, I don't know if this is also related to the issue. Right now I have [this](https://github.com/ReVanced/GmsCore/releases/download/v0.3.1.4.240913/app.revanced.android.gms-240913008-hw-signed.apk) one installed.

**Comment by eldepor** [comment]
> > Now just because #€@#&+= Google implement these stupid features? This is beyond a joke.
> 
> Google did not implement the spoof dimensions patch, nor is it their fault that spoofing breaks the app. All forms of spoofing can break at any moment for a multitude of different reasons.

Please read my message again.

**Comment by eldepor** [comment]
> There was a patch that allowed disabling VP9. Please open an issue to return the feature so we can track it. It was removed previously due to redundancy.

Correct me if I´m wrong but wouldn't the objective be to force VP9 instead of disabling it?, because it appears here that Google its already "disabling" VP9 by forcing AV1. Thanks.
