### ISSUE TITLE
feat: (G-MAIL) Dark Theme Patch for Android 9.0 & Below

### ISSUE THREAD

**Issue by Dusk-Golem** [ReVanced/revanced-patches#3]
### Feature description

Hi there, please make a patch to enable Dark Theme on Gmail app on Android 9.0 (and below if possible) since Google being a B.I.T.C.H, refuses to do so OFFICIALLY.

### Motivation

This is literally the only Google App (or any app for that matter) on my Galaxy A8 2018 which does not have a dark mode. I have tried looking everywhere for a possible resolution to this like the LSPosed module "Gmail Dark Theme Enabler" and some substratum themes but the problem with them is, the module does try to hook into the gmail app but when I go to gmail app general setting to change the theme, the theme changing option appears for a fraction of a second and then disappears rendering the module useless (for me at least) and the chances for finding up to date substratum themes is absolutely zero now. I don't know what else I can do since installing a custom rom or buying a new phone is out of question for me.

Also, I don't know how many people are still on Android 9 but I am sure that no one will be against this. Also, I will not be changing my phone for the next 2 years (broke and looking for a job in a foreigh country) so I'll really really appreciate it if you guys can make such a patch (a future proof version will be awesome but not possible I assume judging by how frequently google updates the app).

I hope you guys can make it happen. Best regards.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Dusk-Golem** [comment]
BUMP.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
