### ISSUE TITLE
feat: (Instagram): Add Patches `Remove sharing tracker parameter` and `Sanitize sharing links`

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#3020]
### Feature description

Both patches same like YT revanced has.
Port `Sanitize sharing link` and `remove sharing tracker parameter` into [Instagram](https://play.google.com/store/apps/details?id=com.instagram.android) app

### Motivation

Who want to be tracked? I can say NONE.
Yes, because MetaApps just make tracking links to add/gain revenue and or for promote the links/ads. 
The patches also make simplified sharing links.

**To reproduce:**
1. Open any Instagram post or reels
2. Tap `Send` icon (paperplane icon under post or reels)
3. Select the way you share the link, either share to WhatsApp or just copy the link
4. See there is a embedded tracker in the end of the link
5. For the example, this is result of copied link: `https://www.instagram.com/reel/C5qgBP4rXDK/?igsh=ZXZidjV2aHp0bGM0`

We can open the link without `?igsh=ZXZidjV2aHp0bGM0`

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
