### ISSUE TITLE
feat: (Youtube/Downloads)Add ability to open external download app's downloads viewer

### ISSUE THREAD

**Issue by Tanmandal** [ReVanced/revanced-patches#3033]
### Feature description

Please add ability to overwrite the downloads button that opens in app downloads to open external app's downloads viewer. Ensure to not only allow package name but also activity name so that desired activity of require app could be opened.
![Screenshot_2024-04-18-01-57-35-203-edit_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/93572359/1c6e40c0-9ddc-4c5d-8689-cb8a0cd7cb46)
Actually I want this downloads button to open
![Screenshot_2024-04-18-01-58-00-218_com junkfood seal](https://github.com/ReVanced/revanced-patches/assets/93572359/1d8627cf-2fd6-4df9-864c-1d3668ecbc00)

### Motivation

This feature would make the downloads button link to external downloader's viewer and thus enable downloaded videos be accessible from the moded app itself , making the downloading and watching experience more inline with the actual app.

### Acknowledgements

- [x] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
