### ISSUE TITLE
feat: (YT Music) Choose folder for device files 

### ISSUE THREAD

**Issue by JimB99** [ReVanced/revanced-patches#3038]
### Feature description

Make it possible to choose or filter a specifc folder for the device files for local downloaded music.

### Motivation

Right now YT Music looks at all audio files on the phone and puts them todether. That means that even for example WhatsApp audio is shown and played when doing shuffle. Since it is likely/easy that the actual songs are in a separate folder, if one could choose to filter the songs by folder, it would make it a lot easier to play local device files in the app.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
