### ISSUE TITLE
feat: TikTok: Remove TikTok Shop Tab

### ISSUE THREAD

**Issue by Konix26** [ReVanced/revanced-patches#3089]
### Application
TikTok v32.5.3
(Unsure of which version this shop tab appears in first)

### Issue
TikTok's shop tab is in the way, and I among others have no intention of treating this app like it's Etsy.

### Patch
Add option under ReVanced Settings Menu to Remove TikTok Shop tab entirely. This function could completely remove that tab.

![Screenshot_20240425_065513_TikTok](https://github.com/ReVanced/revanced-patches/assets/29917813/d66eec12-7ad6-45ae-97db-a72fa780f8ff)

### Why I think this should be implemented
The shop kind of strays from the original intent of the platform. This is a video app, not etsy.

### Use Case
- No interest in buying anything
- Shop Tab is in the way

### Benefits
- No swiping into a shop when moving between FYP and Following Tabs

### Importance
- Tiktok has ads removal but shop defeats the purpose.
- TikTok is a video viewing platform, not etsy

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
