### ISSUE TITLE
feat: youtube - hide suggested video overlay

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#3114]
### Feature description

Hide this new "suggested video" to watch next overlay that shows up when you finish a video

![Screenshot_2023-10-08-05-54-40-356-edit_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/107653639/c4d694f7-74af-4da7-89f6-6f957fac8fb6)

### Motivation

It's pretty useless, all videos it suggests either I've already watched or simply am not interested in at all

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GreatestFool** [comment]
I'm pretty sure this was a patch previously, that got removed somewhere after 18.23.x.

And to point out something else, it not only doesn't give good suggestions anyway, but makes it more annoying to exit fullscreen using the UI buttons and when minimizing the video, it'll show the thumbnail of the suggested video instead of the actual video. Below is an example of a random video. The top one is the actual video, while the bottom one is the same video, but displaying both the name and thumbnail of the suggested video instead of the actual video.

![image](https://github.com/ReVanced/revanced-patches/assets/3003484/67a8d698-8116-475e-b881-ad7eae7b84b7)

Though, for sake of clarity, I think `Hide endscreen cards` patch should have its description changed. The way it's currently worded makes it somewhat more vague than it should be, regarding whether it means YouTube's suggested videos or a YouTuber's selection of suggested videos. Perhaps a bit pedantic, and so long as another path is made that is named something like "Hide suggested video overlay" it'll probably be enough of a difference to let help the user interpret the use-cases for each. Though more specificity would be nice.

**Comment by oSumAtrIX** [comment]
> Hide suggested video overlay

Thats what the new patch in dev is currently staged with.
