### ISSUE TITLE
Patches for Rakuten Viber

### ISSUE THREAD

**Issue by PhoenixFossGR** [ReVanced/revanced-patches#3116]
### Feature description

The app Viber is extremely popular in Greece and other countries. The app however, is full of trackers, ads and more. Is it possible for the creation of patches for Viber, that remove telemetry, ads, spam, communities and trackers?

### Motivation

Viber is really popular and is being used by some to spread phishing and malware via communities and via ads. Viber also says it’s very private and secure, but it filled with trackers. It would be amazing if we could stop this to protect our family and friends who aren’t very aware of technology and cybersecurity.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please add screenshots of the ads, trackers and telemetry

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
