### ISSUE TITLE
feat: Universal Patch to force an app to support landscape mode on tablets

### ISSUE THREAD

**Issue by Bingo90** [ReVanced/revanced-patches#3196]
### Feature description

This patch would allow apps that have landscape mode disabled to be rotated into landscape mode.

### Motivation

Some apps that are primarily made for phones don't natively support landscape mode. Samsung Tablets have a feature to override this, but some other manufacturers (for example, OnePlus) don't. A patch like this would make using apps that don't support this natively more convenient to use on tablets.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
