### ISSUE TITLE
feat: (pl.neptis.yanosik.mobi.android) - ad blocking 

### ISSUE THREAD

**Issue by Roki100** [ReVanced/revanced-patches#3198]
### Feature description

Yanosik is a polish app for alerting stuff that happens on the road, including speed traps, it also acts as navigation, however it is filled with a ton of ads, and it wouldn't be a big problem if the ads weren't blasting on your speakers so loud and they didn't charge monthly sub for just ad-free experience

so a patch just allowing you to switch the "disable ads" setting in app settings without paying for that would be great 

### Motivation

Because no one deserves to hear ads full blasting on their speakers at random moments, and the app is very very popular among drivers in Poland 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by Roki100** [comment]
lol
