### ISSUE TITLE
bug(YouTube - Spoof client): Playback speed flyout menu is missing

### ISSUE THREAD

**Issue by MoTem** [ReVanced/revanced-patches#3203]
### Bug description

Playback speed button no longer shows up in the flyout menu. There is no way to change it currently other than by setting it in Revanced - Video - Default Playback Speed.

This issue appeared after updating from 4.7 to 4.8. No changes in default patches, and cache was cleared. The option to show playback speed was enabled and disabled too. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by MoTem** [comment]
Yes I am aware of that. It is not appearing in the flyout menu, even when it is enabled. I am not the only one facing this issue, a lot of users mentioned this on reddit too.

**Comment by gui-lherme** [comment]
I'm experiencing this as well. When I turn `off` the `client spoof` patch, the playback speed flyout returns to **normal**. I'm using a **brand account**.

**Comment by oSumAtrIX** [comment]
This is one of the limitations we can work around with with #3197. I am not sure why the player request causes these issues because the player only returns player data and not layout instructions. What can be done is set the response type to json, check if it contains anything interesting in this regard. If it does not, that means we don't only touch /player requests. Perhaps YouTube is also caching objects so when we modify them with a hook, they may be used in a other request. Perhaps after the request is done, we could reset the fields we change and see if that makes a difference

**Comment by oSumAtrIX** [comment]
Moving to https://github.com/ReVanced/revanced-patches/issues/3208
