### ISSUE TITLE
feat: Return old YouTube Casting behavior

### ISSUE THREAD

**Issue by AstonJay** [ReVanced/revanced-patches#3261]
### Feature description

I cannot find a screenshot of how it looked previously. However, when I connected the YouTube app on my phone to the YouTube app on my PS4/5 and I wanted to cast a video to the PS, you would usually tap on the video you wanted to watch and on your phone and it would bring up a rectangular dialog box with 2 options; Play Now & Add to Queue. (With a Play symbol and Plus symbol in the middle of each button respectively) I hope someone can remember how it looked.

### Motivation

This was changed to where if you click on a video (even accidentally) it would immediately just play that video on the PS without confirmation if that is what you wanted to do. This would happen even if you were already watching a video. 
You now have to press on the 3 dots to bring up the options menu in order to "Add to Queue", which is annoying as heck. If there is a way to bring back the old dialog box it would be amazing. 

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
