### ISSUE TITLE
feat: Remove ads and featured posts from Kleinanzeigen 

### ISSUE THREAD

**Issue by C0ntroller** [ReVanced/revanced-patches#329]
### Application

Kleinanzeigen (formerly known as eBay Kleinanzeigen) an app for searching/selling stuff. Comparable to Facebook marketplace. 

com.ebay.kleinanzeigen

### Issue

When searching for something, every 2–3 posts, an ad is shown. Also, there are featured posts where people can pay, so their post is shown on top. 

### Patch

Removing the ads and featured posts. 

### Motivation

It is astonishing how many ads are shown there. The app is barely usable now. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
