### ISSUE TITLE
bug: Twitch patching fails with Recommended Version (17.1.0)

### ISSUE THREAD

**Issue by MRMIdAS** [ReVanced/revanced-patches#3313]
### Bug description

Attempting to patch Twitch with the new patches. Patching fails with LOTS of errors, Assuming it's a version mismatch despite using recommended version.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by KobeW50** [comment]
> `16.9.1` is the recommended version, use that.

The manager currently suggests `17.1.0` because only the settings patch is constrained to `16.9.1` while all other Twitch patches are constrained to `17.1.0`

All patches work on `16.9.1`. Should I PR to add `16.9.1` as a supported version for all the patches?

![SmartSelect_20231120_221531_Chrome.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/29683381-4307-4cb5-a372-b4c81cbb71a9)

**Comment by oSumAtrIX** [comment]
Yes, that version works for all patches
