### ISSUE TITLE
feat: Apply Custom Playback speed to Youtube shorts

### ISSUE THREAD

**Issue by Akv2021** [ReVanced/revanced-patches#3421]
### Feature description

- Similar to normal videos in Youtube where we have option to choose default Playback speed, there should also be a control to apply videos playback speed for Shorts.
- The MVP will be apply the same default playback speed to shorts which is applicable to full length videos. There would be an option in app settings to toggle this behaviour. 
- Better UX will be to introduce a new option in shorts settings menu to change playback speed. This selection should also pertain (ie remain applicable unless changed similar to existing default playback speed option) 

### Motivation

- The same reasons for custom playback speed in normal videos are applicable here. i.e. for speeding shorts up/down.
- Validated that YouTube supports sped up shorts. To replicate can use chrome playback speed extension on web & increase speed on shorts. Works as expected without any playback issues.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
> The same reasons for custom playback speed in normal videos are applicable here. i.e. for speeding shorts up/down.

The same reason doesn't apply to shorts. Shorts are short, changing the speed doesn't sound logical to me.

**Comment by Akv2021** [comment]
- I agree that shorts are upper bound in length and the gains in video playback duration are not the key motivation. The specific advantage I want to highlight is that in general we can comfortably listen to faster content than the creators can speak/ present naturally. So, on most of the channels (videos & shorts) I'd personally switch to 1.25/1.5 to make the gaps/ pauses in speech less noticeable. Also when switching from all videos playing at a higher speed to the non sped up shorts is a noticeable difference. Applying the same playback speed makes the experience uniform. Hope, this clears up the thought process behind feature request.
- Yeah, added it for context. Didn't mean it to be another motivation. You can replicate the UX with extension & decide if it makes a difference.

**Comment by oSumAtrIX** [comment]
Shorts are already short enough. They dont need to be sped up like long form content.

**Comment by eldepor** [comment]
I can give you a motivation to implement the patch. There's an issue with some devices like Xiaomi Pad 6, which have some sort of incompatibility with revanced (with play store YouTube works perfectly). These devices (miui 14 android 13) have a setting to change screen refresh rate, you can set it to Dynamic, 60hz, 90hz or 144hz.
If you set it other than exactly 60hz (dynamic, 90 or 144), when a 60fps video starts to play, the refresh rate drops to 30, so you are viewing a 60fps source in 30fps. That's bad. 
To avoid this, I found a workaround on a Russian forum: set default playback speed to 1.01, which is unnoticeable and boom, now the refresh rate stays @ 60hz and can watch 60fps videos in 60fps. 

Speeds with 0.5 increments (2.0x, 1.5x, 2.5, 0.5x etc) have this problem (well, maybe the problem is something else), but everything between 0.01~0.49 / 0.51~0.99 "solves" this issue. 
This is the reason I would like to set 1.01 speed to my shorts too, so I can watch them @60fps instead of 30.

Maybe the problem can be solved in another way, internally in the code or something, and can open an issue specifically for it, because as I said, I don't have this issue with play store official YT, but at the moment I haven't found another better solution than this trick. Obviously, running my tablet permanently on 60hz or changing refresh rate settings every time I use YouTube is not a viable option. Thanks!

**Comment by eldepor** [comment]
> > There's an issue with some devices like Xiaomi Pad 6
> 
> That needs to be resolved with Xiaomi and not us working around their issue with playback speed.

But it doesn't happen with official YouTube. Xiaomi will tell me to update my device to android 14 blabla, which I won't.

**Comment by eldepor** [comment]
No luck. Still dropping to 30hz. I patched the app with only Gsmcore support patch, the only patch I can't uncheck, otherwise I'm not able to install revanced because unpatched YT is installed as system app and I'm still in warranty. The only "fix" I can find is adding shorts speed settings, to set 1.01x as default.

**Comment by oSumAtrIX** [comment]
In that case it's not an issue with ReVanced and conclusively something YouTube x Xiaomi will have to figure out

**Comment by eldepor** [comment]
> In that case it's not an issue with ReVanced and conclusively something YouTube x Xiaomi will have to figure out

Sorry but it is, there's no issue with unpatched official YouTube.

**Comment by eldepor** [comment]
I guess https://github.com/ReVanced/revanced-patches/pull/4153 help with this issue

**Comment by Julmik647** [comment]
There are some shorts like [this one](https://youtu.be/KtDuQnqXSsk) that tell you to change playback speed, so adding playback speed to shorts will allow to do this without using normal video player.
