### ISSUE TITLE
bug: Sync for Reddit crashes with /s/ links patch

### ISSUE THREAD

**Issue by burakdede0** [ReVanced/revanced-patches#3430]
### Bug description

- Patched the latest version of Sync for Reddit with official ReVanced patches and it crashes on launch.

### Error logs

```shell
07-11 16:40:13.866 E/AndroidRuntime(1199): java.lang.NoSuchMethodError: No static method patchSetAccessToken(Ljava/lang/String;)V in class Lapp/revanced/integrations/syncforreddit/FixSLinksPatch; or its super classes (declaration of 'app.revanced.integrations.syncforreddit.FixSLinksPatch' appears in /data/app/~~IBA2sb0nQIc94E1NEirZrA==/com.laurencedawson.reddit_sync-nvD4wnWCI6XCUCdP0BGOsw==/base.apk)
```

### Solution

Patching and launching without /s/ links fix patch works fine.

### Additional context

Tried clean installing and 2 different devices running Android 14.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The method is present:
https://github.com/ReVanced/revanced-integrations/blob/main/app/src/main/java/app/revanced/integrations/syncforreddit/FixSLinksPatch.java#L21

Your integrations are outdated, likely due to incorrect cache. Delete ReVanced Manager data to update it correctly. For support, move to one of our links at https://revanced.app.

**Comment by burakdede0** [comment]
Thanks. That fixed the issue for me.
