### ISSUE TITLE
feat (SwissId): Pass Integrity Check

### ISSUE THREAD

**Issue by KillTrot** [ReVanced/revanced-patches#3477]
### Feature description

package-name: com.swisssign.swissid.mobile

At the moment it is not possible to use this app with a custom rom installed, as the app required that you pass all [Integrity Checks](https://developer.android.com/google/play/integrity/overview)
It would be nice to have a patch that disabled this integrity check to allow the usage of SwissId on custom roms.

### Motivation

The app is currently unusable for many users, for example of custom ROMS like LineageOS or GrapheneOS
With a custom patch it should be possible to disable those limitations and allow the usage of the app for users of custom ROMS

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Integrity checks from Google Play are completely beyond ReVanced

**Comment by erikk333** [comment]
As long as no patch is available:
1. Root
2. Install last available  play integrity fix by chiteroman

**Comment by KillTrot** [comment]
I tried this and for me it did not work, but maybe I did something wrong

Also the pull request is merged, so I guess this could be closed?

**Comment by LeVraiRoiDHyrule** [comment]
Hi.
The bank I am using, Yuh, recently implemented Play Integrity checks (I am not sure at which level). As I am using MicroG, I can't have full play integrity.
I am wondering if the fix implemented here for SwissID can also be applied to other apps like Yuh.

Thanks in advance for any answer, have a nice day

**Comment by KillTrot** [comment]
As far as I know MicroG alone should not influence the Play Integrity Checks, but you're most likely rooted as well?

**Comment by LeVraiRoiDHyrule** [comment]
Thanks a lot for your answer.

I am rooted yes, but I am using KernelsSU instead of Magisk. I don't think that is the problem because I had apps that detects root with Magisk but no longer detect since I switched to KernelSU.

The Yuh apps fails with the following error since a few days:
![Image](https://github.com/user-attachments/assets/ef4ca842-34c3-4bea-9e23-c5879c4f9494)

My play integrity status is the following:
![Image](https://github.com/user-attachments/assets/59b17f94-771e-4de9-b58b-0a1d658ed58e)
It explains why Yuh is not working. But I don't understand what the problem could be.

I have the following KernelSU modules:
- AlterInstaller v2
- microg installer reborn v1
- Open Webview v2.5.2
- Play Integrity Fix by chiteroman v19
- Zygisk Next v1.2.8
- Zygisk Lsposed v1.10.1
- Shamiko v1.2.1

I have real play store, installed from an apk and as a system app by microg installer. 

Recently, I have updated Play Integrity Fix from v18 to v19. At that moment, I had "Basic Integrity" level working for Play Integrity. After updating PIF, and trying its "action" (which apparently consists in downloading and installing a pif.json file), it falled back to "No integrity" level that I have here. But Yuh began to fail before that, so I don't that is the problem. I think that Yuh indeed raises the required Play Integrity level, but I don't know if they expect "Device" or "Strong". 

Sorry for all that data. Would you have an idea of what could be wrong?

Thanks in advance for any answer and have a nice day.

**Comment by KillTrot** [comment]
I am almost sure that you need at least basic integrity for Yuh to work. I honestly would try to achieve that first before trying to patch the APK

**Comment by LeVraiRoiDHyrule** [comment]
> I am almost sure that you need at least basic integrity for Yuh to work. I honestly would try to achieve that first before trying to patch the APK

I see. I will try that then. But I am having a very hard time trying to get that to pass, everyone is saying everything and its contrary on the subject of Play Integrity. Would you know if there is a reference and up to date tutorial on this? All I can find are telegram messages and outdated obscure github repositories.

I am a microg user. As I understood it, I need to have real play store for integrity, so I have that too. But now, after reinstalling everything integrity related, I am in a state where play store is perfectly installed and working, but apps like Play Integrity checker says "PLAY_STORE_NOT_FOUND". I am stuck on this and can't find any start of a solution. Would you have an idea on this or somewhere I can ask? Thanks in advance for any answer and sorry if this is out of the original topic.

**Comment by KillTrot** [comment]
I personally use Magisk, not KernelSU, so it's difficult for me to give reliable information. You already seem to do what I would do, using PlayIntegrityFix and running the action of it, so I'm not sure how to do it:/

As Google and app vendors are cracking down on ways to use apps with root or custom rooms, it probably won't take long until the only possibility to use those apps is to have a unrooted, bootloader locked phone...
Aka you need a second phone if you want your main phone to be rooted.

Everyone with root / custom rom is struggling more and more with it.

Maybe the best course of action you can take for now is trying if an old version of Yuh is working (if they don't lock old versions out). You can download old versions using Aurora Store, as I don't find the APKs online. Don't forget to disable auto updates though.

**Comment by LeVraiRoiDHyrule** [comment]
Hi, thanks for your answer.
Using old version does not work. They implemented Play Integrity checks for more than 6 months now, without it blocking access to the application. Then they enabled check blocking access server side, on all of the versions.
I have tried with various installations of microG + Play store, and also with GrapheneOS' Sandboxed google play services. It should be working as Yuh devs worked with GrapheneOS to get it to work, but I didn't succeed.
At that point, it is simpler to just change bank for one that does not use Play Integrity.
