### ISSUE TITLE
feat: (Youtube) zoom video between standard and fill the screen

### ISSUE THREAD

**Issue by carmichaell** [ReVanced/revanced-patches#355]
### Application

Youtube

### Issue

Youtube video cannot be zoom in between original aspect ratio and fill the screen(it always magnetically zoom back to standard or fill the screen)

### Patch

Allow youtube video zooming between original aspect ratio and fill the screen

### Motivation

It will extremely useful for foldable to zoom slightly to reduce the black bar and also useful for regular phone if user wants to zoom in before the punch hole or just want slightly bigger viewing area without sacrificing too much content.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by Frontline11** [comment]
I understand Osum, but this function that I asked for would be fundamental
for YouTube to advance, because we activate the key and the screen is
completely filled when we rotate the cell phone screen and we no longer
need to pinch with our fingers to fill it, that is more practical and many
people will like it

Em sáb., 1 de jun. de 2024 18:05, oSumAtrIX ***@***.***>
escreveu:
