### ISSUE TITLE
feat(YT Music): Seamless  Switch audio-video/video-audio

### ISSUE THREAD

**Issue by YashjitPal** [ReVanced/revanced-patches#386]
### Application

Youtube Music/ YT Music

### Issue

I can't change audio to video or video to audio in the mini player as it shows its a premium feature.

### Patch

![Screenshot_2023-08-30-19-31-01-01_261cc69e159889934ed6f60143ee2161](https://github.com/ReVanced/revanced-patches/assets/80625891/78920382-220f-4777-b636-fb4fd7703aaf)
![Screenshot_2023-08-30-19-31-50-28_261cc69e159889934ed6f60143ee2161](https://github.com/ReVanced/revanced-patches/assets/80625891/faf03c06-a194-4e72-ac48-e040f7af10bd)
Whenever I try to change any song's video to audio or audio to video, it shows that the feature is called "Seamless Switch between audio and video" and it's available only in premium. So I would like to patch this.

### Motivation

YouTube music is left incomplete in being totally premium without the feature. And it is also very useful as sometimes we dont have enough data to run the video and to reach the song version of the same song at the same time lapse. So overall this feature is very useful to be patched. 

If you feel that there's something incomplete in this section, then please kindly explain me what I actually have to write in this portion. 

Thank You.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
