### ISSUE TITLE
feat: Xpatch Universal Patch

### ISSUE THREAD

**Issue by owen-the-kid** [ReVanced/revanced-patches#3911]
### Feature description

based off the idea of <a src=https://github.com/WindySha/Xpatch>Xpatch</a> and might be usefull but does mean that the manager needs to manage these xposed modules.
the patch can be based off xpatch like lspatch did but without the need of shizuku.

### Motivation

It could work as replacement to the now discontinued Lspatch and would also work better because of shizuku having issues on later versions of android

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by kitadai31** [comment]
FYI, Shizuku is not a requirement to use LSPatch.
Shizuku is only used to install the patched APK directly after patching a APK.
Everything else will work without Shizuku.

**Comment by oSumAtrIX** [comment]
LSPatch works as an internal memory hook by adding the libraries for hooking into the APK and make the app process load the library. The reason LSPatch does not work, is because those native hooking libraries don't. ReVanced could do what LSPosed did, but it would effectively be limited by the libraries compatibility. Alternatively there's hook frameworks like pine actively maintained.
