### ISSUE TITLE
feat(YouTube): Always route channel icon press to the channel homepage

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#418]
### Issue

When a video in a feed is from a channel that is currently livestreaming/live, pressing the channel icon will take you directly to the livestream instead of to the channel page.

![Screenshot_20230823_010116](https://github.com/ReVanced/revanced-patches/assets/84587632/1496fe3b-a214-467f-b4c3-bccb14bf5006)

### Patch

Changes the behavior of the channel icon button so that it always routes to the channel page.

### Motivation

It is annoying that the livestream starts. If I'm in middle of a video it is disruptive.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
