### ISSUE TITLE
feat (YouTube): patch that lets me scrobble songs on last.fm if the song is categorized as music

### ISSUE THREAD

**Issue by IoIxD** [ReVanced/revanced-patches#425]
### Application

YouTube

### Issue

I want to be able to use last.fm again, but I can't get myself to use YouTube Music, which is a problem because the music I like (Japanese Jazz Fusion, City Pop) isn't on mainstream platforms like Spotify, meaning that I have to rely on people who upload it to YouTube.

### Patch

I'd like to see a patch for YouTube that lets me log into last.fm and scrobble videos categorized as music.

### Motivation

There are other people who listen to j-jazz that might benefit from this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
