### ISSUE TITLE
feat(spotify): add play next in queue option

### ISSUE THREAD

**Issue by D3SOX** [ReVanced/revanced-patches#429]
### Application

Spotify

### Issue

Spotify doesn't have an option to add a song to the beginning of the queue, just to the end

### Patch

Maybe the three-dots song menu could be patched to add a button

### Motivation

Sometimes I'm listening to something and I already prepared a queue
Then I wanna listen to some different songs next, so I have to first queue them all up and then move them to the top which is a really tedious process.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

### Additional context

Maybe looking at implementation for the Spicetify extension that does exactly that could help
https://github.com/daksh2k/Spicetify-stuff/blob/master/Extensions/playNext.js

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by D3SOX** [comment]
I understand, but I am not sure if closing it is a good idea for discoverability because not many people search for closed issues. I think a label would be better suited but in the end it's your decision .-.
