### ISSUE TITLE
feat (YouTube): allow changing per channel notifications despite having popup notifications disabled

### ISSUE THREAD

**Issue by linuzzx** [ReVanced/revanced-patches#436]
### Application

YouTube

### Issue

When you don't want popup notifications but still notifications in the app, you disable notifications. In doing that, YouTube prevents you from changing any per channel notification settings, which is annoying.  
  
You can't use notification blockers either since they would also block the media player which auto stops every video you play, making it useless.

### Patch

Either:
- let the user change these settings
- spoof notification access

### Motivation

Not everyone wants these annoying video popups, especially when you have a lot of channels subscribed. But you should still be able to keep on track with all videos that are uploaded by these channels, without being feature blocked.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
