### ISSUE TITLE
feat(TikTok): Set minimum/maxiumum length for videos in feed

### ISSUE THREAD

**Issue by aaronneallucas** [ReVanced/revanced-patches#452]
### Application

TikTok

### Issue

TikTok allows users to film and share videos up to 10 minutes in length, which is pretty excessive for an app that is supposed to be "short-form" videos.

### Patch

Patch which allows people to remove videos that are under or over a certain length; it would be held in the ReVanced settings on TikTok. It would function similarly  to the one that removes videos from feeds based on like count and view count.

### Motivation

Very significant advantage for those looking to have more control over the content in their feed. Many users could set maximum lengths so far down that the experience could be like scrolling through Vine again. Many other users many not like the fact of how short the videos are and could set a minimum length for their videos as well. Either way, I could see this being a great and easy to implement feature for ReVanced.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
