### ISSUE TITLE
feat(Twitch): add hide-link-warning patch

### ISSUE THREAD

**Issue by girshcatt** [ReVanced/revanced-patches#472]
### Application

Twitch

### Issue

When you tap on link in twitch chat you get warning like this
![Screenshot_20230813_120720_PurpleTV](https://github.com/ReVanced/revanced-patches/assets/110785596/f95a656b-3403-4145-b620-a5482338f9c7)
Add function to hide this warning

### Patch

Add Disable Browser link disclaimer switch in settings (defalut off)

### Motivation

This will bring more comfort in Twitch using, this feature will help in situations when for example streamer gives you link in chat and say who first will open it will get boosty subscription

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
