### ISSUE TITLE
feat: Make the screen black in Photography Pro after a picture has been taken

### ISSUE THREAD

**Issue by IsakTheHacker** [ReVanced/revanced-patches#48]
### Feature description

The camera app on Sony phones (Photography Pro, com.sonymobile.photopro) doesn't provide any feedback when a photo is taken which can lead to missing the shot. A patch that adds a black screen for quarter a second would solve this.

### Motivation

This patch would affect many people and fix an issue that has been present for a long time

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
