### ISSUE TITLE
feat: Bypass battery check in Sony's Photography Pro

### ISSUE THREAD

**Issue by IsakTheHacker** [ReVanced/revanced-patches#49]
### Feature description

The camera app on sony phones: Photography Pro (com.sonymobile.photopro) has an annoying battery check that prevents you from taking any pictures if the phone has 5% battery or less. It would be awesome to patch it so that it always works regardless of the battery level

### Motivation

This patch would affect many people since this is the standard camera app on all recent Sony phones

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
