### ISSUE TITLE
feat:  Make YouTube Music able to play offline downloaded songs.

### ISSUE THREAD

**Issue by adnansid99** [ReVanced/revanced-patches#507]
### Application

YouTube Music

### Issue

Youtube Music is not automatic downloading my Liked playlist. And if I download the songs manually, I am not able to play that. It's showing Payment required.

![received_1749918925469103](https://github.com/ReVanced/revanced-patches/assets/60623435/b0208034-4f03-41e9-ae16-d8ab55443df9)

### Patch

Can you please make patch for this?

### Motivation

People can listen music offline anywhere. :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by tim-gromeyer** [comment]
> @adnansid99 You can use external downloader, e.g [YTDLnis](https://github.com/deniscerri/ytdlnis) And premium features like that is server-sided feature which is not unlocked wiyhout pay.

While using an external downloader like YTDLnis is a possible solution, it does not provide the most seamless user experience. Here's why integrating this feature directly into the app could be more beneficial:

1. **Auto-download**: This feature would save users' time and effort as they wouldn't need to manually download songs.
2. **Same app**: Users would benefit from having all features in one place, eliminating the need to switch between different apps.
3. **Removing disliked titles**: An integrated feature could automatically remove disliked titles, keeping playlists clean and tailored to users' tastes.
4. **Privacy of 'Liked Titles'**: Downloading 'Liked Titles' is challenging due to privacy settings. An integrated feature could handle this seamlessly.
5. **Playlist Limitations**: The current 50-song limit when adding to a new playlist makes it cumbersome to download all titles. An in-app solution could bypass such restrictions, making the process smoother.

**Comment by sayyid5416** [comment]
@tim-gromeyer most probably it is a server-side feature, so it's not possible to implement this feature. Although I've not researched about this, just a guess on the basis of its behavior.

**Comment by tim-gromeyer** [comment]
Thats very unfortunate, since this would make thing so much easier.... but I don't understand, how downloading can be a server-side feature. It's literally just getting a file from a server. Isnt it possible, to embed a YouTube Downloader and wrinting some code which manages the downloads?

**Comment by oSumAtrIX** [comment]
Click on share and select any external downloader. Anything beyond that is complicated.

**Comment by tim-gromeyer** [comment]
> Click on share and select any external downloader. Anything beyond that is complicated.

I cannot share my "Songs I liked" (I hope the translation is correct) because it is automatically generated, private and there is no share button. This is my main problem and I have to manually download every single song, piece by piece. Very annoying.

**Comment by oSumAtrIX** [comment]
You can share any song on YouTube Music.

**Comment by KTibow** [comment]
@oSumAtrIX the user is clearly referring to downloading the whole playlist. There are other playlists you might also want to download as a whole.

Of note: I used to have a Premium trial that expired and I was still able to play some songs from my "offline mixtape" for a bit.

**Comment by oSumAtrIX** [comment]
Like I said, the liked playlist is a playlist you can download

**Comment by KTibow** [comment]
To reiterate, you cannot share a playlist, so you have to "manually download every single song, piece by piece", which as they said is indeed annoying.

**Comment by oSumAtrIX** [comment]
Again, the playlist is a regular playlist and can be downloaded as a whole: https://music.youtube.com/playlist?list=LM

As its private you need to authenticate yourself to the API just like any other private playlist. I hope I don't have to repeat myself another time

**Comment by KTibow** [comment]
Correct me if I'm wrong but the popular downloaders Seal and NewPipe don't support authentication and can't download your offline mixtape, so they don't really solve the problem.

**Comment by oSumAtrIX** [comment]
Neither seal or newpipe are affiliated with us so if you have a problem with them you should open an issue on their end

**Comment by KTibow** [comment]
Let me make myself as clear as possible:
- If ReVanced had a patch that would allow for downloading, the app would be extremely convenient to use.
- Right now, there is **no** way to download your offline mixtape. 
- Right now, downloading your liked songs is **not easy**.
  - Option 1: click through each song to a downloader. This is very slow, you likely couldn't download more than 10 songs each minute of time spent on this.
  - Option 2: find a downloader app, find a way to add cookies, and try to find a way to download your liked songs. This is an unintuitive process that you couldn't figure out without instructions, as demonstrated by the other confused users here. 
- Therefore, it's not true to say "we don't need to do this because you can already accomplish this with other methods", because those other methods don't solve the whole problem.
- I hope you can understand my point. This issue isn't about how to accomplish a task with some other method, it's about a specific patch that is needed to complete the premium feel.

**Comment by oSumAtrIX** [comment]
The playlist grows, you usually need this feature once, otherwise you"d be downloading duplicates. Therefor the extreme additional convenience is over exaggerated.

If at all, just like for YouTube the DL patch will work similarly, how you handle the downloads with your external downloader will be out of scope.

**Comment by KTibow** [comment]
Ideally this would work exactly the same way as it does for a Premium user. You can download a playlist and it auto updates. You can flip on the offline mixtape and recently downloaded switches and it auto downloads.

If this isn't going to be implemented anytime soon, it would at least be helpful to make it clear to the users that the download button and related settings are broken.

**Comment by oSumAtrIX** [comment]
The implications involved to do that are the reason why an external downloader is used for the YouTube app. Feel free to suggest how to make it clear.

**Comment by sayyid5416** [comment]
For instance, the [YT-DL](https://github.com/ytdl-org/youtube-dl) library can download songs from YouTube Music. So, why can’t a similar feature be implemented using a ReVanced patch?

Here’s a potential implementation idea:
- A YouTube download handler could be set to run in the background.
- Whenever a user attempts to download a song or playlist, the download is managed by the background YouTube downloader.
- If a user tries to play a song while offline, the song could be played from the downloaded version.

This is just a rough idea and would need further refinement.

**Comment by oSumAtrIX** [comment]
See my previous message

**Comment by KTibow** [comment]
> The implications

I'd be curious about what they are. Is it just that it would be complicated to hook in to the offline system, or is there another factor?

> how to make it clear

If the user doesn't have premium and doesn't have any current downloads, hide the downloads section in Settings and in Library.
If the user doesn't have premium, hide the Download button in all context menus.

**Comment by KTibow** [comment]
> That requires making an API call to check for the case to hide the download buttons or extensively reverse engineer the app to find the APIs that return that condition.

I find it interesting that despite the fact that we know how to override the premium check, we don't know how to check if the user originally had premium.

**Comment by oSumAtrIX** [comment]
No, that is not enough

**Comment by oSumAtrIX** [comment]
Anyways, I just realized what this issue is about and it's too much effort for the miniscule gain it gives. Use an external downloader
