### ISSUE TITLE
feat(YouTube): Unlock 1080P premium quality 

### ISSUE THREAD

**Issue by LunaWuna** [ReVanced/revanced-patches#509]
### Application

YouTube 

### Issue

Allowing 1080P premium to be streamed without owning premium.

### Patch

It seems YouTube doesn't seem to require premium to actually access it since you can download the 1080p premium video using yt-dlp or something similar. I assume it would be possible to patch it in revanced to allow this.

### Motivation

1080P premium is getting rolled out and is appearing on more and more videos and makes a huge difference. I think the entire revanced community will benefit from higher bitrates on 1080P. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
