### ISSUE TITLE
(YouTube) Make timestamp setting permanent 

### ISSUE THREAD

**Issue by 111ebobo** [ReVanced/revanced-patches#53]
### Feature description

![Screenshot_20231129-220130](https://github.com/ReVanced/revanced-patches/assets/104251188/66b4f5d3-b37b-49fe-b0e3-979193c6b269)
Make this thing able to be permanent and not reverting back to regular timestamp 

### Motivation

For some people is more comfortable to see how long to the end of the video but not the current timestamp of the video 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
