### ISSUE TITLE
feat: chatGPT - remove play store requirement

### ISSUE THREAD

**Issue by shadoxxhd** [ReVanced/revanced-patches#538]
### Application

chatGPT (the official android application by OpenAI)

### Issue

The application can't start if play store is disabled (or otherwise not installed).

### Patch

The application should never check what other apps I have installed, and start whether or not play store is enabled.

### Motivation

Store-specific lock in is extremely user-hostile behavior, and prevents anyone who is either security-conscious (reading play store ToS is not fun), on a Huawei device, or simply on an older android, from using the app at all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
