### ISSUE TITLE
feat(YouTube): Hide player overlay that appears after double tapping to skip forward/backwards

### ISSUE THREAD

**Issue by Mohammed1520** [ReVanced/revanced-patches#540]
### Application

YouTube 

### Issue

No issue 

### Patch

Hides the dark filter layer from the player's background. (I mean the darkness of video on douple tap to seek for example 10 seconds)
![Hide-player-overlay-filter](https://github.com/ReVanced/revanced-patches/assets/107951133/7dd57fde-125e-4128-9197-2c98472138d1)

### Motivation

It is better as when you use  double tap to seek feature, the video doesn't get darker 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Mohammed1520** [comment]
No it still the same as video i had posted in the issue template

**Comment by GKid94** [comment]
Same
![Screenshot_2024-04-28-12-36-56-555_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/1a957ccc-ca12-485a-861e-119f7a76cc13)
![Screenshot_2024-04-28-12-45-36-094_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/cd660759-c635-4d33-b570-7fcf383b9b27)
![Screenshot_2024-04-28-12-47-41-947_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/545d2218-54ee-4737-a8c6-0ce9f352d782)

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
