### ISSUE TITLE
feat: Outlook - remove ad banner

### ISSUE THREAD

**Issue by floriegl** [ReVanced/revanced-patches#563]
### Application

Outlook - com.microsoft.office.outlook

### Issue

Annoying ad banner on top of email list

### Patch

![IMG_20230723_172439](https://github.com/ReVanced/revanced-patches/assets/22279483/ad092a0b-c549-484d-acae-b38c132704e8)

Hide this banner whenever it appears on top of the email list.

### Motivation

The outlook app has a high user count (over 500 million download) and is actually has a good user interface compared to some other Microsoft products. From what I have noticed it handles multiple folders and email aliases way better than most third party email clients. Also the patch shouldn't be that hard to create as it only should hide one element (as there aren't any other ads when you configure the app correctly).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!

**Comment by Julmik647** [comment]
I think that there are some other Email clients that support Outlook.
