### ISSUE TITLE
bug: Brightness when viewing hdr videos is reset to auto

### ISSUE THREAD

**Issue by bozander** [revanced/revanced-patches#588]
### Type

Other

### Bug description

when you turn on the HDR video, the brightness is reset to auto, that is, for example: you open the video with a swipe, you change the brightness (it changes) and after a second (sometimes even during the "setup") it returns to its original position "Auto" (checkboxes for adjusting the brightness are checked in the settings and volume with swipes). Normal videos without HDR work fine, brightness settings are not reset.

### Steps to reproduce

Step 1. Launch Youtube Revanced
Step. 2. Enable swipe control for brightness in Revanced settings.
Step. 3. Start hdr video
Step. 4. Adjust the brightness level with a swipe.

### Relevant log output

```shell
Missing
```

### Solution

Not found

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Canny1913** [comment]
Not a bug. You can disable auto HDR brightness in settings.

**Comment by Canny1913** [comment]
ReVanced Settings -> Miscellanous

**Comment by bassmadrigal** [comment]
Is there supposed to be a feature to enable max brightness when rotated to landscape like Vanced had? On reddit, a user said their YouTube ReVanced did this, but it has not worked for me at all regardless of whether this setting is enabled, disabled, or the patch not even used. I'm not sure if this patch is even related to that feature.

For mine, if I enable max brightness, it will keep future videos at max brightness until I close the app (not just background it) and reopen it. At that point, it will go back to auto-brightness.

If this is broken on my phone (rather than something that isn't implemented), I can post a new issue. Possibly related to #647.
