### ISSUE TITLE
feat (YT Music/`Disable Auto Captions`): Disables Forced Captions on Video-Only Songs

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patches#603]
### Application

YT Music

### Issue

Currently, YT Music lacks several customization features that could greatly enhance user experience and personalization within the music streaming platform. I would like to propose the implementation of several theming and customization options for YT Music, similar to the features available in the YouTube app.

### Patch

Provide an option to disable auto-generated captions in video songs. Some users may find the auto captions distracting or prefer to view the content without captions, and having the ability to disable them would enhance their viewing experience.

### Motivation

By implementing these theming and customization options, YT Music will offer users greater control over their experience and allow them to tailor the app according to their preferences. These enhancements will contribute to a more personalized and enjoyable music streaming experience overall.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
