### ISSUE TITLE
feat(reddit): Add removed home feed sort controls

### ISSUE THREAD

**Issue by mjtimblin** [ReVanced/revanced-patches#617]
### Application

Reddit

### Issue

Reddit removed the home feed sort controls in favor of always sorting by best.

https://old.reddit.com/r/reddit/comments/zmo8hm/the_feed_read_chapter_two_take_control_of_your/

### Patch

I would like to see the removed home feed sort controls (rising, controversial, top) added to the official reddit app. I personally prefer sorting by top of last 24 hours, but all the missing sort options would be ideal.

### Motivation

The official reddit app used to have the functionality, but it was removed. With the recent killing of 3rd party apps, this was the first annoying missing feature I noticed when switching to the official app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
