### ISSUE TITLE
feat(patch): Update patches for Sync for Reddit to target versions 19.x

### ISSUE THREAD

**Issue by thx1e** [ReVanced/revanced-patches#662]
### Application

Sync for Reddit

### Issue

UI/UX issues.

Left sidebar is not a sliding panel navigation drawer in tablet mode/dual pane on [v20+](https://github.com/laurencedawson/sync-for-reddit/issues/1475).
It's the case on v19.x.

Revanced patches aren't compatible with 19.x versions of Sync for Reddit.

### Patch

Update patches for Sync for Reddit to target versions 19.x

### Motivation

Get a better UI/UX on tablet.
Get full two columns navigations on tablet without a constant left sidebar.

Level of difficulties:
I tried but failed to get myself the origin_client_id using mitmproxy, run and adapt a [custom_client_id.py](https://gist.github.com/TheManchineel/386717249f4fa0cc8a69d8122bbff245)
but since Android 7, apps ignore user provided certificates.

Edit:
I managed to get the origin client id and make the py script run by patching the apk using [apk-mitm](https://github.com/shroudedcode/apk-mitm).
It redirects successfully to the created app linked to the account when Logging in, but displays "Login Error" when allowing the created app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Should be fixed

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
