### ISSUE TITLE
feat(youtubemusic): sort albums by recency by default

### ISSUE THREAD

**Issue by bennett-sh** [ReVanced/revanced-patches#696]
### Application

YouTube Music Revanced

### Issue

Recently YTM has replaced the individual singles & albums shelves with a single top releases shelf sorted by popularity.

### Patch

Currently the default sorting is by popularity. It should be replaced with recency (which already is an option under a few clicks so it shouldn't be too hard).

### Motivation

Popularity is a changing factor which often promotes the worst/"poppiest" songs, hides great work & makes navigation of artist profile inconsistent.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
