### ISSUE TITLE
feat: Bypass Sign in of Adobe Products

### ISSUE THREAD

**Issue by anxiouslelimo** [ReVanced/revanced-patches#725]
### Application

Photoshop Express Photo Editor (https://play.google.com/store/apps/details?id=com.adobe.psmobile)
Lightroom Photo & Video Editor (https://play.google.com/store/apps/details?id=com.adobe.lrmobile)

### Issue

Sign in mandatory to use the app.

### Patch

Patch to disable sign in prompt so that the apps can be used without signing in.

### Motivation

Since these apps cannot be used without sign in, it is bad from a privacy standpoint as Adobe is known to often use privacy invasive features.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
