### ISSUE TITLE
bug: ads on YouTube frontpage

### ISSUE THREAD

**Issue by Osahashi** [revanced/revanced-patches#761]
### Type

Cosmetic

### Bug description

On my Huawei MediaPad M5, Android 9, EMUI 9.1.0, I see ads on the front page. I've been re-patching, clearing cache, deleting data, turning ads on and off for the last few days but they are still there.

### Steps to reproduce

Manager 0.0.30 mit YouTube apk 17.36.37 gepatchet.

### Relevant log output

```shell
not needed
```

### Screenshots or videos

![Screenshot_20221011_004928_app revanced manager flutter](https://user-images.githubusercontent.com/22057956/194963929-5560bac1-0e6f-416d-ac34-28562d77b8b2.jpg)
![Screenshot_20221011_004910_app revanced manager flutter](https://user-images.githubusercontent.com/22057956/194963954-bb588094-3fb6-44f3-a0fd-674c2d911daf.jpg)
![Screenshot_20221011_005000_app revanced android youtube~(1)](https://user-images.githubusercontent.com/22057956/194963977-a8e3d48a-ab56-4ca2-933c-2beec06e1d01.jpg)
![Screenshot_20221011_005015_app revanced android youtube~(1)](https://user-images.githubusercontent.com/22057956/194963988-f709b585-69a1-4ac7-84d4-864731cbc35e.jpg)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#206.

**Comment by Osahashi** [comment]
That is not the same issue in my opinion, I don't have an Samsung device and I always have the ads, the are not randomly or rarely like people say in the issue #206, the ads are always there

**Comment by oSumAtrIX** [comment]
It's the same type of ad and a patch for them would close both issues the same way, hence a dupe.

**Comment by TheNoFace** [comment]
> the are not randomly or rarely like people say in the issue #206, the ads are always there

It looks like this issue is only on tablet landscape mode, no matter what brand the table or phone is. My samsung table also has ads showing always on main and player ui unless reverting resource patch commit.

However devs are no more using resource patch method, so just wait patiently until they come across another solution.
Personally, I use my own fork of patch that use resource patch for hiding cosmetic ads. Try this one: [`revanced-patches`](https://github.com/TheNoFace/revanced-patches)
