### ISSUE TITLE
feat: Tidal - show bitrate

### ISSUE THREAD

**Issue by Roki100** [ReVanced/revanced-patches#767]
### Application

Tidal

### Issue

Currently only master quality tracks show current bitrate

### Patch

Display current bitrate and sample rate the song is straming at

### Motivation

Nerds and audiophiles like real numbers, so why not get a bitrate display on every song :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
