### ISSUE TITLE
feat: hide youtube shorts that have less than x likes or without titles

### ISSUE THREAD

**Issue by Matszwe02** [ReVanced/revanced-patches#768]
### Application

com.google.android.youtube

### Issue

It's known that shorts are random and sometimes some shitty ones appear, made by users with one-digit subscribers and not relevant. What if they were hidden from shorts?

### Patch

hide shorts that have less than x likes (settable by users, 100-1000 is a great starting point), or / and hide shorts that have no titles (ie. "`6 june 2023`")

### Motivation

While scrolling through shorts I often find these shorts that are just static images or other non-informative content. I want some useful shorts to show up, not these ones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
