### ISSUE TITLE
feat: New "unwatched" recommended feed filter for YouTube

### ISSUE THREAD

**Issue by JakSla806** [ReVanced/revanced-patches#772]
### Application

YouTube

### Issue

Recommending already watched videos in the feed, both on the homepage and below videos

### Patch

I would love to see a patch that adds an "unwatched" filter to the feed. It would make it to where the feed only shows videos that YouTube recommends, but not ones that I've already seen. There is already a "new to me" filter, but I'm not talking about that. That recommends videos that aren't based on stuff I might like.

### Motivation

Because having already watched videos, over and over, recommended to you is very annoying. This patch would make the recommended feed a whole lot more efficient and more relevant to the individual.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
