### ISSUE TITLE
feat: YouTube music cross-fading

### ISSUE THREAD

**Issue by Caps2357** [ReVanced/revanced-patches#774]
### Application

app.revanced.android.apps.youtube.music

### Issue

When ending a song, it instantly changes to the next song without an option to gradually start the next song.
Spotify has this features and you can select the amount of time between the fading.
![image](https://github.com/revanced/revanced-patches/assets/111622306/2f0a316f-a904-4129-b395-4ba0989f8238)

### Patch

I would like a patch that adds a slider for a transitional period between songs, it slowly fades out the currently playing song and gradually raises the next song volume to gaplessly fade into each other.

### Motivation

This patch would be amazing because I know quite a few people that has switched away from YouTube music for this exact reason and I believe that a lot of people would value the option for it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
