### ISSUE TITLE
feat(reddit): Show usernames in home feed

### ISSUE THREAD

**Issue by jordan1776** [ReVanced/revanced-patches#786]
### Application

reddit

### Issue

Display username in posts in the home feed. At some point reddit removed this feature. I believe this should be added back into the app, as well as display in classic view (which it never did)

### Patch

On the home feed, posts in 'card' view should read:
r/subreddit 
u/user • 1h • i.redd.it

Same as before.

And for 'classic' view the post should display
r/subreddit • u/user • 1h • i.redd.it

I am not sure how very long username and subreddit combinations should be handled, maybe by making it 2 lines and having the post slightly taller or by trailing off the line?

### Motivation

This would help to keep the app more user focused, by actually showing the username of the person who submitted the post in the main feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
