### ISSUE TITLE
feat(youtube): hide 'subtitle/CC turned on/off' popup

### ISSUE THREAD

**Issue by RamPawar7** [ReVanced/revanced-patches#799]
### Application

Youtube (com.google.android.youtube)

### Issue

When watching a video in full screen mode, the popup 'Subtitles/CC turned on' that appears on the bottom left corner when enabling the Subtitles/CC is overlayed on top of the subtitles and hides them behind it for about 4 seconds.

### Patch

The patch will have option to either disable the 'Subtitles/CC turned off/on' popup completely or reduce the time for which the popup stays on screen. This can also be applied to other similar popups.

### Motivation

Many people that usually keep the subtitles turned off, whenever they don't understand a word or a sentence said in a video, they turn on subtitles briefly to read what was said. But they need to wait for this annoying popup to disappear and then they can rewind the video to read the subtitles.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
