### ISSUE TITLE
feat: Google Dialer Call Recording

### ISSUE THREAD

**Issue by Pheggas** [ReVanced/revanced-patches#825]
### Application

Phone By Google [package com.google.android.dialer](https://play.google.com/store/apps/details?id=com.google.android.dialer)

### Issue

When using Google Dialer in European countries, users can't use call recoring feature without rooting their phone. You used to be able to record phone calls via pre-patched Google Dialer apps which aren't maintained anymore.

### Patch

I'd like to see a patch which enables the call recording feature in the Google Dialer app. It is possible by editing the values in Phenotype database of Google Play Services as [GAppsMod](https://github.com/jacopotediosi/GAppsMod) did it.

### Motivation

Users that live in countries where call recording is not allowed doesn't have convinient way to replay calls to recall what they said in terms of date dealing for example.

PS: There is [another patch request](https://github.com/revanced/revanced-patches/issues/1789) tied with Google Dialer

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Pheggas** [comment]
Any update on this?

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
