### ISSUE TITLE
feat(patch): Universal themes

### ISSUE THREAD

**Issue by Ludonope** [ReVanced/revanced-patches#839]
### Application

all

### Issue

Some apps do not use the device's theme (dark/light) but still use a `colors.xml` file.

### Patch

A patch that allows to override or customize the `colors.xml` with presets or manual colors.

### Motivation

That could help with many apps that fall into that category but do not have enough attention to get a custom patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
