### ISSUE TITLE
feat: (Tumblr) Remove Blaze Posts

### ISSUE THREAD

**Issue by LadyHaywood** [ReVanced/revanced-patches#84]
### Feature description

I thought the "remove ads" patch fixed this since the way blaze posts work on the app is same way ads and sponsored post do. I also didn't see them for awhile until just now and they seem to be showing up more often.

![Screenshot_20231121_035316](https://github.com/ReVanced/revanced-patches/assets/10987703/2e8f9f21-b4cb-4181-995e-6edba1abcb7f)

### Motivation

Blaze posts are just user ads

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
