### ISSUE TITLE
feat(youtube): hide comment 'sort by' menu options

### ISSUE THREAD

**Issue by Jakenevada** [ReVanced/revanced-patches#856]
### Application

Youtube:Revanced

### Issue

I had issues with a patch that brings old filter button cause it would show all of the action buttons such as clip,download and support even with this being turned off in options so i thought if it could be repaired if not i would like to request ability to hide sorting from newest to oldest in coments
![343442490_6010398189057902_6054958994849699502_n](https://github.com/revanced/revanced-patches/assets/132659424/bf867374-4aa7-4674-bd22-b54e2283a87f)

### Patch

Above

### Motivation

Fix of a glitch if possible/Customization opption like filter buttons

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
