### ISSUE TITLE
feat(youtube): remove related videos under the video player

### ISSUE THREAD

**Issue by matt873** [ReVanced/revanced-patches#886]
### Application

YouTube

### Issue

An option to remove related videos under the video player to reduce distraction.

### Patch

I have added a screenshot from NewPipe for just a demonstration and idea of this feature.
![Screenshot_20230526-003019](https://github.com/revanced/revanced-patches/assets/108935493/939aff27-6932-4bd2-9baa-c7dfbd778a81)
![Screenshot_20230526-002853](https://github.com/revanced/revanced-patches/assets/108935493/251be576-4381-479d-8694-9ba470bce4a7)

### Motivation

This will help save time and not be distracted by youtube algorithm.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DrSapling** [comment]
> You can use the `related_video` custom filter to achieve this. However, it is risky because the app will continually try to load the related videos, and the YT API might consider it API abuse, and then ban your YT user.

And there is not option to hide shorts under video. Hiding shorts entirely would remove them from subscriptions feed. A patch to remove videos and shorts under video would be nice.

Moreover, I might be wrong, but custom filters onyl hide components, not remove them, so they still load in background. So, if we were to use `related_video` filter and let's say `related_short` (which afaik does not exist) it would lead to api abuse loading more and more hidden videos?

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
