### ISSUE TITLE
Turn on Android 11+ bubble style for Facebook Messenger

### ISSUE THREAD

**Issue by kongacute** [ReVanced/revanced-patches#891]
### Application

Facebook Messenger

### Issue

Some device will only have Android bubble and some have old style Messenger Chat Head.

### Patch

Force Messenger use Android Bubble instead of old Chat Head.

### Motivation

Some people like to use Android bubble. There are already have patch for that but doesn't allow to export apk file after patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
