### ISSUE TITLE
feat: (Tumblr) Remove anything badge related from view

### ISSUE THREAD

**Issue by LadyHaywood** [ReVanced/revanced-patches#90]
### Feature description

Would like to have the badges that show beside usernames not visible as well as removing the "add badge" button on your blog  that shows up on any version of the app above v28.6.0.110

![Screenshot_18](https://github.com/ReVanced/revanced-patches/assets/10987703/dcef707c-8dd2-42ad-b6af-5decaf62586e)

### Motivation

I've had problems where too many badges will overlap(?) the follow button at times as seen in the photo.
I also just really don't seeing them.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
