### ISSUE TITLE
feat(twitch): vod subscriber bypass

### ISSUE THREAD

**Issue by Mylloon** [ReVanced/revanced-patches#907]
### Application

Bypass VOD who are suscribers-only

### Issue

Ability to see any VOD

### Patch

When opening a VOD for suscribers-only, bypass the restriction and play the video

### Motivation

It's a nice to have, and already exists in others app like PurpleTV. Also an [extension exists for browsers](https://github.com/besuper/TwitchNoSub) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
