### ISSUE TITLE
feat(patch): GBoard and SwiftKey - Custom Clipboard History Expiration

### ISSUE THREAD

**Issue by Stale-1** [ReVanced/revanced-patches#913]
### Application

Microsoft SwiftKey
GBoard

### Issue

1) Clipboard History automatically expires in 1 Hour.
2) Limited Clippet Maximum History
SwiftKey can store upto 30 clippets.
GBoard can store upto 20 clippets. 

3) Sometimes when filling up forms(login) the option for opening the ClipBoard Manager is not visible. 
### Patch

1) Ability to Change Clipboard Expiration
2) Ability to Change the Maximum Number of Clippets it can Store. 
3) Ability to open ClipBoard Manager by holding the SpaceBar
And/Or Add a Button in right side of suggestion bar. 
![IMG_20230523_222431](https://github.com/revanced/revanced-patches/assets/74855954/48eb8355-cbd0-43d4-90b5-827ff45b38ff)

### Motivation

GBoard and SwiftKey are currently the most popular Keyboard in Android. But it lacks customization in the Clipboard Manager.

Native Clipboard is a great addon but:
1) It requires Accessibility or Root. Most Android would automatically turn off Accessibility so it is quite a hassle to set it up every now and then.
2) It is too old and doesn't work in newer Devices. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
