### ISSUE TITLE
feat(patch): Spotify Custom playback speed for Songs

### ISSUE THREAD

**Issue by fatalcoder524** [ReVanced/revanced-patches#941]
### Application

Spotify

### Issue

Changing custom playback speed for Songs without download.

### Patch

I'm not sure if this is possible but is it possible to add a patch to support custom playback speed like YouTube or Spotify podcasts to Spotify music!.

### Motivation

Depending the taste of users songs and demand for this feature, current solutions require either to download songs offline or use chrome extention and view it in a pc. If it is possible in the app itself, it will be a great feature addition.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
