### ISSUE TITLE
feat(patch): Tiktok Lite: Download, Seekbar and Speed Button; Remove Ads; View Photos + Maximum Quality

### ISSUE THREAD

**Issue by Stale-1** [ReVanced/revanced-patches#948]
### Application

TikTok Lite

### Issue

Currently, only the Tiktok app is supported.

### Patch

TikTok Lite Patches
* Remove Ads
* Enable Download Button (Always)
* Enable Seekbar (Always)
* Add Video Speed Option
* Enable Maximum Video/Photos Quality

TikTok Lite currently don't support TikTok Photos
* If possible: Enable TikTok Photos
* If not: Add button to Download Photos instead

### Motivation

1) A lot of people with Low Budget Phones use TikTok Lite.
2) Not all people really make TikTok Videos, some just watch it. (Original TikTok consumes a lot of space due to features/filters in making Videos)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
