### ISSUE TITLE
feat(patch): Working Fullscreen quick actions on tablets

### ISSUE THREAD

**Issue by zzahkaboom24** [ReVanced/revanced-patches#960]
### Application

YouTube ReVanced

### Issue

Not working quick actions in fullscreen mode when watching a YouTube video. First Screenshot is on tablet, second screenshot is on mobile for comparison.

![Screenshot_20230513_201356](https://github.com/revanced/revanced-patches/assets/42496614/de6456b0-4236-49d9-8508-ba66371602ef)

![Screenshot_20230513_201938](https://github.com/revanced/revanced-patches/assets/42496614/5dba3d07-9253-4fdb-a9c3-c4c354b0553f)

Note that quick actions in fullscreen do not work in the normal YouTube client on tablets, whereas they do work on mobile. I hope this is achievable for tablets as well somehow.

### Patch

Basically the quick actions in fullscreen patch, but working for tablets as well.

### Motivation

It adds quick actions when watching videos in fullscreen basically improving the "productivity" when in fullscreen. I also think tablet users would appreciate when this feature actually works for them as well and not keeping it to mobile only.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
