### ISSUE TITLE
feat(patch): prefer music uploads over videos in albums on youtube music

### ISSUE THREAD

**Issue by selfisekai** [ReVanced/revanced-patches#969]
### Application

com.google.android.apps.youtube.music

### Issue

youtube music for some reason prefers the ids of music videos over the "provided to youtube by [legal rights owner]" uploads.

as an example comparison (same behavior happens on web between `WEB` and `WEB_REMIX`):
on https://music.youtube.com/playlist?list=OLAK5uy_msgnHMUuF-Zp3m_jb9W_TwtNvHiVPem9I, a song resolves to https://music.youtube.com/watch?v=-iM83TiKdY0
on https://www.youtube.com/playlist?list=OLAK5uy_msgnHMUuF-Zp3m_jb9W_TwtNvHiVPem9I (same ID), the same song resolves to https://www.youtube.com/watch?v=Y90uO6SG5WE

### Patch

when making a request to innertube `/browse` endpoint, and `browseId` (that's how the key is called in JSON, idk about protobufs) starts with `VLOLAK5uy_`, make the request as `ANDROID` rather than `ANDROID_MUSIC`. not sure if more handling to the response is also needed.

### Motivation

annoyed by stupid behavior that can probably be avoided

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
