### ISSUE TITLE
bug: Yuka patch has not been working since Yuka v4.24

### ISSUE THREAD

**Issue by smtgpm** [ReVanced/revanced-patches#97]
### Bug description

So the manager still suggests that any version of Yuka can be patched, but I've been trying every update since Yuka 4.24 (I think it was 4.24 the last working version, not sure) and all of them have Yuka not starting up once the patches have been applied. 
I instanll via mount (root)
On apkmirror also there is no apk anymore only bundle so latests updates were only possible via Mount, but I'm pretty sure when there still were apks released after 4.24 it was crashing all the same
It keeps crashing on start, app launches and crashes instantly

Android 12
Root

### Error logs

```shell
Ran 
logcat | grep AndroidRuntime
On termux on my android but no log shows mentioning AndroidRunTime
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by jacopotediosi** [comment]
> So in conclusion, last working version is 4..29, doesn't matter if it's installed as apk or bundle. The only weird thing is that after 4.29 there are no apks anymore on apkmirror, only bundles, but that might also just be a coencidence

It's not a coincidence.

Starting from Yuka version 4.29, releases are not only compiled as bundles but also include the `libpairipcore.so` library. This library introduces a new integrity protection mechanism called "Pairip", which is added directly by the Play Store during bundle creation.

Due to this protection, the patched application crashes, as shown in the following logcat output:

```
03-14 18:52:28.946 20125 20125 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb400007aa45fb549 in tid 20125 (io.yuka.android), pid 20125 (io.yuka.android)
03-14 18:52:29.059 20148 20148 F DEBUG   : Cmdline: io.yuka.android
03-14 18:52:29.059 20148 20148 F DEBUG   : pid: 20125, tid: 20125, name: io.yuka.android  >>> io.yuka.android <<<
03-14 18:52:29.059 20148 20148 F DEBUG   :       #00 pc 00000000000307a0  /data/app/~~jF0wiBzP5mgarIhQqSQI8g==/io.yuka.android-z7LgzAZgDsr5qWkygV40pw==/lib/arm64/libpairipcore.so
```

Essentially, part of the application code runs inside an obfuscated virtual machine (VM) that performs various integrity checks. Even runtime patches (Frida, LSPosed, etc.) are neutralized by this protection mechanism.

I believe Revanced will soon need to find a way to bypass Pairip; otherwise, patching any app in the future could become impossible.

Useful references:
- https://matrixeditor.github.io/pairipcore-vm/
- https://blog.byterialab.com/reversing-googles-new-vm-based-integrity-protection-pairip/
