### ISSUE TITLE
feat(youtube/general-ads) Hide  "Get Youtube Premium" ad in description of music videos.

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches#984]
### Application

Youtube

### Issue

Hide Get Youtube Premium advertisement in the video description of music category videos.
Example:
![Screenshot_20230511_160847_YouTube](https://github.com/revanced/revanced-patches/assets/30195961/7e08735a-0642-4a6a-aab3-90945543e444)

### Patch

Hide Get Youtube Premium ad as a part of General Ads patch.

### Motivation

Motivation being clean and clutter free UI experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
