### ISSUE TITLE
Add play/pause button in Instagram reels player

### ISSUE THREAD

**Issue by sams452m** [ReVanced/revanced-patches#99]
### Feature description

There should be play/pause button in Instagram reels like yt shorts.

### Motivation

Firstly we don't have to hold the reel for a while to read something and we can start our reel from the pause part we don't need to find the exact timeline also it prevents autoplay of reel while reading comments.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Over time, a lot of feature requests have been made, which is why I am closing some according to the [contribution guidelines](https://github.com/ReVanced/revanced-patches/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long
- Low priority
- Maintainers un-interested
- Too complex to realize

Regardless, anyone who comes across this feature request can PR it. Thanks for the feature request!
